### ISSUE TITLE
 An error occurs at startup when running GAMA_2024.02.0 on windows installed using:  GAMA_2024.02.0_Windows_with_JDK_24.02.24_.exe  and GAMA_2024.02.0_Windows_with_JDK_24.02.24_.zip. 

### ISSUE THREAD

**Issue by jmbangate** [gama-platform/gama#103]
**Describe the bug**

An error occurs at startup when running GAMA_2024.02.0 on windows installed using:

GAMA_2024.02.0_Windows_with_JDK_24.02.24_.exe
GAMA_2024.02.0_Windows_with_JDK_24.02.24_.zip 

**To Reproduce**
1. Install on windows version of gama 2024.02.0 with jdk (both exe and zip)
2. Run Gama.exe on install folder or using created desktop shortcut.
3. Message pops: An error has occured .. see logs ...
4. Logs below

//-----------------------------------------------------------------

!SESSION 2024-02-28 07:46:25.666 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  ./jdk/bin/javaw-vm-startup ./jdk/bin/javawplugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar
Command-line arguments:  -os win32 -ws win32 -arch x86_64 ./jdk/bin/javaw-vm-startup ./jdk/bin/javawplugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar -data @noDefault

!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2024-02-28 07:46:26.241
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.simpleconfigurator [2]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

!ENTRY org.eclipse.osgi 4 0 2024-02-28 07:46:26.241
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.equinox.simpleconfigurator_1.5.0.v20230919-1457.jar was not resolved.

!ENTRY org.eclipse.osgi 4 0 2024-02-28 07:46:26.257
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

//-----------------------------------------------------------------

**Expected behavior**
Gama would load :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - PC Model: HP ZBook Power G7 Mobile Workstation, 32GB, Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
 - GAMA version: 2024.02.0
 - Java version: 1.8.0_45
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

Merci,

Julius

**Comment by lesquoyb** [comment]
Hello Julius,

I see two possible origins for your problem:

- you are using the same workspace as for gama 1.9.3, and in that case it's normal that it breaks because we changed a lot the internal structure of gama. In that case the fix is easy: just create a new workspace
- you have plugins installed from gama 1.9.3 (or previews versions), and that would break for the same reason of internal structure. In that case you will need to get rid of those plugins, if you are not sure where they are stored (I'm not exactly sure myself and on windows they are stored and referenced in two locations at the same time) maybe it's easier for you to just reinstall gama, if possible in a different directory. If you need to use those plugins you will have to wait for @RoiArthurB to finish publishing the plugins compatible with 2024-02 or go back to 1.9.3.

It could also be those two problems at the same time.

**Comment by jmbangate** [comment]
Thanks :)

**Comment by RoiArthurB** [comment]
@jmbangate did you identify your issue? Was it because of some plugins, some old workspace, nothing else?

Also, is your issue solved by what @lesquoyb recommended you? :)

**Comment by lesquoyb** [comment]
The lack of answer makes me think it's solved, so I'm closing the issue, feel free to reopen if it's not the case
