### ISSUE TITLE
Exception raised on a very basic model

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#113]
**Describe the bug**
Running a very simple model, end up in an IllegalArgumentException

**To Reproduce**

the model:

```
model Move

global {
	
	init {
		create a number:10;
	}
	
}

species a {
	
	point l;
	geometry shape <- circle(2);
	
	reflex move {
		location <- any_location_in(world.shape);
	}
	
}

experiment xp {
	
	output {
		display main {
			species a;
		}
	}
	
}
```

1. Copy past the model
2. Run it for few second
3. See the error

**Expected behavior**
Raise no exception

**Desktop (please complete the following information):**
 - OS: macOS (M1)
 - GAMA version: 1.9.3 and git 2024_02

**Comment by lesquoyb** [comment]
I tested on the git version and didn't see the error in the user interface, everything run normally.
Though in the eclipse console I get the error:
```
java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:133)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:32)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:347)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:46)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at gama.core.metamodel.shape.GamaShape.copy(GamaShape.java:620)
	at gama.core.metamodel.shape.GamaShape.copy(GamaShape.java:1)
	at gama.gaml.statements.AspectStatement.lambda$0(AspectStatement.java:150)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:512)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at gama.core.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at gama.core.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at gama.core.outputs.display.LayerManager.drawLayersOn(LayerManager.java:176)
	at gama.ui.display.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:273)
	at gama.ui.experiment.views.displays.LayeredDisplayView$2.run(LayeredDisplayView.java:347)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Java error: illegal argument
	at gama.core.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:72)
	at gama.core.outputs.display.LayerManager.drawLayersOn(LayerManager.java:179)
	at gama.ui.display.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:273)
	at gama.ui.experiment.views.displays.LayeredDisplayView$2.run(LayeredDisplayView.java:347)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:133)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:32)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:347)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:46)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at gama.core.metamodel.shape.GamaShape.copy(GamaShape.java:620)
	at gama.core.metamodel.shape.GamaShape.copy(GamaShape.java:1)
	at gama.gaml.statements.AspectStatement.lambda$0(AspectStatement.java:150)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:512)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at gama.core.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at gama.core.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at gama.core.outputs.display.LayerManager.drawLayersOn(LayerManager.java:176)
	... 3 more
```
I don't know why the exception is not showing at the user level for me but it is for you.
Also reading the error message, could it be related to [this old issues ?](https://github.com/gama-platform/gama.old/issues/3639)

**Comment by AlexisDrogoul** [comment]
Well. The error is not showing because it is raised in the UI (and more precisely the displays), where errors can be considered harmless. There is a preference to toggle this on or off.
