### ISSUE TITLE
Browser of a list of agents from the inspector

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1232]
```
What steps will reproduce the problem?
1. Open and run the model: Tutorials/Incremental model/Incremental Model 7.gaml
2. Run one simulation step
3. Inspect one of the green buildings
4. Browse the list of agents "people_inside"

What is the expected output? What do you see instead?
The browser view appears with an error:
java.lang.NullPointerException
	at msi.gama.gui.views.PopulationInspectView.fillAttributeMenu(PopulationInspectView.java:279)
	at msi.gama.gui.views.PopulationInspectView.access$6(PopulationInspectView.java:278)
	at msi.gama.gui.views.PopulationInspectView$3.modifyValue(PopulationInspectView.java:247)
	at msi.gama.gui.parameters.ExpressionControl.modifyText(ExpressionControl.java:68)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:179)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1471)
	at org.eclipse.swt.widgets.Text.setText(Text.java:2108)
	at msi.gama.gui.views.PopulationInspectView.createExpressionComposite(PopulationInspectView.java:259)
	at msi.gama.gui.views.PopulationInspectView.createToolItems(PopulationInspectView.java:708)
	at msi.gama.gui.views.actions.GamaToolbarFactory.buildToolbar(GamaToolbarFactory.java:192)
...

Please use labels and text to provide additional information.
```

Original issue reported on code.google.com by `patrick.taillandier` on 2015-05-27 01:39:40

**Comment by AlexisDrogoul** [comment]
The population browser needs a serious lifting… I will try to handle this on time for GAMA 1.7

**Comment by AlexisDrogoul** [comment]
This issue has been solved, but the population browser is not functional yet. I close it nevertheless.
