### ISSUE TITLE
NPE in MoleExperiment.dispose

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#1270]
I am updating the Gama OpenMOLE plugin. When using the latest git version of gama I get this exception when calling dispose:

```
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | java.lang.NullPointerException
 | 	at msi.gama.headless.openmole.MoleExperiment.dispose(MoleExperiment.java:92)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:125)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:94)
 | 	at org.openmole.plugin.task.external.ExternalTask$class.withWorkDir(ExternalTask.scala:175)
 | 	at org.openmole.plugin.task.gama.GamaTask.withWorkDir(GamaTask.scala:84)
 | 	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:94)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:48)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:48)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:84)
 | 	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:48)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:84)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:82)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:125)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
 | 	at java.lang.Thread.run(Thread.java:745)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:128)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:94)
	at org.openmole.plugin.task.external.ExternalTask$class.withWorkDir(ExternalTask.scala:175)
	at org.openmole.plugin.task.gama.GamaTask.withWorkDir(GamaTask.scala:84)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:94)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:48)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:48)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 12 more
```

**Comment by gnoubi** [comment]
we will check that when the new version of openmole plugin will available

**Comment by AlexisDrogoul** [comment]
I'm closing this issue as it concerns two versions of GAMA and OpenMole that are both 1 year and a half old.
