### ISSUE TITLE
NullPointerException in model RoadTraffic

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1371]
Does not work on model 5-6-7. Others seem ok.

Here is the error :

java.lang.NullPointerException
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:56)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:69)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:84)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:73)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:64)
	at msi.gama.runtime.AbstractScope.execute(AbstractScope.java:410)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:186)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:200)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:188)
	at msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:144)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:95)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:86)
	at msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:125)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at gaml.additions.GamlAdditions$112.run(GamlAdditions.java:197)
	at gaml.additions.GamlAdditions$112.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:63)
	... 26 more

**Comment by ptaillandier** [comment]
This bug is weird: the goto action seems to correctly return the path, but this one becomes nil in GAML... Something has changed concerning the way the skill actions are managed?

**Comment by AlexisDrogoul** [comment]
OK. My entire fault when pushing one commit this morning. In PrimitiveStatement.privateExecuteIn(), the line `result = helper.run(scope, agent, skill == null ? agent : skill);` had become `helper.run(scope, agent, skill == null ? agent : skill);`. No more assignment to result, and I dont remember why… Most probably a mistake when doing some copy/paste.
