### ISSUE TITLE
BDI model does not work

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1386]
I just added the "helicopter" model to the BDI Architecture project (in plugin models), based on the "Using BDI" recipe. I got a NullPointerException when I try to launch an execution at the first step.

```
java.lang.NullPointerException
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:56)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:69)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:74)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:74)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:84)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.simplebdi.SimpleBdiPlan.privateExecuteIn(SimpleBdiPlan.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:73)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:64)
	at msi.gaml.architecture.simplebdi.SimpleBdiArchitecture.executeOn(SimpleBdiArchitecture.java:127)
	at msi.gama.runtime.AbstractScope.execute(AbstractScope.java:410)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:186)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:200)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:188)
	at msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:144)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:156)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:95)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:489)
	at msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:86)
	at msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:125)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at gaml.additions.GamlAdditions$13.run(GamlAdditions.java:88)
	at gaml.additions.GamlAdditions$13.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:63)
	... 29 more
```

**Comment by mathieuBourgais** [comment]
I don't have any problems with the model. It works perfectly well.

**Comment by mazarsju** [comment]
Strange... Do you run the model with the latest git version or with gama 1.61 ? And is it the exact model I just put in the plugin models ?

**Comment by mathieuBourgais** [comment]
Yes, this is the exact model. It runs on the latest git version.

**Comment by mazarsju** [comment]
Ok, the model just works fine now, although I changed nothing... Very weird. Sry about that, I close the issue.
