### ISSUE TITLE
Error when clicking too fast on an experiment button after GAMA starting

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1435]
When I launch GAMA, if I click too fast on an experiment button, I get this error:

java.lang.NullPointerException
	at msi.gama.kernel.experiment.ExperimentAgent.setMinimumDuration(ExperimentAgent.java:356)
	at gaml.additions.GamlAdditions$219.run(GamlAdditions.java:266)
	at msi.gaml.variables.Variable._setVal(Variable.java:398)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:346)
	at msi.gama.kernel.experiment.ExperimentPopulation.createVariables(ExperimentPopulation.java:53)
	at msi.gama.kernel.experiment.ExperimentPopulation.createAgents(ExperimentPopulation.java:40)
	at msi.gama.kernel.experiment.ExperimentPlan.createAgent(ExperimentPlan.java:177)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:295)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:745)
Early startup of the XText UI plugin so as to ensure all services are setup

Note that my computer is very slow.

**Comment by AlexisDrogoul** [comment]
It seems that the IGui object is not pushed fast enough to GAMA when opening the application. I will try to make it faster !

**Comment by ptaillandier** [comment]
Note that I was not able to reproduce this bug today... so, we can maybe close this issue (if it reappears, I will reopen it).
