### ISSUE TITLE
Error in Diffusions model (and OpenGL exception)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1436]
Run the Anisotropic Diffusion (Cycle length) model.
You can observe that in the quick display, after several steps, the display is strange (the model makes some cells have a height increases more and more. At some point, the disappear).
In addition, when I reopen another model such as:
model new

global {
	init {
		ask int {
			write "hello";
		}
	}
}

experiment new type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}

I get the exception in the console: 

com.jogamp.opengl.GLException: Geometry building thread: Context not current on thread, inDestruction: false, obj 0x30eb52bc, ctx 0x0, isShared true, surf true 0x0, <5f5b61d8, 519c8443>[count 0, qsz 0, owner <NULL>]
	at jogamp.opengl.GLContextImpl.release(GLContextImpl.java:403)
	at jogamp.opengl.GLContextImpl.release(GLContextImpl.java:382)
	at ummisco.gama.opengl.scene.GeometryCache$GeometryAsyncBuilder.run(GeometryCache.java:113)
	at java.lang.Thread.run(Thread.java:745)

com.jogamp.opengl.GLException: Geometry building thread: Context not current on thread, inDestruction: false, obj 0x447f328, ctx 0x0, isShared true, surf true 0x0, <1a3bc236, 5f394f15>[count 0, qsz 0, owner <NULL>]
	at jogamp.opengl.GLContextImpl.release(GLContextImpl.java:403)
	at jogamp.opengl.GLContextImpl.release(GLContextImpl.java:382)
	at ummisco.gama.opengl.scene.GeometryCache$GeometryAsyncBuilder.run(GeometryCache.java:113)
	at java.lang.Thread.run(Thread.java:745)

**Comment by benoitgaudou** [comment]
Now a new exception is raised : 


com.jogamp.opengl.GLException: Drawable's handle neither NSView, NSWindow nor PBuffer: drawableHandle 0x0, isNSView false, isNSWindow false, isFBO false, isPBuffer false, jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
	MacOSXOnscreenCGLDrawable[Realized false,
	Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@1ececb56,
	Handle    0x0,
	Surface   WrappedSurface[ displayHandle 0x0
, surfaceHandle 0x0
, size 1459x643
, UOB[ ]
, MacOSXCGLGraphicsConfiguration[DefaultGraphicsScreen[MacOSXGraphicsDevice[type .macosx, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x61c0d413]], idx 0],
	chosen    GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/0, dbl, mono  , hw, GLProfile[GL2/GL2.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/8/0, dbl, mono  , hw, GLProfile[GL2/GL2.hw], on-scr[.]]]
, surfaceLock <6f07365b, 6b38bf63>[count 1, qsz 0, owner <Geometry building thread>]
, SWTCanvasUpstreamSurfaceHook[upstream: SWT-GLCanvas[Realized false,
	null-drawable,
	Factory   null,
	handle    0x0,
	Drawable size -1x-1,
	SWT size 1459x643], 1459x643]
, upstreamSurface false ]]
	at jogamp.opengl.macosx.cgl.MacOSXCGLContext$NSOpenGLImpl.getNSViewHandle(MacOSXCGLContext.java:583)
	at jogamp.opengl.macosx.cgl.MacOSXCGLContext$NSOpenGLImpl.create(MacOSXCGLContext.java:607)
	at jogamp.opengl.macosx.cgl.MacOSXCGLContext.createContextARBImpl(MacOSXCGLContext.java:266)
	at jogamp.opengl.GLContextImpl.createContextARB(GLContextImpl.java:986)
	at jogamp.opengl.macosx.cgl.MacOSXCGLContext.createImpl(MacOSXCGLContext.java:314)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:763)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at ummisco.gama.opengl.scene.GeometryCache$GeometryAsyncBuilder.run(GeometryCache.java:112)
	at java.lang.Thread.run(Thread.java:745)
