### ISSUE TITLE
Batch experiment throws RejectedExecutionException

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1601]
When I try to run batch experiment, the simulation crashes after a while with the following error : 

```
!ENTRY org.eclipse.ui 4 4 2016-03-01 16:46:25.167
!MESSAGE GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2bd2fdc9 rejected from java.util.concurrent.ThreadPoolExecutor@225308ce[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 594]
!STACK 0
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2bd2fdc9 rejected from java.util.concurrent.ThreadPoolExecutor@225308ce[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 594]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:151)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:172)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:98)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:60)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:139)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:492)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:88)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:121)
	at java.lang.Thread.run(Unknown Source)
GAMA Caught a workbench message : GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2bd2fdc9 rejected from java.util.concurrent.ThreadPoolExecutor@225308ce[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 594]
```

**Comment by mazarsju** [comment]
```
!ENTRY org.eclipse.ui 4 4 2016-03-01 16:58:28.240
!MESSAGE Closing Error View
GAMA Caught a workbench message : Closing Error View
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:58)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:494)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:88)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:121)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:151)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:172)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:98)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:60)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:139)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:492)
	... 3 more

!ENTRY org.eclipse.ui 4 4 2016-03-01 16:58:28.338
!MESSAGE GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
GAMA Caught a workbench message : GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]

!ENTRY org.eclipse.ui 4 4 2016-03-01 16:58:28.348
!MESSAGE GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
!STACK 0
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:151)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:172)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:98)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:84)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:60)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:139)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:492)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:88)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:121)
	at java.lang.Thread.run(Unknown Source)
GAMA Caught a workbench message : GamaRuntimeException java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7006f9e rejected from java.util.concurrent.ThreadPoolExecutor@e883115[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 71]
```

**Comment by AlexisDrogoul** [comment]
I have committed a possible fix for this erratic behavior (which, I'm afraid, is once again Windows-centric…). Please close the issue if it works.

**Comment by mazarsju** [comment]
works fine now for me ! I close the issue
