### ISSUE TITLE
problem with agent browser when inspecting agents when some agents are dead

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1610]
test the following model:
model testinpector

global {
	init {create dummy number: 5000;}
}

species dummy {
	rgb color <- rnd_color(255);
	aspect default {draw circle(3) color: color;}
	reflex to_die when:flip(0.01) {do die;}
}

experiment main type: gui {
	output {
		display view {species dummy;}
	}
}

Run several steps (10 for instance), then inspect (right button, Species layer: dummy, browse agents).
I get this error:

java.lang.IndexOutOfBoundsException: Index: 4520, Size: 4361
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at msi.gama.util.GamaList.get(GamaList.java:250)
	at msi.gama.util.GamaList.getFromIndicesList(GamaList.java:322)
	at msi.gama.metamodel.population.GamaPopulation.getFromIndicesList(GamaPopulation.java:792)
	at msi.gama.metamodel.population.GamaPopulation.getFromIndicesList(GamaPopulation.java:1)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:507)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:1)
	at gaml.additions.GamlAdditions$797.run(GamlAdditions.java:839)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:78)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:76)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:1)
	at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:474)
	at msi.gama.outputs.InspectDisplayOutput.step(InspectDisplayOutput.java:214)

**Comment by AlexisDrogoul** [comment]
A good illustration on the difference between my_species(i) and my_species[i]. While the former will return the agent of my_species whose index is i, the second will return the ith agent of my_species. If no agent dies, the two are the same, but as soon as agent0 is killed, agent1 keeps the same index but becomes the 0th agent… 

I have made the mistake myself in the serialization of agents, so I guess we need to put it somewhere in the documentation (or in a model example).
