### ISSUE TITLE
Impossible to run the headless : ClassCastException (Windows)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1669]
I cannot launch the headless from my computer. 

Here is the xml / gaml I'm using : 
[models.zip](https://github.com/gama-platform/gama/files/209536/models.zip)

And here is the command line I use : 
```
-os ${target.os} -ws ${target.ws} -arch ${target.arch} -nl ${target.nl} -consoleLog -data /tmp/titi    /tmp/models/predatorPrey.xml  /tmp/ff
```

Here is the error stack : 

```
Exception in thread "Thread-4" java.lang.RuntimeException: java.lang.ClassCastException: org.eclipse.emf.ecore.xmi.impl.XMIResourceImpl cannot be cast to msi.gama.lang.gaml.resource.GamlResource
	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:79)
	at msi.gama.headless.runtime.LocalSimulationRuntime.loadModel(LocalSimulationRuntime.java:182)
	at msi.gama.headless.job.ExperimentJob.load(ExperimentJob.java:202)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:183)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:209)
Caused by: java.lang.ClassCastException: org.eclipse.emf.ecore.xmi.impl.XMIResourceImpl cannot be cast to msi.gama.lang.gaml.resource.GamlResource
	at msi.gama.lang.gaml.resource.GamlModelBuilder.compile(GamlModelBuilder.java:108)
	at msi.gaml.factories.ModelFactory.compile(ModelFactory.java:124)
	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:68)
	... 4 more
```

**Comment by AlexisDrogoul** [comment]
What happens before the exception is raised ? Any activity log ? Seems that GAML has not been correctly loaded in that case, as the resource should be interpreted as a GamlResource and not as a generic XMIResource.

**Comment by mazarsju** [comment]
The logs in the console you mean ? Here are the logs just before the exception is risen : 
```
Debug: >> GAMA bundle loaded in 2745ms: 	msi.gama.core
Debug: >> GAMA bundle loaded in 176ms: 	simtools.gaml.extensions.traffic
Debug: >> GAMA bundle loaded in 10ms: 	msi.gama.headless
Debug: >> GAMA bundle loaded in 89ms: 	irit.gaml.extensions.database
Debug: >> GAMA bundle loaded in 54ms: 	ummisco.gaml.extensions.maths
Debug: >> GAMA bundle loaded in 16ms: 	idees.gama.mapcomparison
Debug: >> GAMA total load time 3367 ms.
>> Registering GAML expression compiler.
cpus :4
```

**Comment by AlexisDrogoul** [comment]
There is a Logger defined in HeadlessSimulationLoader, that should provide a little bit more precise information. Can you enable it (dont know how to do, probably with a parameter to the command line instruction, or by putting somewhere a file enabling the logger) ?

**Comment by hqnghi88** [comment]
HI Julien,
do you have any update on this issue?

**Comment by hqnghi88** [comment]
Hi,
Could you please test on other OS and reopen if it still not work, it seem to be fixed on my windows

**Comment by mazarsju** [comment]
Well done ! It seems you solved it ;).
