### ISSUE TITLE
NullPointerException when running model with overlay in headless mode (and trying to get an output)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1675]
When trying to run a model with an overlay (ex : the model "Overlay" of the model library) with headless, a NullPointerException is risen.
Here is the error stack :

```
.Overlay position: java.awt.Point[x=25,y=25] size: java.awt.Point[x=180,y=100]
java.lang.NullPointerException
	at msi.gama.outputs.display.AWTDisplayGraphics.beginOverlay(AWTDisplayGraphics.java:288)
	at msi.gama.outputs.layers.OverlayLayer.drawDisplay(OverlayLayer.java:53)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:151)
	at msi.gama.outputs.ImageDisplaySurface.drawAllDisplays(ImageDisplaySurface.java:166)
	at msi.gama.outputs.ImageDisplaySurface.paint(ImageDisplaySurface.java:179)
	at msi.gama.outputs.ImageDisplaySurface.getImage(ImageDisplaySurface.java:196)
	at msi.gama.outputs.LayeredDisplayOutput.getImage(LayeredDisplayOutput.java:608)
	at msi.gama.headless.core.RichExperiment.getRichOutput(RichExperiment.java:50)
	at msi.gama.headless.job.ExperimentJob.exportVariables(ExperimentJob.java:255)
	at msi.gama.headless.job.ExperimentJob.doStep(ExperimentJob.java:238)
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:225)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:217)
..........Exception in thread "Thread-4" java.lang.NullPointerException
	at msi.gama.outputs.display.AWTDisplayGraphics.setOpacity(AWTDisplayGraphics.java:88)
	at msi.gama.outputs.display.AWTDisplayGraphics.fillBackground(AWTDisplayGraphics.java:232)
	at msi.gama.outputs.ImageDisplaySurface.drawAllDisplays(ImageDisplaySurface.java:165)
	at msi.gama.outputs.ImageDisplaySurface.paint(ImageDisplaySurface.java:179)
	at msi.gama.outputs.ImageDisplaySurface.getImage(ImageDisplaySurface.java:196)
	at msi.gama.outputs.LayeredDisplayOutput.getImage(LayeredDisplayOutput.java:608)
	at msi.gama.headless.core.RichExperiment.getRichOutput(RichExperiment.java:50)
	at msi.gama.headless.job.ExperimentJob.exportVariables(ExperimentJob.java:255)
	at msi.gama.headless.job.ExperimentJob.doStep(ExperimentJob.java:238)
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:225)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:217)
```

**Comment by mazarsju** [comment]
Here is an example of xml to run to reproduce the error :

```
<?xml version="1.0" encoding="UTF-8"?>
<Experiment_plan>
  <Simulation id="0" sourcePath="/F:\Gama\GamaSource\msi.gama.models\models\Features\Overlay\Overlay.gaml" finalStep="11" experiment="overlay">
    <Outputs>
      <Output id="831" name="map" framerate="10" />
    </Outputs>
  </Simulation>
</Experiment_plan>
```
