### ISSUE TITLE
RuntimeException when changing display

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1687]
This error is not reproductible, but it happens quite often for me. When this error occurs, I have to reload all GAMA. 

Here is the stack error : 

```
Exception in thread "Animator thread" java.lang.RuntimeException: Waited 5000ms for: <ca2d8e5, 174da8de>[count 1, qsz 0, owner <main>] - <Animator thread>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:168)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at ummisco.gama.opengl.SWTGLAnimator.displayGL(SWTGLAnimator.java:184)
	at ummisco.gama.opengl.SWTGLAnimator.run(SWTGLAnimator.java:165)
	at java.lang.Thread.run(Unknown Source)
```

Ex of model with which this error happened for the last time for me : 

```
model new

global {}

grid cells width:2 height:2 {
	rgb color <- rgb(255,200,255,255);
	aspect base {
		draw square(10) color:rgb(255,200,255,255);
	}
}
grid cellsAlpha width:2 height:2 {
	rgb color <- rgb(255,200,255,100);
	aspect base {
		draw square(10) color:rgb(255,200,255,50);
	}
}

grid cells2 width:63 height:63 {
	rgb color <- rgb(grid_x*4,grid_y*4,255,grid_x*2+grid_y*2);
//	rgb color <- rgb(255,255,255,grid_y+grid_x);
	aspect base {
		draw square(100.0/63.0) color:rgb(grid_x*4,grid_y*4,255,grid_x*2+grid_y*2);
	}
}

experiment my_experiment type:gui{
	output {
		display "openGL display (grid)" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
			grid cells;
		}
		display "openGL display (grid+alpha)" type:opengl background:#white /*diffuse_light:100*/ ambient_light:100 {
			grid cellsAlpha;
		}
		display "openGL display" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
			graphics "coucou" {
				draw square(10) color:rgb(0,0,0,10);
			}
		}
		display "openGL display2" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
			species cells aspect:base;
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
Can you try to reproduce it (although it seems difficult) with the patch I've just committed. It basically forces the OpenGL displays to "realize" themselves by bringing them to front (it is for example necessary on MacOS X for opening different displays) -- so that this 5000ms wait should not be present anymore.

**Comment by mazarsju** [comment]
No, it still occurs...

**Comment by AlexisDrogoul** [comment]
Is it this issue that have been resolved using the preferences to disable the shared OpenGL context ?

**Comment by AlexisDrogoul** [comment]
I have modified the comment in the preferences to acknowledge the fact that it may cause problems on Linux and Windows.

**Comment by mazarsju** [comment]
Yes, it works well now with the preferences (appart from all the other bugs I'm facing with my graphical card). So I close this issue.
