### ISSUE TITLE
Detaching an opengl display raises an exception

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1700]
- Using the follwing model of Julien 
- Launch experiment
- Restore GAMA windows (the size is windowed, not maximized)
- Drag an display, detach it (drag it outside the GAMA windows).
- Maximize the detached display.
==> Exception at below.

model new

global {}

grid cells width:2 height:2 {
    rgb color <- rgb(255,200,255,255);
    aspect base {
        draw square(10) color:rgb(255,200,255,255);
    }
}
grid cellsAlpha width:2 height:2 {
    rgb color <- rgb(255,200,255,100);
    aspect base {
        draw square(10) color:rgb(255,200,255,50);
    }
}

grid cells2 width:63 height:63 {
    rgb color <- rgb(grid_x*4,grid_y*4,255,grid_x*2+grid_y*2);
//  rgb color <- rgb(255,255,255,grid_y+grid_x);
    aspect base {
        draw square(100.0/63.0) color:rgb(grid_x*4,grid_y*4,255,grid_x*2+grid_y*2);
    }
}

experiment my_experiment type:gui{
    output {
        display "openGL display (grid)" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
            grid cells;
        }
        display "openGL display (grid+alpha)" type:opengl background:#white /*diffuse_light:100*/ ambient_light:100 {
            grid cellsAlpha;
        }
        display "openGL display" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
            graphics "coucou" {
                draw square(10) color:rgb(0,0,0,10);
            }
        }
        display "openGL display2" type:opengl background:#white /*diffuse_light:100*/ ambient_light:40 {
            species cells aspect:base;
        }
    }
}

GAMA Caught a workbench message : Unhandled event loop exception com.jogamp.opengl.GLException: Caught RuntimeException: java.lang.NullPointerException on thread main
com.jogamp.opengl.GLException: Caught RuntimeException: java.lang.NullPointerException on thread main
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at jogamp.opengl.GLDrawableHelper.invoke(GLDrawableHelper.java:912)
	at com.jogamp.opengl.swt.GLCanvas.invoke(GLCanvas.java:789)
	at ummisco.gama.opengl.camera.AbstractCamera.mouseMove(AbstractCamera.java:215)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:67)
	at jogamp.opengl.GLDrawableHelper.execGLRunnables(GLDrawableHelper.java:770)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:676)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 35 more
Caused by: java.lang.NullPointerException
	at ummisco.gama.opengl.camera.CameraArcBall.internalMouseMove(CameraArcBall.java:446)
	at ummisco.gama.opengl.camera.AbstractCamera$2.run(AbstractCamera.java:220)
	at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:61)
	... 39 more

**Comment by AlexisDrogoul** [comment]
Seems to be windows only. I cant reproduce this on Mac. The problem comes CameraArcBall.internalMouseMove(), which maybe receives a null event. Can you try by testing the nulliness of the event in this method  (returning if it is) ?

**Comment by hqnghi88** [comment]
I chose the solution that initialize lastMousePressedPosition instead of "returning if it is null".
