### ISSUE TITLE
Xtext editor error after git update a63ca1: Allows to define the 'light' and 'camera' layer...

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1730]
Here are the erro stack trace
!ENTRY msi.gama.headless 4 0 2016-05-10 21:25:46.810
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: msi.gama.headless [201]
  Unresolved requirement: Require-Bundle: msi.gama.lang.gaml
    -> Bundle-SymbolicName: msi.gama.lang.gaml; bundle-version="1.7.0.qualifier"; singleton:="true"
       msi.gama.lang.gaml [205]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.generator; bundle-version="2.9.1"; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe2.launch; bundle-version="2.8.3"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY msi.gama.lang.gaml.ui 4 0 2016-05-10 21:25:46.816
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: msi.gama.lang.gaml.ui [203]
  Unresolved requirement: Require-Bundle: msi.gama.lang.gaml; visibility:="reexport"
    -> Bundle-SymbolicName: msi.gama.lang.gaml; bundle-version="1.7.0.qualifier"; singleton:="true"
       msi.gama.lang.gaml [205]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.generator; bundle-version="2.9.1"; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe2.launch; bundle-version="2.8.3"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY msi.gama.lang.gaml 4 0 2016-05-10 21:25:46.819
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: msi.gama.lang.gaml [205]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.generator; bundle-version="2.9.1"; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe2.launch; bundle-version="2.8.3"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by AlexisDrogoul** [comment]
Oops. Sorry. The fix is on his way.
