### ISSUE TITLE
ConcurrentModificationException in multi-simulation

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1736]
Using the following code:
model M1
global
{
	init{}
	reflex stopsim when: cycle>100{do halt;}
}

experiment multisim type:gui{
	init{
		create simulation number:100;
	}
}

will produce this exception:

!ENTRY org.eclipse.ui 4 4 2016-05-16 12:34:17.207
!MESSAGE GamaRuntimeException java.util.ConcurrentModificationException
!STACK 0
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:235)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:191)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentAgent.stepSubPopulations(ExperimentAgent.java:230)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:219)
	at msi.gama.metamodel.agent.MinimalAgent.step(MinimalAgent.java:188)
	at msi.gama.kernel.experiment.ExperimentAgent.step(ExperimentAgent.java:493)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
	at java.lang.Thread.run(Thread.java:745)
GAMA Caught a workbench message : GamaRuntimeException java.util.ConcurrentModificationException java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:235)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:191)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentAgent.stepSubPopulations(ExperimentAgent.java:230)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:219)
	at msi.gama.metamodel.agent.MinimalAgent.step(MinimalAgent.java:188)
	at msi.gama.kernel.experiment.ExperimentAgent.step(ExperimentAgent.java:493)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
	at java.lang.Thread.run(Thread.java:745)
java.util.ConcurrentModificationException
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:58)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:598)
	at msi.gama.kernel.experiment.ExperimentAgent.stepSubPopulations(ExperimentAgent.java:230)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:219)
	at msi.gama.metamodel.agent.MinimalAgent.step(MinimalAgent.java:188)
	at msi.gama.kernel.experiment.ExperimentAgent.step(ExperimentAgent.java:493)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:235)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:191)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	... 8 more

**Comment by AlexisDrogoul** [comment]
Fixed by commit https://github.com/gama-platform/gama/commit/1d625105508bfd751c91b4e44c0751895eaf6256
