### ISSUE TITLE
Error with an experiment in batch mode 

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1739]
Hello,
I have an error with an experiment in batch mode. 
It does not work without the stop condition in experiment statement (see the experiment 'test_do_halt_batch' below) .But I have called a "do halt" to stop the simulation  in the global section)
However, It works well with experiment 'batch_until' where I have set the stopping condition with  "until:" facet (without "do halt;" )

Thank you!

Quang
__________________________________________________________
global{
	init {
	}
	reflex write{
		if cycle =9 {
			write cycle;
			do halt;	
		}
	}
}
/* Insert your model definition here */
experiment 'test_do_halt_batch' type: batch repeat: 10 keep_seed: true  {
}

/* Insert your model definition here */
experiment 'batch_until' type: batch repeat: 10 keep_seed: true until: time =10 {
}

![batch_error](https://cloud.githubusercontent.com/assets/11825516/15284551/245a456c-1b7c-11e6-81bd-709b5a2ef7b3.png)

ENTRY org.eclipse.ui 4 4 2016-05-16 15:34:46.658
!MESSAGE GamaRuntimeException java.util.ConcurrentModificationException
!STACK 0
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)

	at java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:191)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:184)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:64)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:55)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:150)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
	at java.lang.Thread.run(Unknown Source)
GAMA Caught a workbench message : GamaRuntimeException java.util.ConcurrentModificationException java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:191)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:184)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:64)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:55)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:150)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
	at msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
	at java.lang.Thread.run(Unknown Source)

**Comment by tcquang** [comment]
Dear M. Drogoul,
Just for remaining the issue that you have fixed, because it could relate with the issue #1836.
In this issue, I had a problem with "do halt" statement. But after that, I have some problems with my model, thus I have not tested the batch mode with my real model until now.
