### ISSUE TITLE
Simulation's memory

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1763]
Hello,
The memory are not released after a simulation. 
- When I run my model, the first time it showed: 770MB of 1050MB in the task bar
- The 2nd time, it took 1104MB of 1615.
-  It took  1408 of 2026MB for the 3rd time
- It took 1859-2027MB for the 4th
- On the 5th time, it showed 1908 of 2008MB, but the initialization could not finish .

Cheer,
![simulation_momory](https://cloud.githubusercontent.com/assets/11825516/15316467/4dd147f8-1c47-11e6-9947-fe3e18a92043.png)

Quang

**Comment by tcquang** [comment]
When I break the simulation, it shows this message on Eclipse. After that, When I clicked on the recycle bin button, the it showed 1432M of 2006.

Quang

Thread [Worker-3] | Resource set [1 resources]
'lu_suitability.gaml' validated in 13.509322 ms [ ~928 kb used ]
****************************************************
simulation agent set seed: 0.5668964957523631
Agent constructor for Description of land_unit based on :class msi.gama.metamodel.agent.GamlAgent
Exception in thread "Thread-38" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at msi.gama.common.util.GeometryUtils$GamaCoordinateSequence.<init>(GeometryUtils.java:92)
	at msi.gama.common.util.GeometryUtils$GamaCoordinateSequence.clone(GeometryUtils.java:125)
	at msi.gama.common.util.GeometryUtils$GamaCoordinateSequence.clone(GeometryUtils.java:1)
	at com.vividsolutions.jts.geom.LinearRing.reverse(LinearRing.java:150)
	at com.vividsolutions.jts.geom.Polygon.reverse(Polygon.java:445)
	at com.vividsolutions.jts.geom.MultiPolygon.reverse(MultiPolygon.java:149)
	at msi.gama.common.util.GeometryUtils.changeClockWise(GeometryUtils.java:1039)
	at msi.gama.metamodel.shape.GamaShape.setInnerGeometry(GamaShape.java:498)
	at msi.gama.metamodel.shape.GamaShape.<init>(GamaShape.java:63)
	at msi.gama.metamodel.shape.GamaGisGeometry.<init>(GamaGisGeometry.java:31)
	at msi.gama.util.file.GamaShapeFile.readShapes(GamaShapeFile.java:311)
	at msi.gama.util.file.GamaShapeFile.fillBuffer(GamaShapeFile.java:242)
	at msi.gama.util.file.GamaFile.getContents(GamaFile.java:256)
	at msi.gama.util.file.GamaFile.length(GamaFile.java:294)
	at msi.gaml.statements.CreateFromGeometriesDelegate.createFrom(CreateFromGeometriesDelegate.java:57)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:319)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:84)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:208)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:187)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:395)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:150)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:136)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:218)
Trying to open perspective msi.gama.application.perspectives.ModelingPerspective 
+++ Part Model LU_coastal_MK_suitability / Experiment LU_coastal_MK is being disposed
+++ Part Console is being disposed
auto-save activated: true
Perspective msi.gama.application.perspectives.ModelingPerspective opened

**Comment by AlexisDrogoul** [comment]
Two questions:

- Is it something new ?
- Do you reload, relaunch (from the Editor) or close and relaunch them ?

**Comment by tcquang** [comment]
Hello,
The 2nd comment is what I saw in the eclipse console.
For the simulation times, each time, I launched the simulation from the Editor. Then, I stopped it by clicking on the "X" in the simulation's toolbar. After that, I relaunched it again from the Editor.

Quang

**Comment by AlexisDrogoul** [comment]
Can you try again with some modifications I have made ? Not sure I really addressed the problem, but who knows... And I will probably need your model to understand where the memory leak happens (you seem to manipulate some data)

**Comment by tcquang** [comment]
Hello,
​
 Land_use_markov_CA.rar
<https://drive.google.com/a/ctu.edu.vn/file/d/0B_dE-90zu3GYQ3RYeDZMUjN2aXM/view?usp=drive_web>
Here is my model in the attachement file.
The model folder is over 25MB, thus, I have uploaded it on the Google Drive.

Thank you!

Quang

2016-05-18 11:20 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Can you try again with some modifications I have made ? Not sure I really
> addressed the problem, but who knows... And I will probably need your model
> to understand where the memory leak happens (you seem to manipulate some
> data)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gama-platform/gama/issues/1763#issuecomment-219921494>
>



-- 
Quang Chi TRUONG
Tel: 0939388153
