### ISSUE TITLE
Many "NoSuchElementException" while calling "buildExperiment" for experiments without display (Headless)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1820]
I got many "NoSuchElementException" when I try to compile models using headless module.

Example of models with this problem : 
- Data Importation / CSV File Loading
- Co-model Usage / Syntax / comodel_simple
- Date and Time / Date type and real dates
- ...

```
java.util.NoSuchElementException
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
	at com.google.common.collect.Iterators.find(Iterators.java:712)
	at com.google.common.collect.Iterables.find(Iterables.java:643)
	at msi.gaml.descriptions.SymbolDescription.getChildWithKeyword(SymbolDescription.java:714)
	at msi.gama.headless.job.ExperimentJob.loadAndBuildJob(ExperimentJob.java:401)
	at msi.gama.headless.job.JobPlan.loadAndBuildJobs(JobPlan.java:156)
	at msi.gama.headless.job.JobPlan.loadModelAndCompileJob(JobPlan.java:76)
	at msi.gama.headless.script.ExperimentationPlanFactory.buildExperiment(ExperimentationPlanFactory.java:140)
	at msi.gama.headless.runtime.Application.buildXMLForModelLibrary(Application.java:273)
	at msi.ummisco.modelLibraryGenerator.modelLibraryGenerator.start(modelLibraryGenerator.java:108)
	at msi.gama.headless.runtime.Application.start(Application.java:209)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

@gnoubi any idea ?
To reproduce this error, change the flag "buildModelLibrary" in Application to true, and change the 2 paths "wikiFolder" and "sourceFolder" in "modelLibraryGenerator".

**Comment by mazarsju** [comment]
Sry my mistake...

**Comment by mazarsju** [comment]
It seems it is a problem when we call the "buildExperiment" method (static method of ExperimentationPlanFactory) with an experiment without any display.
