### ISSUE TITLE
The relative path is not work well if the import model is not in the same project

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1826]
For example, I have 2 projects: P0 and TestRelativePath.
In the P0, i have model m1 working with the image.
In the TestRelativePath, i have model m2, import m1.
When i click on the experiment exp1 of m1, i got this message

!ENTRY org.eclipse.ui 4 4 2016-05-24 23:04:09.917
!MESSAGE GamaRuntimeException File denoted by D:\OneDrive\Gama1.7\TestRelativePath\models2\..\images\images\soil.jpg not found! Tried the following paths : 
!STACK 0
File denoted by D:\OneDrive\Gama1.7\TestRelativePath\models2\..\images\images\soil.jpg not found! Tried the following paths : 
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:142)
	at msi.gama.common.util.ImageUtils.getImageFromFile(ImageUtils.java:82)
	at msi.gama.outputs.layers.ImageLayerStatement._init(ImageLayerStatement.java:147)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.SimulationOutputManager.init(SimulationOutputManager.java:56)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:204)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:173)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:396)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:164)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:134)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:228)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:187)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:173)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:196)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:258)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)
GAMA Caught a workbench message : GamaRuntimeException File denoted by D:\OneDrive\Gama1.7\TestRelativePath\models2\..\images\images\soil.jpg not found! Tried the following paths :  File denoted by D:\OneDrive\Gama1.7\TestRelativePath\models2\..\images\images\soil.jpg not found! Tried the following paths : 
File denoted by D:\OneDrive\Gama1.7\TestRelativePath\models2\..\images\images\soil.jpg not found! Tried the following paths : 
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:142)
	at msi.gama.common.util.ImageUtils.getImageFromFile(ImageUtils.java:82)
	at msi.gama.outputs.layers.ImageLayerStatement._init(ImageLayerStatement.java:147)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.SimulationOutputManager.init(SimulationOutputManager.java:56)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:204)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:173)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:396)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:164)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:134)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:228)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:187)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:173)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:196)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:258)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)

[testcase.zip](https://github.com/gama-platform/gama/files/279917/testcase.zip)

**Comment by AlexisDrogoul** [comment]
That's usually what projects are made for. They keep resources and make them available to the models.
But are you talking about projects or folders ?  Because your error seems a bit different: is the path `D:\OneDrive\Gama1.7\TestRelativePath\models2..\images\images\soil.jpg` correct on Windows ? Especially the part `\models2..\images\` ? Shouldn't it be `\models2\..\images\` instead ??

**Comment by hqnghi88** [comment]
Dear Alexis,
I talk about projects level. I try to put the error in txt file, it was the right path with \..\ 
You find the screenshot. The model m1 in project P0 is working, no error of paths. When it is imported in m2 of "project" TestRelativePath, it add the button exp1. The error occur if user click on button exp1.



[error.txt](https://github.com/gama-platform/gama/files/280122/error.txt)
![untitled](https://cloud.githubusercontent.com/assets/6105384/15514504/90fe6c14-2213-11e6-986a-90b044501c4d.png)

**Comment by hqnghi88** [comment]
I take the occassion to test , it seem a slash have dissapear in the comment:   \..\

![testslash](https://cloud.githubusercontent.com/assets/6105384/15514624/2ae7b434-2214-11e6-9b42-4ebe544c23f6.png)

**Comment by AlexisDrogoul** [comment]
The more I think about this issue, the more I wonder if we need to fix it. I will issue a fix, probably, but there are circumstances where we dont want the imported model to load its own resources -- instead, we want it to load the resources it may find in the scope of the model that imports it. So the fix will probably be to maintain a list of relevant directories for models, so that it searches first in the importing model project, and then after in the imported model(s) project(s).

**Comment by hqnghi88** [comment]
Dear Alexis,
In fact, the issue come from the lauching of out-of-project experiment. If we consider that imported model load the resources in the scope of the model that imports it, I think we could etablish the rule that : Imported experiment dont show if it is out-of-project. In that case, modelers need to specify the parent of experiment if they want to reuse the experiment.
And yes, if we have the list of relevant directories, it would be nice for all the complexity proposed.

**Comment by hqnghi88** [comment]
Sorry, I have tried, but the inheritance of experiment out-of-project still cant find the right path. So as your proposal is the only solution.
Cheers.
