### ISSUE TITLE
Batch 's permanent chart: "simulations" raises null exception.

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1846]
In the Feature/Batch/Batch.gaml, launch the "Exhaustive optimization" experiment. I got this message:
Error: nil value detected when applying the collect operator on nil and each.nb_infected

!ENTRY org.eclipse.ui 4 4 2016-05-27 09:21:49.982
!MESSAGE GamaRuntimeException Error: nil value detected
!STACK 0
Error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:74)
	at msi.gama.util.GAML.nullCheck(GAML.java:44)
	at msi.gama.util.GAML.nullCheck(GAML.java:39)
	at msi.gaml.operators.Containers.collect(Containers.java:928)
	at gaml.additions.GamlAdditions$390.run(GamlAdditions.java:429)
	at gaml.additions.GamlAdditions$390.run(GamlAdditions.java:1)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:83)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:63)
	at msi.gama.outputs.layers.charts.ChartDataSourceUnique.inferDatasetProperties(ChartDataSourceUnique.java:102)
	at msi.gama.outputs.layers.charts.ChartDataSourceUnique.createInitialSeries(ChartDataSourceUnique.java:122)
	at msi.gama.outputs.layers.charts.ChartDataStatement.createDataSource(ChartDataStatement.java:160)
	at msi.gama.outputs.layers.charts.ChartDataStatement.privateExecuteIn(ChartDataStatement.java:208)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._init(ChartLayerStatement.java:506)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.ExperimentOutputManager.init(ExperimentOutputManager.java:74)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:199)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:257)
	at msi.gama.kernel.experiment.BatchAgent.schedule(BatchAgent.java:87)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)
GAMA Caught a workbench message : GamaRuntimeException Error: nil value detected Error: nil value detected
Error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:74)
	at msi.gama.util.GAML.nullCheck(GAML.java:44)
	at msi.gama.util.GAML.nullCheck(GAML.java:39)
	at msi.gaml.operators.Containers.collect(Containers.java:928)
	at gaml.additions.GamlAdditions$390.run(GamlAdditions.java:429)
	at gaml.additions.GamlAdditions$390.run(GamlAdditions.java:1)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:83)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:63)
	at msi.gama.outputs.layers.charts.ChartDataSourceUnique.inferDatasetProperties(ChartDataSourceUnique.java:102)
	at msi.gama.outputs.layers.charts.ChartDataSourceUnique.createInitialSeries(ChartDataSourceUnique.java:122)
	at msi.gama.outputs.layers.charts.ChartDataStatement.createDataSource(ChartDataStatement.java:160)
	at msi.gama.outputs.layers.charts.ChartDataStatement.privateExecuteIn(ChartDataStatement.java:208)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._init(ChartLayerStatement.java:506)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.ExperimentOutputManager.init(ExperimentOutputManager.java:74)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:199)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:257)
	at msi.gama.kernel.experiment.BatchAgent.schedule(BatchAgent.java:87)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.ui 4 4 2016-05-27 09:21:50.089
!MESSAGE GamaRuntimeException java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
	at msi.gama.runtime.exceptions.GamaRuntimeException.addContext(GamaRuntimeException.java:158)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:44)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._init(ChartLayerStatement.java:506)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.ExperimentOutputManager.init(ExperimentOutputManager.java:74)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:199)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:257)
	at msi.gama.kernel.experiment.BatchAgent.schedule(BatchAgent.java:87)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)
GAMA Caught a workbench message : GamaRuntimeException java.lang.NullPointerException java.lang.NullPointerException
java.lang.NullPointerException
	at msi.gama.runtime.exceptions.GamaRuntimeException.addContext(GamaRuntimeException.java:158)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:44)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._init(ChartLayerStatement.java:506)
	at msi.gama.outputs.layers.AbstractLayerStatement.init(AbstractLayerStatement.java:78)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:264)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.outputs.AbstractOutputManager.init(AbstractOutputManager.java:157)
	at msi.gama.outputs.ExperimentOutputManager.init(ExperimentOutputManager.java:74)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:199)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:257)
	at msi.gama.kernel.experiment.BatchAgent.schedule(BatchAgent.java:87)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)

Gama Git version.

**Comment by AlexisDrogoul** [comment]
Yep. Probably because `simulations` is initialized after or during the initialization of the outputs.

**Comment by tcquang** [comment]
I have an error NullPointerException that I think it could relate with this issue?.
I have a calculation for FuzzyKappa at the step 6 of the simulations but it is not working in batch mode.

Thank you!


1 occurence in Simulation 0 at cycle 6: java.lang.NullPointerException
in kappa <- fuzzy_kappa(parcels,parcels collect each.landuse_obs,parcels collect each.landuse,similarity_per_agents,LUT.keys,fuzzy_categories,distance_kappa);
java.lang.NullPointerException
msi.gama.metamodel.topology.GamaQuadTree.allAtDistance(GamaQuadTree.java:109)
msi.gama.metamodel.topology.CompoundSpatialIndex.allAtDistance(CompoundSpatialIndex.java:173)
msi.gama.metamodel.topology.AbstractTopology.getNeighborsOf(AbstractTopology.java:462)
msi.gaml.operators.MapComparison.buildRings(MapComparison.java:673)
msi.gaml.operators.MapComparison.fuzzyKappa(MapComparison.java:238)
msi.gaml.operators.MapComparison.fuzzyKappa(MapComparison.java:199)
gaml.additions.GamlAdditions$488.run(GamlAdditions.java:527)
gaml.additions.GamlAdditions$488.run(GamlAdditions.java:1)
msi.gaml.expressions.NAryOperator.value(NAryOperator.java:76)
msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:115)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:49)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:187)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:74)
msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:65)
msi.gama.runtime.AbstractScope.execute(AbstractScope.java:515)
msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:220)
msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:184)
msi.gama.metamodel.agent.MinimalAgent.step(MinimalAgent.java:191)
msi.gama.kernel.simulation.SimulationPopulation$1.call(SimulationPopulation.java:148)
java.util.concurrent.FutureTask.run(Unknown Source)
com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
msi.gama.kernel.simulation.SimulationPopulation.step(SimulationPopulation.java:197)
msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:190)
msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:64)
msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:55)
msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:101)
msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:156)
msi.gama.runtime.AbstractScope.step(AbstractScope.java:596)
msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:94)
msi.gama.kernel.experiment.ExperimentScheduler.run(ExperimentScheduler.java:132)
java.lang.Thread.run(Unknown Source)

in kappa <- fuzzy_kappa(parcels,parcels collect each.landuse_obs,parcels collect each.landuse,similarity_per_agents,LUT.keys,fuzzy_categories,distance_kappa);
in if true  {
	fuzzy_categories <- as_matrix(0.0,point(nb_LUT,nb_LUT));
	loop i from: 0 to: nb_LUT - 1  {
		fuzzy_categories[point(i,i)] <- 1.0;
	}

	fuzzy_transitions <- as_matrix(0.0,point(nb_LUT * nb_LUT,nb_LUT * nb_LUT));
	loop i from: 0 to: (nb_LUT * nb_LUT) - 1  {
		fuzzy_transitions[point(i,i)] <- 1.0;
	}

	list<float> similarity_per_agents <- [];
	kappa <- fuzzy_kappa(parcels,parcels collect each.landuse_obs,parcels collect each.landuse,similarity_per_agents,LUT.keys,fuzzy_categories,distance_kappa);
	loop i from: 0 to: length(parcels) - 1  {
		int val <- int(255 * similarity_per_agents[i]);
		ask parcels[i]  {
			color_fuzzy <- rgb(val,val,val);
		}
	
	}

}

in action call_fuzzy_kappa  {
	ask parcels  {
		if not(landuse in categories)  {
			categories <+ landuse;
		}
	
		if not(landuse_obs in categories)  {
			categories <+ landuse_obs;
		}
	
	}

	if true  {
		fuzzy_categories <- as_matrix(0.0,point(nb_LUT,nb_LUT));
		loop i from: 0 to: nb_LUT - 1  {
			fuzzy_categories[point(i,i)] <- 1.0;
		}
	
		fuzzy_transitions <- as_matrix(0.0,point(nb_LUT * nb_LUT,nb_LUT * nb_LUT));
		loop i from: 0 to: (nb_LUT * nb_LUT) - 1  {
			fuzzy_transitions[point(i,i)] <- 1.0;
		}
	
		list<float> similarity_per_agents <- [];
		kappa <- fuzzy_kappa(parcels,parcels collect each.landuse_obs,parcels collect each.landuse,similarity_per_agents,LUT.keys,fuzzy_categories,distance_kappa);
		loop i from: 0 to: length(parcels) - 1  {
			int val <- int(255 * similarity_per_agents[i]);
			ask parcels[i]  {
				color_fuzzy <- rgb(val,val,val);
			}
		
		}
	
	}

	loop c over: LUT.keys  {
		list<land_parcel> area_c <- parcels where (each.landuse_obs = c);
		list<float> area_shape_c <- area_c collect each.shape.area;
		nb_per_cat_obs <+ sum(area_shape_c);
		nb_per_cat_sim <+ sum((parcels where (each.landuse = c)) collect each.shape.area);
	}

	pad <- percent_absolute_deviation(nb_per_cat_obs,nb_per_cat_sim);
}

in do call_fuzzy_kappa ;
in if cycle = 6  {
	do call_fuzzy_kappa ;
}

in reflex stop  {
	if cycle = 6  {
		do call_fuzzy_kappa ;
	}

}

in agent Simulation 0
