### ISSUE TITLE
Redirecting (resolving) of relative path is not correct

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1849]
### Steps to reproduce
1. Use the projects in attached zip file testcase.zip
2. Open model m2
3. Click on any experiment button. It return this exception:
File denoted by ../images/images/soil.jpg not found! Tried the following paths : 
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:102)
	at msi.gama.util.file.GamaFile.<init>(GamaFile.java:52)
	at msi.gama.util.file.GamaImageFile.<init>(GamaImageFile.java:145)
	at gaml.additions.GamlAdditions$939.run(GamlAdditions.java:979)
	at gaml.additions.GamlAdditions$939.run(GamlAdditions.java:1)
	at msi.gaml.types.ParametricFileType.createFile(ParametricFileType.java:132)
	at msi.gaml.types.ParametricFileType.cast(ParametricFileType.java:71)
	at msi.gaml.types.ParametricFileType.cast(ParametricFileType.java:1)
	at msi.gaml.types.ParametricType.cast(ParametricType.java:391)
	at msi.gaml.types.ParametricType.cast(ParametricType.java:1)
	at msi.gaml.operators.Cast.as(Cast.java:192)
	at gaml.additions.GamlAdditions$680.run(GamlAdditions.java:719)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:83)
	at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:575)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:351)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:429)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:383)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:132)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:226)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:186)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:200)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:195)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:256)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)
GAMA Caught a workbench message : GamaRuntimeException File denoted by ../images/images/soil.jpg not found! Tried the following paths :  File denoted by ../images/images/soil.jpg not found! Tried the following paths : 
File denoted by ../images/images/soil.jpg not found! Tried the following paths : 
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:102)
	at msi.gama.util.file.GamaFile.<init>(GamaFile.java:52)
	at msi.gama.util.file.GamaImageFile.<init>(GamaImageFile.java:145)
	at gaml.additions.GamlAdditions$939.run(GamlAdditions.java:979)
	at gaml.additions.GamlAdditions$939.run(GamlAdditions.java:1)
	at msi.gaml.types.ParametricFileType.createFile(ParametricFileType.java:132)
	at msi.gaml.types.ParametricFileType.cast(ParametricFileType.java:71)
	at msi.gaml.types.ParametricFileType.cast(ParametricFileType.java:1)
	at msi.gaml.types.ParametricType.cast(ParametricType.java:391)
	at msi.gaml.types.ParametricType.cast(ParametricType.java:1)
	at msi.gaml.operators.Cast.as(Cast.java:192)
	at gaml.additions.GamlAdditions$680.run(GamlAdditions.java:719)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:83)
	at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:575)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:351)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:429)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:383)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:132)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:226)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:186)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:200)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:195)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:617)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:172)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:256)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:331)
	at msi.gama.kernel.experiment.ExperimentController$1.run(ExperimentController.java:101)
	at java.lang.Thread.run(Thread.java:745)

### Expected behavior
All experiment in model m2 must be runable without exception.
In the model m3 of testRelativePath, all things work well.
It seem that the computation of relative path still not good if a model m2 import a model m3 in subfolder which import a model m1 out-of-project.

### Actual behavior
See the attached snapshot 
### System and version 
GAMA git, JDK 8u77 64b, OS W10 64b

[testcase.zip](https://github.com/gama-platform/gama/files/287875/testcase.zip)
<img width="960" alt="shot" src="https://cloud.githubusercontent.com/assets/6105384/15629049/60f1d0ae-253a-11e6-8572-0c9779c2dce4.png">

**Comment by hqnghi88** [comment]
#1826

**Comment by AlexisDrogoul** [comment]
I have committed a possible fix for this, building during the compilation of models a list of possible alternate paths where GAMA should be looking for resources. I am however a bit concerned that it may interfere in the execution of complex models like MAELIA ( @benoitgaudou ) or headless operations, where it is not clear for me where the resources are actually searched ( @gnoubi , @ptaillandier ). 

Could the three above developers test these changes ASAP so that we can consider the fix to be permanent ?

**Comment by AlexisDrogoul** [comment]
Seems to work quite well for "normal" operations -- what about the headless ones ?

**Comment by hqnghi88** [comment]
I have test the example projects, and they work well in the headless mode.

**Comment by AlexisDrogoul** [comment]
OK. We can then close this issue, I guess, unless @benoitgaudou discovers it breaks MAELIA and its peculiar way of loading hundreds of files...

**Comment by hqnghi88** [comment]
I have tested with 700 imports, It slow down the validation at first time but after that it works well. I post the example in case of further test.
[TestImports.zip](https://github.com/gama-platform/gama/files/305241/TestImports.zip)
