### ISSUE TITLE
gama.application.product not found

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1853]
Hi, 

I am trying to update git version on my home computer, after update, when I launch gama, I get this error

!SESSION 2016-05-31 15:38:25.798 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product msi.gama.application.product --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.product -data /Users/Ram/Documents/workspace2016/../runtime-gama.product -dev file:/Users/Ram/Documents/workspace2016/.metadata/.plugins/org.eclipse.pde.core/gama.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY msi.gama.headless 4 0 2016-05-31 15:38:46.644
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: msi.gama.headless [10]
  Unresolved requirement: Require-Bundle: simtools.gaml.extensions.traffic; bundle-version="1.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.equinox.app 0 0 2016-05-31 15:38:50.076
!MESSAGE Product msi.gama.application.product could not be found.

!ENTRY org.eclipse.equinox.ds 2 0 2016-05-31 15:39:20.196
!MESSAGE [SCR - WorkThread] Timeout occurred! Thread was blocked on processing [QueuedJob] WorkPerformer: org.eclipse.equinox.internal.ds.SCRManager@6d2557da; actionType 1

!ENTRY org.eclipse.equinox.ds 2 0 2016-05-31 15:39:20.231
!MESSAGE [SCR] Enabling components of bundle org.eclipse.update.configurator did not complete in 30000 ms 

!ENTRY msi.gama.headless 2 0 2016-05-31 15:39:22.837
!MESSAGE Could not resolve module: msi.gama.headless [10]
  Unresolved requirement: Require-Bundle: simtools.gaml.extensions.traffic; bundle-version="1.0.0"

!ENTRY org.eclipse.osgi 4 0 2016-05-31 15:39:22.866
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:242)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

### Expected behavior
GAMA to be launched

### Actual behavior
GAMA is not launched

### System and version 
Git gama, Mac Mavericks, Java 1.7

**Comment by AlexisDrogoul** [comment]
How do you launch it ?

**Comment by sriramab** [comment]
By clicking on "Launch an eclipse application" in the overview tab of gama.product under msi.gama.application

**Comment by AlexisDrogoul** [comment]
Try first to synchronize your product with the defining plug-in (first tab). I dont understand why msi.gama.headless is dependent on a fixed version of traffic, and I've removed this dependency. Can you try again ?

**Comment by AlexisDrogoul** [comment]
And do not forget to import all the projects present in GitHub. If you miss some feature / plugin projects, it won't work.

**Comment by sriramab** [comment]
Hmm. I did, still error. Today I changed two things: Java to 1.8 in eclipse but when I run it reads java 1.7. I dont know why. Second, I changed max RAM to 4096m. These are the only two changes I made before update. Please also see attachment.

![error](https://cloud.githubusercontent.com/assets/12668606/15681040/23d8fec0-2758-11e6-8f74-0a1ce528ee67.jpg)

**Comment by sriramab** [comment]
The error is here

!SESSION 2016-05-31 17:44:44.347 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product msi.gama.application.product --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.product -data /Users/Ram/Documents/workspace2016/../runtime-gama.product -dev file:/Users/Ram/Documents/workspace2016/.metadata/.plugins/org.eclipse.pde.core/gama.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY org.eclipse.equinox.app 0 0 2016-05-31 17:44:49.989
!MESSAGE Product msi.gama.application.product could not be found.

!ENTRY msi.gama.headless 4 0 2016-05-31 17:44:50.379
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: msi.gama.headless [189]
  Unresolved requirement: Require-Bundle: simtools.gaml.extensions.traffic

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY msi.gama.headless 2 0 2016-05-31 17:44:54.684
!MESSAGE Could not resolve module: msi.gama.headless [189]
  Unresolved requirement: Require-Bundle: simtools.gaml.extensions.traffic


!ENTRY org.eclipse.osgi 4 0 2016-05-31 17:44:54.685
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:242)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by hqnghi88** [comment]
Hi Sriri,
You miss some feature plugin in the screenshot, see mine. You can:
-right click in project explorer, choose import.
- choose Git - Project from git.
- Existing  local repository
-Next, Next, Next and Finish.
Then , check if you have the missing. If yes, do a Clean-Build from Project
menu. and i think it should work.

**Comment by sriramab** [comment]
Yes, I did. I have some error in msi.gama.parent project and now the errors increased.
[1464710322546.txt](https://github.com/gama-platform/gama/files/291569/1464710322546.txt)

**Comment by sriramab** [comment]
In msi.gama.parent there is error or red mark on pom.xml, rest all projects are non-red.
The product configuration should be based on plugin or on features?

**Comment by sriramab** [comment]
I still do not understand why it reads java 1.7 while default is set to 1.8 as you can see in the screenshot.

**Comment by hqnghi88** [comment]
Hi,
In summarize, the problem of missing plugins have solved, and I change one more thing and it works for Srirama: clarify the JDK version in eclipse preference to 1.8 by removing these others.
The increase of memory does not take into account here.
But i am still wonder why 1.7 cannot work.

**Comment by AlexisDrogoul** [comment]
By default, the Eclipse preferences will show an error if the target is 1.7 and your JDK is 1.8. Changing the general JDK is then ok (as I have removed from all the projects, I guess, "specific settings" about this), but it is also possible to change the error into a warning. I have added a paragraph in the documentation for this problem (https://github.com/gama-platform/gama/wiki/InstallingGitVersion#if-you-have-errors)
