### ISSUE TITLE
Index out of bound error is not properly displayed

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#196]
**Describe the bug**
When an index out of bound happens in a simulation, it is not always properly displayed. In my case the simulation pauses and the editor opens at the faulty line, but nothing is displayed, the error view doesn't open.

**To Reproduce**
1. Run this model:
```
model silenterror

experiment a {
	init {
		write "hello";
		list l;
		write "content: " + l[0];
	}
	
}
```
3. see that it pauses but no error is displayed

Here is the eclipse stack:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at gama.core.util.IList.get(IList.java:369)
	at gama.core.util.GamaList.getFromIndicesList(GamaList.java:116)
	at gama.gaml.operators.Containers.internal_at(Containers.java:553)
	at gaml.additions.core.GamlAdditions.lambda$488(GamlAdditions.java:538)
	at gama.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:150)
	at gama.gaml.expressions.AbstractExpression.value(AbstractExpression.java:87)
	at gama.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:149)
	at gama.gaml.expressions.AbstractExpression.value(AbstractExpression.java:87)
	at gama.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:102)
	at gama.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.runtime.IScope.execute(IScope.java:414)
	at gama.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at gama.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at gama.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at gama.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.runtime.IScope.execute(IScope.java:414)
	at gama.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:137)
	at gama.core.metamodel.agent.AbstractAgent.init(AbstractAgent.java:229)
	at gama.core.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:276)
	at gama.core.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:372)
	at gama.core.metamodel.agent.MinimalAgent.init(MinimalAgent.java:241)
	at gama.core.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:452)
	at gama.core.runtime.ExecutionScope.init(ExecutionScope.java:602)
	at gama.core.kernel.experiment.DefaultExperimentController.schedule(DefaultExperimentController.java:196)
	at gama.core.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:532)
	at gama.core.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:714)
	at gama.core.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:772)
	at gama.core.kernel.experiment.DefaultExperimentController.processUserCommand(DefaultExperimentController.java:72)
	at gama.core.kernel.experiment.AbstractExperimentController.lambda$0(AbstractExperimentController.java:63)
	at java.base/java.lang.Thread.run(Thread.java:842)
Adding exception to error collector1 occurence in a0 at cycle 0: Java error: index out of bounds
in a0
in agent a0
in write 'content: ' + l[0] ;
IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
java.base/java.util.Objects.checkIndex(Objects.java:359)
java.base/java.util.ArrayList.get(ArrayList.java:427)
gama.core.util.IList.get(IList.java:369)
gama.core.util.GamaList.getFromIndicesList(GamaList.java:116)
when applying the internal_at operator on [] and [0]
in write 'content: ' + l[0] ;
```

**Expected behavior**
The error view opens with an error message

**Comment by lesquoyb** [comment]
closing because it was just because I (unknowingly) completely deactivated the errors in my configuration
