### ISSUE TITLE
"No implementation for msi.gama.lang.gaml.indexer.BaseIndexer" error in Headless mode with OpenMole

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1972]
I have some problem using OpenMOLE latest build with latest build version of gama dev on Linux 16.04 ( GAMA1.7_Linux_64_09.06.16_bb1b3d2.zip ). 

Using the very simple Voronoi example in Gama and OpenMOLE ( which i precise already worked with older version of Gama dev build), i have this error now : 

```
1) No implementation for msi.gama.lang.gaml.indexer.BaseIndexer was bound.
 |   at msi.gama.lang.gaml.GamlRuntimeModule.configure(GamlRuntimeModule.java:98)
 | 
```

It seems This error appear only in headless mode.

Any idea or path to follow ? 

Complete error during execution 

```
org.openmole.core.exception.InternalProcessingError: Error for context values in GamaTask@2116400271 {num_points=5, oMSeed=5421200424958686426, seed=42}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:83)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:129)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | Java error: CreationException
 | 	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:70)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.preloadGAMA(HeadlessSimulationLoader.java:61)
 | 	at msi.gama.headless.openmole.MoleSimulationLoader.loadGAMA(MoleSimulationLoader.java:24)
 | 	at org.openmole.plugin.task.gama.GamaTask$.preload$lzycompute(GamaTask.scala:56)
 | 	at org.openmole.plugin.task.gama.GamaTask$.preload(GamaTask.scala:56)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:84)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
 | 	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
 | 	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:83)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
 | 	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:129)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
 | 	at java.lang.Thread.run(Thread.java:745)
 | Caused by: com.google.inject.CreationException: Guice creation errors:
 | 
 | 1) No implementation for msi.gama.lang.gaml.indexer.BaseIndexer was bound.
 |   at msi.gama.lang.gaml.GamlRuntimeModule.configure(GamlRuntimeModule.java:98)
 | 
 | 1 error
 | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
 | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
 | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
 | 	at com.google.inject.Guice.createInjector(Guice.java:95)
 | 	at com.google.inject.Guice.createInjector(Guice.java:72)
 | 	at com.google.inject.Guice.createInjector(Guice.java:62)
 | 	at msi.gama.lang.gaml.GamlStandaloneSetupGenerated.createInjector(GamlStandaloneSetupGenerated.java:40)
 | 	at msi.gama.lang.gaml.GamlStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(GamlStandaloneSetupGenerated.java:34)
 | 	at msi.gama.lang.gaml.GamlStandaloneSetup.doSetup(GamlStandaloneSetup.java:22)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.preloadGAMA(HeadlessSimulationLoader.java:59)
 | 	... 23 more
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:116)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 13 more
```

**Comment by AlexisDrogoul** [comment]
Right. Problem introduced in my latest commits -- BaseIndexer does not seem to be found by the headless GAMA (although it is -- should be -- present in the msi.gama.lang.gaml plugin). Will try to find out why.

**Comment by reyman** [comment]
I have a similar error after test on the new gama build, also with voronoi example : 

```
| Caused by: com.google.inject.CreationException: Guice creation errors:
 | 1) No implementation for org.eclipse.xtext.resource.containers.IAllContainersState$Provider was bound.
 |   while locating org.eclipse.xtext.resource.containers.IAllContainersState$Provider
 |     for field at org.eclipse.xtext.resource.containers.StateBasedContainerManager.stateProvider(Unknown Source)
 |   at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
 | 
```

Complete error  : 
```

org.openmole.core.exception.InternalProcessingError: Error for context values in GamaTask@613343700 {num_points=5, oMSeed=9057653627115189309, seed=42}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:83)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:129)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | Java error: CreationException
 | 	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:70)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.preloadGAMA(HeadlessSimulationLoader.java:61)
 | 	at msi.gama.headless.openmole.MoleSimulationLoader.loadGAMA(MoleSimulationLoader.java:24)
 | 	at org.openmole.plugin.task.gama.GamaTask$.preload$lzycompute(GamaTask.scala:56)
 | 	at org.openmole.plugin.task.gama.GamaTask$.preload(GamaTask.scala:56)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:84)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
 | 	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
 | 	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:83)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
 | 	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:129)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
 | 	at java.lang.Thread.run(Thread.java:745)
 **| Caused by: com.google.inject.CreationException: Guice creation errors:
 | 
 | 1) No implementation for org.eclipse.xtext.resource.containers.IAllContainersState$Provider was bound.
 |   while locating org.eclipse.xtext.resource.containers.IAllContainersState$Provider
 |     for field at org.eclipse.xtext.resource.containers.StateBasedContainerManager.stateProvider(Unknown Source)
 |   at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
 | 
 | 1 error
 | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
 | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
 | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
 | 	at com.google.inject.Guice.createInjector(Guice.java:95)
 | 	at com.google.inject.Guice.createInjector(Guice.java:72)
 | 	at com.google.inject.Guice.createInjector(Guice.java:62)
 | 	at** msi.gama.lang.gaml.GamlStandaloneSetupGenerated.createInjector(GamlStandaloneSetupGenerated.java:40)
 | 	at msi.gama.lang.gaml.GamlStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(GamlStandaloneSetupGenerated.java:34)
 | 	at msi.gama.lang.gaml.GamlStandaloneSetup.doSetup(GamlStandaloneSetup.java:22)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.preloadGAMA(HeadlessSimulationLoader.java:59)
 | 	... 23 more
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:116)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 13 more


```
