### ISSUE TITLE
Issue with ISkill interface  and Openmole headless gama-plugin

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1987]
Using the latest gama continuous build, and gama-plugin for openmole, we discover a new error probably introduced in a recent commit.

```
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | java.lang.NoSuchMethodError: msi.gama.common.interfaces.ISkill.getDescription()Lmsi/gaml/descriptions/SkillDescription;
 | 	at msi.gaml.descriptions.SpeciesDescription.setSkills(SpeciesDescription.java:175)
```

complete log : 

```

org.openmole.core.exception.InternalProcessingError: Error for context values in GamaTask@-1668712544 {num_points=5, oMSeed=-4890871437263511566, seed=42}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:85)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:136)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | java.lang.NoSuchMethodError: msi.gama.common.interfaces.ISkill.getDescription()Lmsi/gaml/descriptions/SkillDescription;
 | 	at msi.gaml.descriptions.SpeciesDescription.setSkills(SpeciesDescription.java:175)
 | 	at msi.gaml.descriptions.SpeciesDescription.<init>(SpeciesDescription.java:99)
 | 	at msi.gaml.descriptions.SpeciesDescription.<init>(SpeciesDescription.java:92)
 | 	at msi.gaml.factories.SpeciesFactory.buildDescription(SpeciesFactory.java:46)
 | 	at msi.gaml.factories.SpeciesFactory.buildDescription(SpeciesFactory.java:1)
 | 	at msi.gaml.factories.DescriptionFactory.create(DescriptionFactory.java:273)
 | 	at msi.gaml.factories.ModelAssembler.addMicroSpecies(ModelAssembler.java:390)
 | 	at msi.gaml.factories.ModelAssembler$4.execute(ModelAssembler.java:169)
 | 	at msi.gaml.factories.ModelAssembler$4.execute(ModelAssembler.java:1)
 | 	at msi.gama.util.TOrderedHashMap.forEachValue(TOrderedHashMap.java:170)
 | 	at msi.gaml.factories.ModelAssembler.assemble(ModelAssembler.java:165)
 | 	at msi.gaml.factories.ModelFactory.createModelDescription(ModelFactory.java:47)
 | 	at msi.gama.lang.gaml.resource.GamlResource.buildModelDescription(GamlResource.java:111)
 | 	at msi.gama.lang.gaml.resource.GamlResource.buildCompleteDescription(GamlResource.java:161)
 | 	at msi.gama.lang.gaml.validation.GamlModelBuilder.buildModelDescription(GamlModelBuilder.java:56)
 | 	at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:40)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:75)
 | 	at msi.gama.headless.openmole.MoleSimulationLoader.loadModel(MoleSimulationLoader.java:29)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$.org$openmole$plugin$task$gama$GamaTask$$withDisposable(GamaTask.scala:60)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
 | 	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
 | 	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:85)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
 | 	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:136)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
 | 	at java.lang.Thread.run(Thread.java:745)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:116)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 13 more
```

**Comment by AlexisDrogoul** [comment]
Hmmm... Probably some cache problem, no ? Because https://github.com/gama-platform/gama/blob/master/msi.gama.core/src/msi/gama/common/interfaces/ISkill.java is ok.

**Comment by reyman** [comment]
I try to remove all cache from .m2 and .ivy to see if the problem is cache, and after that i update this answer with result.

**Comment by reyman** [comment]
Hum, the same error continue to appear after clean of different caches (maven,sbt), with simple or complex example : 

```
org.openmole.core.exception.InternalProcessingError: Error for context values in GamaTask@-1559293756 {num_points=5, oMSeed=-7067960694381665525, seed=42}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:85)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:136)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.UserBadDataError: Gama raised the exception:
 | java.lang.NoSuchMethodError: msi.gama.common.interfaces.ISkill.getDescription()Lmsi/gaml/descriptions/SkillDescription;
 | 	at msi.gaml.descriptions.SpeciesDescription.setSkills(SpeciesDescription.java:175)
 | 	at msi.gaml.descriptions.SpeciesDescription.<init>(SpeciesDescription.java:99)
 | 	at msi.gaml.descriptions.SpeciesDescription.<init>(SpeciesDescription.java:92)
 | 	at msi.gaml.factories.SpeciesFactory.buildDescription(SpeciesFactory.java:46)
 | 	at msi.gaml.factories.SpeciesFactory.buildDescription(SpeciesFactory.java:1)
 | 	at msi.gaml.factories.DescriptionFactory.create(DescriptionFactory.java:273)
 | 	at msi.gaml.factories.ModelAssembler.addMicroSpecies(ModelAssembler.java:390)
 | 	at msi.gaml.factories.ModelAssembler$4.execute(ModelAssembler.java:169)
 | 	at msi.gaml.factories.ModelAssembler$4.execute(ModelAssembler.java:1)
 | 	at msi.gama.util.TOrderedHashMap.forEachValue(TOrderedHashMap.java:170)
 | 	at msi.gaml.factories.ModelAssembler.assemble(ModelAssembler.java:165)
 | 	at msi.gaml.factories.ModelFactory.createModelDescription(ModelFactory.java:47)
 | 	at msi.gama.lang.gaml.resource.GamlResource.buildModelDescription(GamlResource.java:111)
 | 	at msi.gama.lang.gaml.resource.GamlResource.buildCompleteDescription(GamlResource.java:161)
 | 	at msi.gama.lang.gaml.validation.GamlModelBuilder.buildModelDescription(GamlModelBuilder.java:56)
 | 	at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:40)
 | 	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:75)
 | 	at msi.gama.headless.openmole.MoleSimulationLoader.loadModel(MoleSimulationLoader.java:29)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$.org$openmole$plugin$task$gama$GamaTask$$withDisposable(GamaTask.scala:60)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:88)
 | 	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
 | 	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
 | 	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
 | 	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:67)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:85)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
 | 	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:136)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
 | 	at java.lang.Thread.run(Thread.java:745)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:116)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:82)
	at org.openmole.plugin.task.external.External.withWorkDir(External.scala:176)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:82)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:59)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 13 more
```

**Comment by AlexisDrogoul** [comment]
Hmm.. Unfortunately, there is nothing I can do since the ISkill class has the right method and is at the right place in the repository, as you can see yourself.

**Comment by reyman** [comment]
I can try to search which commit create this problem ...

**Comment by AlexisDrogoul** [comment]
There is a commit where ISkill has moved from one plugin to another, while remaining in the same package. So that's why I was speaking about possible cache problems, if you have an old version of the ummisco.gama.annotations plugin lying around.

**Comment by reyman** [comment]
Ok, this is strange... I trash completely my `.m2` and `.ivy`, redownload Internet, and retry. If the error persist, i really don't understand. I update here the result in 1 hour probably ...

**Comment by reyman** [comment]
Hummm, i'm lost, i trash all possible cache, also the p2site online, and the error continue to exist. I reverse engineer the .class, and the method correctly exist in the jar. Only way to find is probably to revert to an old commit of gama and search when problem appear.

**Comment by reyman** [comment]
@AlexisDrogoul I progress, i found some strange things in ummisco.gama.annotations , as you can see in the image, the `src/` file `ISkill.java` don't exist (normal), but the folder `target/` generated contain a ISkill.class ... 

![weird2](https://cloud.githubusercontent.com/assets/466329/18525019/2f07b15e-7abb-11e6-866e-f9168bb158b4.jpg)

![weird](https://cloud.githubusercontent.com/assets/466329/18525024/346c4a10-7abb-11e6-8561-65904739af0c.jpg)
 
We need to change `mvn install` to `mvn clean install` on travis to remove this type of problem :)

I recompile and test, this is probably my problem...

**Comment by reyman** [comment]
Oh well well well ... this is that. Voronoi works :)
I update the build.sh with clean and close the issue.
