### ISSUE TITLE
Shader Opengl not working on Mac OS

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1989]
### Steps to reproduce
1. Inany opengl display  add the following line
use_shader:true 

2. Run it

I get this error:

java.nio.file.NoSuchFileException: Applications/Eclipse.app/Contents/Eclipse/../../../../Users/Arno/git/gama/ummisco.gama.opengl/src/ummisco/gama/modernOpenGL/shader/../shader/vertexShader
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.Files.readAllBytes(Files.java:3152)
    at ummisco.gama.modernOpenGL.shader.AbstractShader.readFile(AbstractShader.java:174)
    at ummisco.gama.modernOpenGL.shader.AbstractShader.loadShader(AbstractShader.java:75)
    at ummisco.gama.modernOpenGL.shader.AbstractShader.<init>(AbstractShader.java:51)
    at ummisco.gama.modernOpenGL.shader.ShaderProgram.<init>(ShaderProgram.java:36)
    at ummisco.gama.modernOpenGL.ModernDrawer.setShaderToEntity(ModernDrawer.java:127)
    at ummisco.gama.modernOpenGL.ModernDrawer.addDrawingEntities(ModernDrawer.java:88)
    at ummisco.gama.modernOpenGL.ModernDrawer.addDrawingEntities(ModernDrawer.java:78)
    at ummisco.gama.opengl.scene.LayerObject.drawWithShader(LayerObject.java:121)
    at ummisco.gama.opengl.scene.LayerObject.draw(LayerObject.java:96)
    at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:168)
    at ummisco.gama.opengl.ModernRenderer.drawScene(ModernRenderer.java:238)
    at ummisco.gama.opengl.ModernRenderer.display(ModernRenderer.java:166)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
    at ummisco.gama.opengl.SWTGLAnimator.displayGL(SWTGLAnimator.java:184)
    at ummisco.gama.opengl.SWTGLAnimator.run(SWTGLAnimator.java:165)
    at java.lang.Thread.run(Thread.java:745)
Runtime error null in OpenGL loop

### Actual behavior
I think it's working on windows. Something related to mac ?

### System and version 
Current version - Mac OS X

**Comment by AlexisDrogoul** [comment]
I have just looked briefly, and I guess the use of getResource() + File.separator + relative paths is clearly not the best way to do it -- and it probably won't work in scenarios with white spaces in the middle also.

I would then advise to put all shaders found in different packages into only one `shaders` folder somewhere in `src` and use, in each class, `getClass().getClassLoader().getResource()` or `getResourceAsStream()` with an **ABSOLUTE** path to the file you want to load.

For instance, if you put `shaders` directly below `src`, your path would remain the same for all classes (`/ shaders/`), and you can read directly the files as streams (no need to find their absolute paths and read them as strings to transform them into bytes afterwards, as I've seen in the code). You can probably directly obtain the byte stream and send it to OpenGL to compile with `getResourceAsStream`.

**Comment by mazarsju** [comment]
I changed some things, I hope it'll work better now. Please feel free to open it again if it's not working.

**Comment by agrignard** [comment]
The error about the file is fixed but I still have a problem of compilation in the shader.

SWTAccessor.<init>: GTK Version: 0.0.0
argument : --launcher.defaultAction
argument : openFile
Error compiling the vertex shader: ERROR: 0:43: Incompatible types (vec2 and vec3) in assignment (and no available implicit conversion)
ERROR: 0:50: '==' does not operate on 'float' and 'int'
ERROR: 0:59: Invalid call of undeclared identifier 'inverse'

**Comment by mazarsju** [comment]
I corrected the 3 errors you have, but I cannot guaranty that there are not others, as the GLSL version in Mac does not seems the same that the one I have... Please give me the logs if you find other errors.

**Comment by agrignard** [comment]
I have now another error:

!ENTRY org.eclipse.core.net 1 0 2016-09-19 10:09:51.769
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
SWTAccessor.<init>: GTK Version: 0.0.0
argument : --launcher.defaultAction
argument : openFile
Error compiling the vertex shader: ERROR: 0:37: Invalid call of undeclared identifier 'texture'
ERROR: 0:81: Invalid call of undeclared identifier 'texture'

**Comment by mazarsju** [comment]
Corrected. A new one ? :)

**Comment by agrignard** [comment]
great it works now!

**Comment by agrignard** [comment]
hehe no sorry one more now when using kesytone

Error compiling the vertex shader: ERROR: 0:22: '*' does not operate on 'float' and 'int'
ERROR: 0:25: Use of undeclared identifier 'pixelSize'

**Comment by mazarsju** [comment]
Stupid issue... It should work now

**Comment by agrignard** [comment]
SWTAccessor.<init>: GTK Version: 0.0.0
argument : --launcher.defaultAction
argument : openFile
Error compiling the vertex shader: ERROR: 0:25: '*' does not operate on 'float' and 'int'

**Comment by mazarsju** [comment]
Done ! I hope it was the last one...

**Comment by agrignard** [comment]
Cool it's working right now. I will now test the keystone. I hope there won't be to much issue ;-)
