### ISSUE TITLE
Problem with Picking in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1994]
Sorry to put that dirty issue but this is what I get sometime when I am doing picking to inspect an Agent and it freezes GAMA...

My display is made of a png background , building roads and people species... nothing so exotic isn't it?

This is the error I get:

Runtime error null in OpenGL loop
java.lang.NullPointerException
	at msi.gama.metamodel.agent.AgentIdentifier.getAgent(AgentIdentifier.java:56)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.selectAgent(SWTOpenGLDisplaySurface.java:581)
	at ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:156)
	at ummisco.gama.opengl.scene.LayerObject.drawPicking(LayerObject.java:213)
	at ummisco.gama.opengl.scene.LayerObject.drawWithoutShader(LayerObject.java:155)
	at ummisco.gama.opengl.scene.LayerObject.draw(LayerObject.java:98)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:168)
	at ummisco.gama.opengl.JOGLRenderer.drawScene(JOGLRenderer.java:330)
	at ummisco.gama.opengl.JOGLRenderer.display(JOGLRenderer.java:233)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:677)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at jogamp.opengl.GLDrawableHelper.invoke(GLDrawableHelper.java:912)
	at com.jogamp.opengl.swt.GLCanvas.invoke(GLCanvas.java:789)
	at ummisco.gama.opengl.camera.AbstractCamera.mouseDown(AbstractCamera.java:278)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:43)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by AlexisDrogoul** [comment]
Is this bug still present ? If no, I let you close the issue.
