### ISSUE TITLE
Segregation model broken 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1997]
### Steps to reproduce
1. try to run Segregation (Cellular Automata)

I get the following error and no way to run the model:

java.lang.NullPointerException
	at msi.gama.metamodel.topology.grid.GamaSpatialMatrix.dispose(GamaSpatialMatrix.java:117)
	at msi.gama.metamodel.topology.grid.GridTopology.dispose(GridTopology.java:270)
	at msi.gama.metamodel.population.GamaPopulation.dispose(GamaPopulation.java:272)
	at msi.gama.metamodel.agent.GamlAgent.dispose(GamlAgent.java:209)
	at msi.gama.kernel.simulation.SimulationAgent.dispose(SimulationAgent.java:312)
	at msi.gama.metamodel.population.GamaPopulation.killMembers(GamaPopulation.java:616)
	at msi.gama.metamodel.population.GamaPopulation.dispose(GamaPopulation.java:268)
	at msi.gama.kernel.simulation.SimulationPopulation.dispose(SimulationPopulation.java:109)
	at msi.gama.kernel.experiment.ExperimentAgent.closeSimulations(ExperimentAgent.java:157)
	at msi.gama.kernel.experiment.ExperimentAgent.dispose(ExperimentAgent.java:177)
	at msi.gama.kernel.experiment.ExperimentPlan.dispose(ExperimentPlan.java:199)
	at msi.gama.kernel.experiment.ExperimentController.closeExperiment(ExperimentController.java:266)
	at msi.gama.kernel.experiment.ExperimentController.close(ExperimentController.java:256)
	at msi.gama.runtime.GAMA.closeAllExperiments(GAMA.java:173)
	at msi.gama.runtime.GAMA.runGuiExperiment(GAMA.java:89)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runModel(ModelRunner.java:96)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runModel(ModelRunner.java:136)
	at msi.gama.lang.gaml.ui.editor.toolbar.OpenExperimentSelectionListener.widgetSelected(OpenExperimentSelectionListener.java:62)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at ummisco.gama.ui.controls.FlatButton.doButtonClicked(FlatButton.java:144)
	at ummisco.gama.ui.controls.FlatButton.handleEvent(FlatButton.java:103)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:43)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by agrignard** [comment]
The bad thing (I don't know if it happens to you also) but when I have thos bug I then have no way to kill GAMA Platform process even with a Force Quit...

**Comment by hqnghi88** [comment]
Hi Arnaud,
I cant reproduce this issue.

**Comment by hqnghi88** [comment]
Could you have an export of your Preferences then?

**Comment by AlexisDrogoul** [comment]
Yeah, same for me I can't. And it 's the same with #1994 . I wonder if you dont have a broken workspace / preferences somewhere.

**Comment by agrignard** [comment]
Mmmm ok thank you Eclipse. I don't see what is wrong with my workspace but
I can reinstall it from scratch for the Nth times... or used a stable
binary version?

**Comment by agrignard** [comment]
I reinstalled everything from scratch and I still have the same problem...

Here is a screenshot of my GAMA I have 3 errors in msi.gama.parent can it
come from this????

**Comment by ptaillandier** [comment]
Hi,


I do not have the same issue as Arnaud, but this model (Schelling -
cellular automata) does work on my computer (last Git version, new
workspace).
I have this error:

 at cycle 0: Java error: wrong casting
ClassCastException:
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation$MinimalGridAgent
cannot be cast to msi.gama.metamodel.agent.IMacroAgent
gaml.additions.GamlAdditions$156.run(GamlAdditions.java:229)
msi.gaml.variables.Variable._setVal(Variable.java:448)
msi.gaml.variables.Variable.initializeWith(Variable.java:389)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation.createAgents(GamaSpatialMatrix.java:1205)
msi.gama.metamodel.topology.AbstractTopology.initialize(AbstractTopology.java:182)
msi.gama.metamodel.topology.grid.GridTopology.initialize(GridTopology.java:55)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation.initializeFor(GamaSpatialMatrix.java:1286)

Cheers,

Patrick

2016-09-20 20:04 GMT+02:00 Arnaud Grignard <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Well, this is one the (hopefully few) cases where perpendicular choices make things difficult. The immediate workaround to this bug is to enable the preference "Automatically optimize the memory used by agents". I will try to issue a fix soon.
