### ISSUE TITLE
Null topology in Toy Models\Urban Growth\models\raster model.gaml

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2020]
### Steps to reproduce
1. Run
Toy Models\Urban Growth\models\raster model.gaml

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
Handler launched
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:70)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:89)
	at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:395)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:385)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:396)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:374)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:160)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:133)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:239)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:199)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:203)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:208)
	at msi.gama.runtime.AbstractScope.init(AbstractScope.java:437)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:167)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:264)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:333)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:97)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at msi.gama.metamodel.population.GamaPopulation.buildGridTopology(GamaPopulation.java:518)
	at msi.gama.metamodel.population.GamaPopulation.createPopulation(GamaPopulation.java:75)
	at msi.gama.kernel.simulation.SimulationAgent.getPopulationFor(SimulationAgent.java:358)
	at msi.gaml.expressions.SpeciesConstantExpression.value(SpeciesConstantExpression.java:39)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:79)
	... 16 more
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
latest git

**Comment by AlexisDrogoul** [comment]
Bad var dependency computation (species constant expressions were left aside). I'm pushing a fix.
