### ISSUE TITLE
Problems with the Network plug-in

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2041]
### Steps to reproduce 1
1. Open the plug-ins model-> Network -> Multi-simulation Network.gaml and try to run the model

### Actual behavior 1
I got this error:
eate mqtt serveur null null
Impossible de se connecter au serveur (32103) - java.net.ConnectException: Connection refused
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	... 2 more
Client non connecté (32104)
	
### Steps to reproduce 2
1. test the following model:
model testNetwork

global {
	int val update: rnd(10);
	init {
		create network_ag
			{
				name<-"Server";
				 do connect to:"localhost" protocol:"tcp_server" port: 3001 with_name:name;
			}
	}
	reflex info {
		write val;
	}
}

species network_ag skills: [network];

experiment main_xp type: gui {
	output {
		display "charts" {
			chart "my chart" type: series {
				data "vals"  value: val color: #red ; 
				
			}
		}
	}
}
### Actual behavior 2
The chart is not updated (same results for other type of layers).
Note that I have no error and that if I remove the line "do connect to:"localhost" protocol:"tcp_server" port: 3001 with_name:name;" it works.

### System and version 
Git version

**Comment by gnoubi** [comment]
hi,
have you downloaded and started activemq server ? 
Nicolas

**Comment by ptaillandier** [comment]
Hi,
No.
Here, I was just wanted to make communicate 2 GAMAs on the same computer.
Note that it was working well few weeks ago.
Patrick


2016-11-04 15:53 GMT+01:00 gnoubi <notifications@github.com>:

**Comment by gnoubi** [comment]
Hum, 

you give me server source code.
what is the client code ? 

nicolas

**Comment by AlexisDrogoul** [comment]
Any news on this one ? Is the network plugin still failing ?

**Comment by hqnghi88** [comment]
Hi, I did not noticed the second behavior in this issue, I 'm investigating it now.

**Comment by AlexisDrogoul** [comment]
Seems to have been solved (but not tested) on the latest version. Closing it for now on, reopen if you are still experiencing problems.
