### ISSUE TITLE
No output configuration with name 'DEFAULT_OUTPUT' exists

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2063]
### Steps to reproduce
1. Open Feature\Co-model Usage\Syntax\Simple Comodel

2. Launch experiment

### Expected behavior
Tell us what should happen (include all relevant expectations)
"normal behavior"
### Actual behavior
An exception appear in eclipse console, but no bad phenomenon  (error, wrong displays...) in GAMA
1397009 [Worker-18] ERROR org.eclipse.xtext.builder.impl.XtextBuilder  - No output configuration with name 'DEFAULT_OUTPUT' exists.
java.lang.IllegalArgumentException: No output configuration with name 'DEFAULT_OUTPUT' exists.
	at org.eclipse.xtext.generator.AbstractFileSystemAccess.getOutputConfig(AbstractFileSystemAccess.java:67)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:551)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:541)
	at org.eclipse.xtext.builder.BuilderParticipant.cleanDerivedResources(BuilderParticipant.java:351)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:285)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.apache.log4j 4 0 2016-12-09 14:06:49.798
!MESSAGE org.eclipse.xtext.builder.impl.XtextBuilder  - No output configuration with name 'DEFAULT_OUTPUT' exists.

!STACK 0
java.lang.IllegalArgumentException: No output configuration with name 'DEFAULT_OUTPUT' exists.
	at org.eclipse.xtext.generator.AbstractFileSystemAccess.getOutputConfig(AbstractFileSystemAccess.java:67)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:551)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:541)
	at org.eclipse.xtext.builder.BuilderParticipant.cleanDerivedResources(BuilderParticipant.java:351)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:285)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
GAMA Caught a workbench message : org.eclipse.xtext.builder.impl.XtextBuilder  - No output configuration with name 'DEFAULT_OUTPUT' exists.
 java.lang.IllegalArgumentException: No output configuration with name 'DEFAULT_OUTPUT' exists.
java.lang.IllegalArgumentException: No output configuration with name 'DEFAULT_OUTPUT' exists.
	at org.eclipse.xtext.generator.AbstractFileSystemAccess.getOutputConfig(AbstractFileSystemAccess.java:67)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:551)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.deleteFile(EclipseResourceFileSystemAccess2.java:541)
	at org.eclipse.xtext.builder.BuilderParticipant.cleanDerivedResources(BuilderParticipant.java:351)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:285)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Harmful error. I dont know exactly what produces it, but it effectively happens from time to time.
