### ISSUE TITLE
Simple Co-model can't run

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2064]
### Steps to reproduce
1. Launch experiment of Feature\Co-model USage\Syntax\Simple Comodel.gaml

2. Press PLay button

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Eclipse's exception:
java.lang.NullPointerException
	at msi.gaml.species.GamlSpecies.stream(GamlSpecies.java:362)
	at msi.gaml.operators.Containers.stream(Containers.java:89)
	at msi.gaml.operators.Containers.collect(Containers.java:1433)
	at gaml.additions.GamlAdditions$923.run(GamlAdditions.java:960)
	at gaml.additions.GamlAdditions$923.run(GamlAdditions.java:1)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:80)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:124)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:356)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:261)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:233)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA).

Are the other co-models affected as well ?

**Comment by hqnghi88** [comment]
Yes, co-modeling is stop working, i'm fixing it.

**Comment by AlexisDrogoul** [comment]
By the way -- a bit unrelated, but still. Would it be possible to have a really **simple** "Simple Co-Model" that doesn't open 10 displays (so that people can maybe figure out what is happening) ?

**Comment by AlexisDrogoul** [comment]
Have you found the cause ? There seems to be several (small) things going on that prevent the comodels to run correctly, but I can't really figure them out.

**Comment by hqnghi88** [comment]
Dear Alexis,
I'm working on it, I found 2 things: wrong micro-model population finding, and the wrong file path computation, I try a little bit more to find a clear solution.

**Comment by AlexisDrogoul** [comment]
Did 20b9975f004884b0cc56f13516fb67a60a24e7c8 solve the problem ?

**Comment by hqnghi88** [comment]
Yes, it works.
