### ISSUE TITLE
Elapsed time window bug

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2093]
### Steps to reproduce
1. Open any model I have been testing it with (Tuto/Road Traffic/models/Model 07.gaml)

### Expected behavior
The elapsed time should work.

### Actual behavior
I have some exception some time throwing this error when I want to see in details the elapsed time (by having the mouse on the window):

GAMA Caught a workbench message : Unhandled event loop exception org.eclipse.swt.SWTException: Failed to execute runnable (java.time.DateTimeException: Field HourOfDay cannot be printed as the value -8 cannot be negative according to the SignStyle)
org.eclipse.swt.SWTException: Failed to execute runnable (java.time.DateTimeException: Field HourOfDay cannot be printed as the value -8 cannot be negative according to the SignStyle)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.time.DateTimeException: Field HourOfDay cannot be printed as the value -8 cannot be negative according to the SignStyle
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2573)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at msi.gaml.operators.Dates$DurationFormatter.toString(Dates.java:915)
	at msi.gaml.operators.Dates$DurationFormatter.format(Dates.java:863)
	at msi.gaml.operators.Dates.asDuration(Dates.java:820)
	at ummisco.gama.ui.controls.StatusControlContribution.getPopupText(StatusControlContribution.java:188)
	at ummisco.gama.ui.controls.Popup.display(Popup.java:110)
	at ummisco.gama.ui.controls.Popup$1.lambda$0(Popup.java:53)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 24 more

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
It was complicated (time zones and local times mixed together, and the difficulty to convert them to durations), but I got it working.
