### ISSUE TITLE
Out of memory with Ant Foraging (Chart examples)

### ISSUE THREAD

**Issue by nordie69** [gama-platform/gama#2095]
### Steps to reproduce
1. Run the Ant Foraging (Charts example).gaml model. Tr yit with or even without the charts (close them after starting the model).

### Expected behavior
The model should run forever.

### Actual behavior
After some time (here at my system: ca. 2.900 cycles) there is an out of memory error. While this is happening, the used memory displayed at the bottom nerby the collector symbol is below 2000M. This bebaviour is regardless of having the chart activated or not.

### System and version 
GIT version of GAMA 1.7.0.201701102200. Windows 8.1.

**Comment by benoitgaudou** [comment]
Hi, 

I thus tried this issue and I also had this OutOfMemoryError (even with 8Go allocated to GAMA).
The error message is GAMA is the following one :
<img width="1366" alt="screen shot 2017-01-11 at 23 59 12" src="https://cloud.githubusercontent.com/assets/1555274/21869892/fb56fd5e-d859-11e6-925f-962ad1d48c66.png">

I can add that the exception in the Eclipse console is the following one: 

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at msi.gama.outputs.layers.charts.ChartDataSeries.savelistd(ChartDataSeries.java:426)
	at msi.gama.outputs.layers.charts.ChartDataSeries.savehistory(ChartDataSeries.java:476)
	at msi.gama.outputs.layers.charts.ChartDataSource.savehistory(ChartDataSource.java:862)
	at msi.gama.outputs.layers.charts.ChartDataSet.updatedataset(ChartDataSet.java:320)
	at msi.gama.outputs.layers.charts.ChartOutput.step(ChartOutput.java:125)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._step(ChartLayerStatement.java:438)
	at msi.gama.outputs.layers.AbstractLayerStatement.step(AbstractLayerStatement.java:103)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.outputs.LayeredDisplayOutput.step(LayeredDisplayOutput.java:636)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.outputs.AbstractOutputManager.lambda$2(AbstractOutputManager.java:170)
	at msi.gama.outputs.AbstractOutputManager$$Lambda$227/1332318552.apply(Unknown Source)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at msi.gama.outputs.AbstractOutputManager.step(AbstractOutputManager.java:170)
	at msi.gama.kernel.simulation.SimulationAgent.postStep(SimulationAgent.java:280)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:250)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner$$Lambda$159/921065820.apply(Unknown Source)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:54)
	at msi.gama.runtime.concurrent.SimulationRunner$$Lambda$221/1398023589.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at msi.gama.outputs.layers.charts.ChartDataSeries.savehistory(ChartDataSeries.java:447)
	at msi.gama.outputs.layers.charts.ChartDataSource.savehistory(ChartDataSource.java:862)
	at msi.gama.outputs.layers.charts.ChartDataSet.updatedataset(ChartDataSet.java:320)
	at msi.gama.outputs.layers.charts.ChartOutput.step(ChartOutput.java:125)
	at msi.gama.outputs.layers.charts.ChartLayerStatement._step(ChartLayerStatement.java:438)
	at msi.gama.outputs.layers.AbstractLayerStatement.step(AbstractLayerStatement.java:103)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.outputs.LayeredDisplayOutput.step(LayeredDisplayOutput.java:636)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.outputs.AbstractOutputManager.lambda$2(AbstractOutputManager.java:170)
	at msi.gama.outputs.AbstractOutputManager$$Lambda$227/1332318552.apply(Unknown Source)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at msi.gama.outputs.AbstractOutputManager.step(AbstractOutputManager.java:170)
	at msi.gama.kernel.simulation.SimulationAgent.postStep(SimulationAgent.java:280)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:250)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner$$Lambda$159/921065820.apply(Unknown Source)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:54)
	at msi.gama.runtime.concurrent.SimulationRunner$$Lambda$221/1398023589.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

Benoit

**Comment by nordie69** [comment]
Thanks for adding the exact error message. I will do so the next time ;-)

Stefan
