### ISSUE TITLE
Issue with getRealSpeed() in AdvancedDrivingSkill (NPE)

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2101]
### Steps to reproduce
1. Launch a model using the advanced driving skill, without any change to the model itself (i.e. no special preparation for the enhancements made recently). 

2. Run the model.

### Expected behavior
That it works as usual :)

### Actual behavior
The simulation stops in error. The following exception is raised:

```
java.lang.NullPointerException
	at simtools.gaml.extensions.traffic.AdvancedDrivingSkill.getRealSpeed(AdvancedDrivingSkill.java:404)
	at simtools.gaml.extensions.traffic.AdvancedDrivingSkill.speedChoice(AdvancedDrivingSkill.java:796)
	at simtools.gaml.extensions.traffic.AdvancedDrivingSkill.primSpeedChoice(AdvancedDrivingSkill.java:1022)
	at gaml.additions.GamlAdditions$82.run(GamlAdditions.java:121)
	at gaml.additions.GamlAdditions$82.run(GamlAdditions.java:1)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at simtools.gaml.extensions.traffic.AdvancedDrivingSkill.primDrive(AdvancedDrivingSkill.java:925)
	at gaml.additions.GamlAdditions$84.run(GamlAdditions.java:123)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:243)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:356)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:178)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:153)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:175)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:170)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:422)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:82)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

### System and version 
Latest Git version, macOS Sierra, JDK 1.8

**Comment by ptaillandier** [comment]
Did you change something concerning the init value of attributes ? I mean, before, when the value of an attribute was not set (in the java code or model), the init value was the one given by the init facet in @var. Now, if the attribute value is not set, the value is null.

**Comment by ptaillandier** [comment]
Finally, it is because of my last commit. I will fix that soon.
