### ISSUE TITLE
Java Exception in Animated GIF Loading (with parallel computation)

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2121]
### Steps to reproduce
1. Open and Launch Data Importation\Animated GIF Loading.gaml

2. Run the simulation. It pass few steps (<10)

3. Then the exceptions appear. Here is the stack trace
Agents stack is empty
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class msi.gama.metamodel.agent.GamlAgent id= 1391957946 hashCode= 1391957946 toString= fish89; object #2 =class msi.gama.metamodel.agent.GamlAgent id= 1391957946 hashCode= 1391957946 toString= fish89

	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:426)
	at msi.gama.util.TOrderedHashMap.rehash(TOrderedHashMap.java:138)
	at gnu.trove.impl.hash.THash.compact(THash.java:201)
	at gnu.trove.impl.hash.THash.removeAt(THash.java:272)
	at gnu.trove.impl.hash.TObjectHash.removeAt(TObjectHash.java:104)
	at gnu.trove.map.hash.THashMap.removeAt(THashMap.java:468)
	at msi.gama.util.TOrderedHashMap.removeAt(TOrderedHashMap.java:151)
	at gnu.trove.map.hash.THashMap.remove(THashMap.java:455)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.remove(GamaQuadTree.java:192)
	at msi.gama.metamodel.topology.GamaQuadTree.remove(GamaQuadTree.java:91)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.remove(CompoundSpatialIndex.java:82)
	at msi.gama.metamodel.topology.AbstractTopology.updateAgent(AbstractTopology.java:226)
	at msi.gama.metamodel.agent.MinimalAgent.setLocation(MinimalAgent.java:152)
	at msi.gaml.skills.MovingSkill.setLocation(MovingSkill.java:193)
	at msi.gaml.skills.MovingSkill.primMoveRandomly(MovingSkill.java:395)
	at gaml.additions.GamlAdditions$1055.run(GamlAdditions.java:1094)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:243)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:359)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:404)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:404)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:31)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:47)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:29)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:93)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class msi.gama.metamodel.agent.GamlAgent id= 149583221 hashCode= 149583221 toString= fish88; object #2 =class msi.gama.metamodel.agent.GamlAgent id= 149583221 hashCode= 149583221 toString= fish88

	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:426)
	at msi.gama.util.TOrderedHashMap.rehash(TOrderedHashMap.java:138)
	at gnu.trove.impl.hash.THash.compact(THash.java:201)
	at gnu.trove.impl.hash.THash.removeAt(THash.java:272)
	at gnu.trove.impl.hash.TObjectHash.removeAt(TObjectHash.java:104)
	at gnu.trove.map.hash.THashMap.removeAt(THashMap.java:468)
	at msi.gama.util.TOrderedHashMap.removeAt(TOrderedHashMap.java:151)
	at gnu.trove.map.hash.THashMap.remove(THashMap.java:455)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.remove(GamaQuadTree.java:192)
	at msi.gama.metamodel.topology.GamaQuadTree.remove(GamaQuadTree.java:91)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.remove(CompoundSpatialIndex.java:82)
	at msi.gama.metamodel.topology.AbstractTopology.updateAgent(AbstractTopology.java:226)
	at msi.gama.metamodel.agent.MinimalAgent.setLocation(MinimalAgent.java:152)
	at msi.gaml.skills.MovingSkill.setLocation(MovingSkill.java:193)
	at msi.gaml.skills.MovingSkill.primMoveRandomly(MovingSkill.java:395)
	at gaml.additions.GamlAdditions$1055.run(GamlAdditions.java:1094)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:243)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:359)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:404)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:404)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:31)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:47)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:29)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:93)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.ConcurrentModificationException
	at msi.gama.util.TOrderedHashMap$THashIterator.nextIndex(TOrderedHashMap.java:688)
	at msi.gama.util.TOrderedHashMap$THashIterator.hasNext(TOrderedHashMap.java:714)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.split(GamaQuadTree.java:252)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.add(GamaQuadTree.java:205)
	at msi.gama.metamodel.topology.GamaQuadTree.insert(GamaQuadTree.java:76)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.insert(CompoundSpatialIndex.java:72)
	at msi.gama.metamodel.topology.AbstractTopology.updateAgent(AbstractTopology.java:228)
	at msi.gama.metamodel.agent.MinimalAgent.setLocation(MinimalAgent.java:152)
	at msi.gaml.skills.MovingSkill.setLocation(MovingSkill.java:193)
	at msi.gaml.skills.MovingSkill.primMoveRandomly(MovingSkill.java:395)
	at gaml.additions.GamlAdditions$1055.run(GamlAdditions.java:1094)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:243)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:359)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:404)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:404)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:31)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:47)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:29)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:93)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.ConcurrentModificationException
	at msi.gama.util.TOrderedHashMap$THashIterator.nextIndex(TOrderedHashMap.java:688)
	at msi.gama.util.TOrderedHashMap$THashIterator.hasNext(TOrderedHashMap.java:714)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.split(GamaQuadTree.java:252)
	at msi.gama.metamodel.topology.GamaQuadTree$QuadNode.add(GamaQuadTree.java:205)
	at msi.gama.metamodel.topology.GamaQuadTree.insert(GamaQuadTree.java:76)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.insert(CompoundSpatialIndex.java:72)
	at msi.gama.metamodel.topology.AbstractTopology.updateAgent(AbstractTopology.java:228)
	at msi.gama.metamodel.agent.MinimalAgent.setLocation(MinimalAgent.java:152)
	at msi.gaml.skills.MovingSkill.setLocation(MovingSkill.java:193)
	at msi.gaml.skills.MovingSkill.primMoveRandomly(MovingSkill.java:395)
	at gaml.additions.GamlAdditions$1055.run(GamlAdditions.java:1094)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:243)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:93)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:84)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:359)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:276)
	at msi.gama.metamodel.agent.MinimalAgent._step_(MinimalAgent.java:255)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:247)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:404)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:404)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:31)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:47)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:29)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:93)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:97)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
GAMA git and win10

**Comment by AlexisDrogoul** [comment]
Well, this happens sometimes (not only in this model) and it seems to be due to the fact that agents (which are mutable objects) are used as keys in maps. Will try to see if something can be done on this problem, of if we need to move to another collections library, more tolerant towards this kind of "behaviour".

**Comment by hqnghi88** [comment]
Dear Alexis,
Just to be sure about the frequency of "sometimes" ( because i want to play with this model), even if i bypass the "Stop simulation at errors", it happens nearly at each step. Is there any other workaround at this moment?

**Comment by AlexisDrogoul** [comment]
It depends on many things, and some are related to your OS (hash strategies are a bit sensitive). So maybe it happens all the times under Windows :)

I will issue soon a more robust and coherent way of computing hash codes for agents, to see if it can lower the occurence of these annoying exceptions.

**Comment by AlexisDrogoul** [comment]
I've issued a possible fix. Can you test it ? Otherwise, to completely answer your question: this error (not on agents, by the way, but on Strings !) happened to me maybe 3 times in 9 years. So whats why I consider it is occasional ...

**Comment by hqnghi88** [comment]
I turned off the (experimental) parallel mechanism and It works. So I have no more exceptions. I also have no idea about the computational power. I close this issue.

**Comment by AlexisDrogoul** [comment]
Oh yes, sorry. Forgot to add this error can only happen in multi-threaded environments (w. the same hash code being computed by 2 threads). I guess some kind of "concurrentquadtree" will be necessary for most of the multi-threaded models...
