### ISSUE TITLE
NPE in headless

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#2136]
### Steps to reproduce
1. using commit b8262de6b6e3209ca586fcb751ad7d96dea06f07

2. run the gama in openmole 

3.

### Expected behavior
Tell us what should happen (include all relevant expectations)

It should work

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

it raises a NPE:

```
>GAMA building GAML artefacts in 225 ms
Init
java.lang.NullPointerException
	at msi.gama.runtime.HeadlessListener$2.informConsole(HeadlessListener.java:373)
	at msi.gama.runtime.HeadlessListener$2.informConsole(HeadlessListener.java:365)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:79)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5$$anonfun$apply$7.apply(GamaTask.scala:132)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5$$anonfun$apply$7.apply(GamaTask.scala:123)
	at org.openmole.plugin.task.gama.GamaTask$.org$openmole$plugin$task$gama$GamaTask$$withDisposable(GamaTask.scala:82)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:123)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1$$anonfun$apply$5.apply(GamaTask.scala:122)
	at org.openmole.plugin.task.gama.GamaTask$.org$openmole$plugin$task$gama$GamaTask$$withDisposable(GamaTask.scala:82)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:122)
	at org.openmole.plugin.task.gama.GamaTask$$anonfun$process$1.apply(GamaTask.scala:114)
	at org.openmole.plugin.task.external.External$.withWorkDir(External.scala:65)
	at org.openmole.plugin.task.gama.GamaTask.process(GamaTask.scala:114)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:39)
	at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:39)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:92)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:88)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:39)
	at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:88)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:101)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:85)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:115)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:136)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
```

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by romainreuillon** [comment]
Works now, thanks!
