### ISSUE TITLE
Request for separating the displays with the SWT_AWT bridge

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2183]
### Steps to reproduce
1. I'm currently develope a full GAMA on web (screenshot).

2. I'm stuck at the drawing phase of agents as the present displays are based on SWT_AWT (or opengl),

3. It is not possible to create a Fram of RCP on web, and it raises the following exception.

!ENTRY org.eclipse.rap.ui 4 0 2017-04-25 17:17:57.728
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.LinkageError: loader constraint violation: loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously initiated loading for a different type with name "org/eclipse/swt/widgets/Composite")
	at org.eclipse.swt.SWT.error(SWT.java:3708)
	at org.eclipse.swt.SWT.error(SWT.java:3631)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:200)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at msi.gama.lang.gaml.web.editor.BasicWorkbench.createUI(BasicWorkbench.java:51)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously initiated loading for a different type with name "org/eclipse/swt/widgets/Composite"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:273)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:632)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:586)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:548)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.swt.awt.SWT_AWT.new_Frame(SWT_AWT.java:127)
	at ummisco.gama.web2d.swing.SwingControl.createFrame(SwingControl.java:279)
	at ummisco.gama.web2d.swing.SwingControl.populate(SwingControl.java:268)
	at ummisco.gama.web2d.swing.SwingControl.handleSetBounds(SwingControl.java:940)
	at ummisco.gama.web2d.swing.SwingControl.setBounds(SwingControl.java:1124)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:689)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:191)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:973)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:689)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:191)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.custom.SashFormLayout.layout(SashFormLayout.java:131)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:973)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:689)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:191)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:973)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:689)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:191)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:973)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:239)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:973)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:222)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:569)
	at org.eclipse.swt.widgets.Composite$1.run(Composite.java:911)
	at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.add(ProcessActionRunner.java:30)
	at org.eclipse.swt.widgets.Composite.notifyResize(Composite.java:906)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:2588)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:946)
	at org.eclipse.ui.internal.LayoutPart.setBounds(LayoutPart.java:301)
	at org.eclipse.ui.internal.presentations.PresentablePart.setBounds(PresentablePart.java:175)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.layoutContent(PresentablePartFolder.java:128)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.layout(PresentablePartFolder.java:407)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(PresentablePartFolder.java:287)
	at org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRightTabOrder.java:64)
	at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(TabbedStackPresentation.java:479)
	at org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:1262)
	at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1215)
	at org.eclipse.ui.internal.PartStack.showPart(PartStack.java:1614)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:508)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:494)
	at org.eclipse.ui.internal.PerspectiveHelper.addPart(PerspectiveHelper.java:398)
	at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2350)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1073)
	at org.eclipse.ui.internal.WorkbenchPage$20.run(WorkbenchPage.java:3815)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3812)
	at msi.gama.lang.gaml.web.ui.utils.SwtGui.lambda$0(SwtGui.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	... 15 more

### Expected behavior
Tell us what should happen (include all relevant expectations)
Any comment or help about the web-based frame are welcome
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
![untitled](https://cloud.githubusercontent.com/assets/6105384/25380744/844ce790-29db-11e7-823f-89b81fe90818.png)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by agrignard** [comment]
wha! nghi that sounds very promising to have a WebBrowser version!!

**Comment by hqnghi88** [comment]
Dear Alexis,
I use RAP. In AWTDisplayView extends LayeredDisplayView , it create a surfaceComposite which is a SwingControl. And this control is a java.awt.Frame created by SWT_AWT.new_Frame . But in RAP, no Frame is accepted. I am trying with some others composite like Widget, Canvas in RAP but no succes. In addition, I have to get rid of org.eclipse.ui (which is everywhere  application, java2d, gama.ui...) because the RAP have their own ui (org.eclipse.rap.ui) which conflict with most of org.eclipse.ui.
SO, the request is to propose (modify) a structure of displayable things which is indepent with graphical engine (swt, awt, opengl, webgl) and they will find the suitable engine for the environment (rcp, rap).
May be i missunderstood something, you tell me.
Thanks.

**Comment by AlexisDrogoul** [comment]
I would say that the best solution would be create, in your own package, a subclass of LayeredDisplayView that would be "pure SWT" (for example a Canvas where you would transform Java2D images into SWT Images before displaying them). The only method required to create should be `protected abstract Composite createSurfaceComposite(Composite parent);`. And you have to ensure somewhere that, when in the RAP environment, a display description is available (look at the plugin.xml for `java2D` or `opengl`).

**Comment by AlexisDrogoul** [comment]
I have added a "pure" abstract SWT Display view (`SWTDisplayView`), independent from OpenGL, from which you can derive your class. Do you see how to proceed ?

**Comment by hqnghi88** [comment]
Thank you Alexis, i think i know how to proceed.

**Comment by hqnghi88** [comment]
I was, actually, implemented it. 
I close this issue as it was fullfilled.
