### ISSUE TITLE
A genetic Batch model throw exception in headless mode

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2262]
### Steps to reproduce
1.batch_headless.gaml

```
model HB

global
{
 	
	float weight_profit <- 0.7 parameter:true;
	float weight_risk <-0.6 parameter:true;
	float weight_implementation <-0.7 parameter:true;
	float weight_suitability <-0.7 parameter:true;
	float weight_neighborhood <-0.0 parameter:true;
	float weight_transition_tax <- 0.9 parameter: true;
	float weight_lu_tax <- 0.8 parameter: true;
	float probability_changing <- 1.0 parameter: true;
	float probability_risk <- 1.0 parameter: true;
	float kappa_sim<-0.0;
	
}
experiment Calibration type: batch keep_seed: true repeat: 1 until: cycle>2 {
	parameter weight_profit  var:weight_profit min: 0.0 max: 1.0 step: 0.1;
	parameter weight_risk  var:weight_risk min: 0.0 max: 1.0 step: 0.1;
	parameter weight_implementation  var:weight_implementation min: 0.0 max: 1.0 step: 0.1;
	parameter weight_suitability  var:weight_suitability min: 0.0 max: 1.0 step: 0.1;
	parameter weight_transition_tax  var:weight_transition_tax min: 0.0 max: 1.0 step: 0.1;
	parameter weight_lu_tax  var:weight_lu_tax min: 0.0 max: 1.0 step: 0.1;
	parameter probability_changing var:probability_changing min: 0.0 max: 1.0 step: 0.1;



	method genetic pop_dim: 10 crossover_prob: 0.7 mutation_prob: 0.1 improve_sol: true stochastic_sel: false
	nb_prelim_gen: 1 max_gen: 20  maximize: kappa_sim ;
	
}
```

2. test.xml
```
    <?xml version="1.0" encoding="UTF-8"?>
    <Simulation id="2" driver="msi.gama.headless.runtime.GamaSimulator" sourcePath="batch_headless.gaml" finalstep="3" experiment="Calibration">
    <Parameters>
    </Parameters>
    <Outputs>
    </Outputs>
    </Simulation>
```

### Expected behavior
Tell us what should happen (include all relevant expectations)
the batch explore all params combinations
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
I've got this exception after 1 simulation

```
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at msi.gama.kernel.batch.InitializationUniform.initializePop(InitializationUniform.java:52)
	at msi.gama.kernel.batch.GeneticAlgorithm.findBestSolution(GeneticAlgorithm.java:201)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:112)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:157)
	at msi.gama.headless.core.Experiment.step(Experiment.java:93)
	at msi.gama.headless.job.ExperimentJob.doStep(ExperimentJob.java:293)
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:272)
	at msi.gama.headless.job.ExperimentJob.playAndDispose(ExperimentJob.java:247)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:206)
```

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
gama git

**Comment by AlexisDrogoul** [comment]
Does the same model run in GUI ?

I dont really understand what it is supposed to do, but I find it odd that different parameters point to the same variable:

```
	parameter probability_changing var:probability_changing min: 0.0 max: 1.0 step: 0.1;
	parameter probability_risk var:probability_changing min: 0.0 max: 1.0 step: 0.1;
```

or 


```
	parameter weight_neighborhood  var:weight_transition_tax min: 0.0 max: 1.0 step: 0.1;
	parameter weight_transition_tax  var:weight_transition_tax min: 0.0 max: 1.0 step: 0.1;
```

**Comment by hqnghi88** [comment]
Dear Alexis,
Yes, batch run in GUI (it's model from JTD) i just removed all other code.

**Comment by hqnghi88** [comment]
I updated the gaml. Thanks

**Comment by AlexisDrogoul** [comment]
I just posted a possible solution. minValue and maxValue of ExperimentParameter were not always computed at the beginning, leading to this strange bug. I computed them in the constructor taking the description, and I hope it's gonna fix your problem.

**Comment by hqnghi88** [comment]
Yes, it satisfied for me. It was not allwasy computed as i found. So their computation in constructor fixed this issue.
Thanks.
