### ISSUE TITLE
fullscreen by pressing esc is broken

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2290]
On the latest release the fullscreen feature is kind of f#?%// up. 

With n display when you press esc it always show the first one on fullscreen mode

When defining a fullscreen with the facet fullscreen:0 then there is no way to go out of the full screen mode...

**Comment by AlexisDrogoul** [comment]
Check your preferences. The right combination on macOS should be:

![monosnap 2017-11-17 00-04-04](https://user-images.githubusercontent.com/579256/32920775-fa2f809e-cb2a-11e7-9442-3c18e1a6b20e.png)

I dont know for Windows or Linux.

**Comment by agrignard** [comment]
once again no way to make it by default? I did an update on the demo machine and all my demo are dead...

**Comment by agrignard** [comment]
This is the settings I have and yes it is reproductible at least on my machine on mac os X el Captan and on another windows 10.

To reproduce it just put two display and one with fullscreen:whatever and you will get stuck on the fullscreen mode without any way to quit the application

**Comment by AlexisDrogoul** [comment]
It is the default.

**Comment by AlexisDrogoul** [comment]
In that case, please make the effort of putting an informative title and the information of OSes, etc. you are using when entering an issue. Fullscreen mode with one screen is perfectly functional, but I have no way to test it with two screens.

**Comment by agrignard** [comment]
Ok so to facilitate the debugging it doesn't happen always...

I m digging on it. it seems to happen when there is more than 2 display defined (and maybe with a display that inherit from a virtual one...

I am using only one screen

**Comment by agrignard** [comment]
It happens often on this specific model
https://github.com/mitmedialab/CityScope_GAMA/blob/master/CPG_CityScope_GAMA/models/CityScope_Volpe_demo.gaml

**Comment by AlexisDrogoul** [comment]
2 displays with one fullscreen: 0 works for me. Only gives the impression of being "stuck" because the fullscreen one does not have the initial keyboard focus (I might need to force it), but clicking on it and pressing ESC works.

**Comment by agrignard** [comment]
Doesn't work for me either fullscreen: 0 or 1 I am stuck in the fullscreen mode (still only with one screen)

**Comment by hqnghi88** [comment]
i confirm that it stuck on windows, even with 1 screen, but it's hard to reproduce. and sometime it can stop by esc after dragging the display

**Comment by hqnghi88** [comment]
I used eclipse Version: Mars.2 Release (4.5.2), xtext 2.9.1, jdk8 .121, gama github in eclipse. When i run model of Arnaud (CityScopeVolpeDemo), i've got this exception in eclipse

java.lang.NullPointerException
	at gaml.additions.GamlAdditions$201.run(GamlAdditions.java:282)
	at gaml.additions.GamlAdditions$201.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:79)
	at msi.gaml.expressions.NAryOperator.value(NAryOperator.java:81)
	at msi.gaml.statements.draw.DrawingData.lambda$4(DrawingData.java:158)
	at msi.gaml.statements.draw.DrawingData$ExpressionAttribute.value(DrawingData.java:87)
	at msi.gaml.statements.draw.DrawingData$Attribute.refresh(DrawingData.java:58)
	at msi.gaml.statements.draw.DrawingData.computeAttributes(DrawingData.java:184)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:302)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:380)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:88)
	at msi.gama.outputs.layers.SpeciesLayer.privateDrawDisplay(SpeciesLayer.java:59)
	at msi.gama.outputs.layers.AbstractLayer.drawDisplay(AbstractLayer.java:122)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:180)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:170)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$2(LayeredDisplayView.java:689)
	at java.lang.Thread.run(Thread.java:745)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:87)
	at msi.gaml.expressions.NAryOperator.value(NAryOperator.java:81)
	at msi.gaml.statements.draw.DrawingData.lambda$4(DrawingData.java:158)
	at msi.gaml.statements.draw.DrawingData$ExpressionAttribute.value(DrawingData.java:87)
	at msi.gaml.statements.draw.DrawingData$Attribute.refresh(DrawingData.java:58)
	at msi.gaml.statements.draw.DrawingData.computeAttributes(DrawingData.java:184)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:302)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:380)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:88)
	at msi.gama.outputs.layers.SpeciesLayer.privateDrawDisplay(SpeciesLayer.java:59)
	at msi.gama.outputs.layers.AbstractLayer.drawDisplay(AbstractLayer.java:122)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:180)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:170)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$2(LayeredDisplayView.java:689)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at gaml.additions.GamlAdditions$201.run(GamlAdditions.java:282)
	at gaml.additions.GamlAdditions$201.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:79)
	... 28 more

**Comment by agrignard** [comment]
Same error for me in Eclipse 

Any update on this issue, is there any way I can help on that?

Actually do we know more or less what has been modified/changed between the time it was working and now?

**Comment by AlexisDrogoul** [comment]
The error is not surprising as, in the model, the `color` of many `amenity` agents is equal to `nil`. So expressions like `color.red`, etc. cannot work properly. If you show the errors occurring in outputs, they will be displayed. 

Regarding the fullscreen problem, my guess is that the keyboard focus is not provided to the right component on screen when fullscreen is launched.

**Comment by agrignard** [comment]
Oups sorry for that, i remove the error that indeed was not at all link with the fullscreen problem.

For the keyboard focus does something change regarding to this this last months?

**Comment by agrignard** [comment]
The aforementioned commit didn't fix the issue but the behavior is a bit different now so maybe we are getting closer to fix it. 

So if I try to summurize when I do:

````
display CityScope type:opengl {}	
        	
display CityScopeTable  type:opengl  fullscreen:1 {}

``` 
When I run the simulation my mouse is then "stucked" in the fullsceen mode of the CityScopeTable mode (I cannot click anywhere and get the "alert sound" as soon as I click anywhere).

As soon as I press esc then the fullscreen:1 is disable and I m not stucked anymore

Maybe it's just a question to give back the focus to the main windows once the fullscreen window is set?

**Comment by agrignard** [comment]
Unfortunately I thought that Oxygen might slove it but it is still happening. maybe (I hope so) it is related to this issue   #2323.

@hqnghi88  Any chance to take a look a bit on that?

**Comment by hqnghi88** [comment]
i will try to see on an mac. Can you try with this https://github.com/gama-platform/gama/releases/tag/latest

**Comment by benoitgaudou** [comment]
Hi 
here what I get:

![img-0518](https://user-images.githubusercontent.com/1555274/37665057-bdb2be40-2c5c-11e8-9ab8-0532b2febb4b.JPG)

@agrignard is it what you are expected.
Not that I get it, with the current release oxygen.
I took the model Features / 3D Vizualisation / Building Elevation.gaml and I add to the road_traffic_multi_layer experiment another display:
```
	output
	{
		display city_display type: opengl
		{
			species road aspect: base;
			species building aspect: base position: { 0, 0, 0.25 };
			species people aspect: base position: { 0, 0, 0.5 };
		}
		
		display city_displayFS type: opengl fullscreen: 1
		{
			species people aspect: base position: { 0, 0, 0.5 };
		}
	}
}
```

Important, if you specify fullscreen: 1, you have to launch the model from the screen corresponding to the principary screen, otherwise I was not able to access GAMA anymore and had to kill it.

**Comment by agrignard** [comment]
Might be link with issue #2386

**Comment by agrignard** [comment]
@AlexisDrogoul and/or @hqnghi88 with all the big change done this last weeks any chance to get rid of this bug? I am wandering how I can help here but It feels a bit out of my scope. The reason why I am "a bit" insisting here is that there is many improvement on GAMA made this last month that I cannot show/use in the demo space area of the lab because of this bug. If we could get rid of this guy for the 1.8 release that would be great!

I tested it recently (like 2 weeks ago) with the last release and it was still occuring.

**Comment by AlexisDrogoul** [comment]
I thought @benoitgaudou in his previous comment showed it running already, no ? I never use multiple screens so I can't test it on my side.

**Comment by hqnghi88** [comment]
I tested the solution of benoit on win with git based, it did not work well. Gama was not hang as not reponding, but it seem the focus is alway on fullscreened display: i can manipulate 3d environment in right display (extended display), but i cant click on any element on main display (left)
![image](https://user-images.githubusercontent.com/6105384/43238614-05eba90e-90b9-11e8-9947-14c0809002b6.png)

**Comment by AlexisDrogoul** [comment]
@hqnghi88 ok. But at least it displays something :) And pressing ESC brings it back to normal ?

**Comment by hqnghi88** [comment]
Yes,  The esc works, i can quit fullscreen and then can click again.

**Comment by AlexisDrogoul** [comment]
One of the issues included here (comment from  @agrignard on 17 Nov 2017) concerned the freezing with **only one screen**. and a display set to fullscreen. **I can't reproduce it on neither macOS nor Windows**. The two displays (I took Benoit's model) open, I can have access to all the elements in the fullscreen one (CMD-T, CMD-K, CMD-L, the menu and ESC), minimise it, no problem. So we can already eliminate this if you confirm the same behaviour.

**Comment by hqnghi88** [comment]
I can confirm that there is no hang, keys , popup menu work, but as i said, i cant click on any on the left . So yes we should have other concret issue

**Comment by agrignard** [comment]
IMPORTANT NOTE: YOU NEED TO CONNECT A SECONDARY MONITOR (OR PROJECTOR) TO GET THE BUG)

Ok so in my case I still have this issue.

i cannot test on the last release (see issue #2477) 

the version I am running is this one:
GAMA1.8_Mac_64_07.02.18_9d27238

A simple way to reproduce it (I insist you need 2 physical screen)

Connect a video projector (or a second screen) in my case on the hdmi port of the macbook pro to your computer and run this model from the main screen. 

````

model multiscreen

global {
 init{
 	create people number:100;
 }
}

species people{
	aspect base{
		draw circle(1);
	}
}
experiment multiscreen type: gui{
	output {		
		
        display CityScope type:opengl{
        	species people aspect: base;
        }
		display CityScopeTable   type:opengl fullscreen:1 {
			species people aspect: base;
		}
	}
}

````

**Comment by sriramab** [comment]
I just tried this model, and it gets stuck, esc does not work. all mouse interactions work. I have two monitors on mac siera 10.12.6
I could drag gama to the second monitor, but the interface is not responding, I could only force quit

**Comment by hqnghi88** [comment]
I retried Arnauds model, i have same behavior as before: focus is on screen 2 with mouse and key manipulation, Gama on screen 1 (main) is disable, no click no keys. BUT it is not hang or force quit, the esc works.

**Comment by hqnghi88** [comment]
I used TV hdmi as 2nd screen.

**Comment by sriramab** [comment]
Yes, Mouse interaction is working on the floating full screen display but not on the GAMA GUI. If you see the screenshot, in the background there is still some GAMA GUI, I could drag to second screen. But this GAMA GUI is not responsive.

![screen shot 2018-07-26 at 12 44 18 pm](https://user-images.githubusercontent.com/12668606/43258093-ee82cc66-90d1-11e8-89fa-46c4c164d169.jpeg)

**Comment by AlexisDrogoul** [comment]
OK. It means all the input is taken by the fullscreen shell. And since the menu is working, can you toggle the toolbar ? Does it appear ?

**Comment by sriramab** [comment]
All the toggles work. but the zoom in zoom out bar is almost invisible at the rock bottom. 
I think this model does not have behavior to check CMD+P, also CMD+P does not show any simulation controls

**Comment by AlexisDrogoul** [comment]
CMD-P is general to all GAMA ("P"lay / "P"ause the simulation). And when you have the toolbar, can you kill the experiment (controls on the left) ? 

BTW, Why do you have a floating screen ? Fullscreen is supposed to be fullscreen, not floating fullscreen.

**Comment by sriramab** [comment]
i added wander behavior and CMD-P works. 
One the left I have General, Camera, OpneGL, KeyStone, Layer-Species
How Do i kill? I don't see how to kill the experiment.

I say floating because my monitor is 1920x1080, and the fullscreen display does not cover the whole monitor.

**Comment by AlexisDrogoul** [comment]
When you toggle the toolbar, you should see (on the bottom left) the simulation controls (while on the right, you have the zoom, etc.). One of them is the button to kill experiments.

**Comment by sriramab** [comment]
No, I don't see them. It is blank. On the same bar to the right right I have a set of zoom, refresh, camera and population buttons

**Comment by AlexisDrogoul** [comment]
And ESC does not work ?

**Comment by sriramab** [comment]
No, it does not. only force quit is the way out.

**Comment by sriramab** [comment]
![screen shot 2018-07-26 at 1 19 45 pm](https://user-images.githubusercontent.com/12668606/43259506-bea38ada-90d6-11e8-9267-1f3c8915d7b6.jpeg)


please see, the toolbar has not simulation/experiment controls

**Comment by benoitgaudou** [comment]
Hi,

I just tested with my GAMA Git (from Eclipse) up-to-date.
With a TV screen pluged on my HDMI port.

When I run the model of Arnaud (with a reflex of agent move).
I have the fullscreen. But the escape does not work . CMD+P does not work
either.
I can have the contextual menu.

BUT when I click on another application, lets say Eclipse  and I move back
to GAMA and the full screen, CMD+P and ESC work.

Another point, on fullscreen, I can have the overlay and the left side
control. (but they do not fit exactly to my screen, I do not know whether
this is an issue with my screen configuration ...)
But the bottom toolbar appears empty (I can observe a small translation of
the simulation screen when I activate it, but nothing inside).

Cheers

Benoit

2018-07-26 13:18 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by sriramab** [comment]
I saw your message in the beginning about preferences, i think I have exactly like that. I can check again. but for that, i have to force-quit

**Comment by sriramab** [comment]
![pref](https://user-images.githubusercontent.com/12668606/43260264-37a557cc-90d9-11e8-854a-55d82fd88730.png)

**Comment by AlexisDrogoul** [comment]
OK. We need to summarise here because this thread is a real mess and I don't know anymore what we are talking about. I let one of you do it, and the best would probably be to open a new issue focused on a repeatable use case and mentioning the things that work and the ones that do not (keyboard combinations that work and don't, like ESC or CMD-P, mouse events that work and don't, like contextual menu, dragging, camera control, other interactions, like switching back and forth GAMA, etc.). Just in order to have a clear view on **one** use-case (and not several bits of different use-cases). Thanks !

**Comment by agrignard** [comment]
I am even lost on my own issue here.

I can create another one to restart from scratch , for me it's pretty clear I cannot use GAMA with two different displays (main display in non fullscreen mode, secondary in fullscreen mode) as the mouse is stucked in the fullscreen display

**Comment by AlexisDrogoul** [comment]
@agrignard yes please. And show the scenarios also when you toggle the preference ""Disable the OS menu bar when a display is full-screen"" on an off.
