### ISSUE TITLE
GAMA hangs in openmole

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#2308]
Hello,

gama seems to call Thread.sleep somewhere in its code. It make OpenMOLE hang when we run a model. Here is the stack trace:

```
"scala-execution-context-global-76" #76 daemon prio=5 os_prio=0 tid=0x00007f1548018800 nid=0x6c1c waiting on condition [0x00007f159029a000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.<clinit>(BuiltinGlobalScopeProvider.java:262)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	- locked <0x000000008dd74288> (a java.lang.Class for com.google.inject.internal.InternalInjectorCreator)
```

cheers,
Romain

PS: not sure if it is related, but just in case, there is also a another error when loading the plugins 
```
Exception in thread "Thread-3" java.lang.NullPointerException
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$1(GamaBundleLoader.java:109)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:179)
	at one.util.streamex.AbstractStreamEx.toSet(AbstractStreamEx.java:1209)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:109)
	at msi.gama.common.Activator.lambda$0(Activator.java:26)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlexisDrogoul** [comment]
It's probably related. However, this error indicates that one of the bundles is null (or that its name is null). Which bundles / extensions to GAMA are you loading ?

**Comment by romainreuillon** [comment]
The openmole gama plugin are recompiled against the latest gama version every day. I just tried this again and it seems to work.

**Comment by AlexisDrogoul** [comment]
I guess it is ok by now ? So let's close the issue.
