### ISSUE TITLE
Import a stored online model (import with an url)

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2319]
### Steps to reproduce
1. I'm working with gama cloud which have now the authentication and access to GDrive files.

2. I tried with validation a single model, it seems to be fine. But the big problem is the importation others models.

3. I knows it is too complicate to have the importation of an online model where every resources must have access priviledges.

### Expected behavior
But could we have a vision on this challenge where it will be solve one day?
### Actual behavior

import "https://raw.githubusercontent.com/gama-platform/gama/master/msi.gama.models/models/Toy%20Models/Ants%20(Foraging%20and%20Sorting)/models/Ant%20Foraging%20(Complex).gaml"

Errors detected (in Ant Foraging (Complex).gaml)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by hqnghi88** [comment]
Dear Alexis,
I just tried with absolute path and it works. i dont it is a side effect or it was enhanced.
import "file://C:/eclipseoxy/Circle.gaml"
But the http/s still not work , it still has green button but there is an exception in eclipse console, seem that the validation is broken

GAMA Caught a workbench message : An internal error occurred during: "Xtext validation".
java.lang.NullPointerException
	at msi.gama.lang.gaml.parsing.GamlSyntacticConverter.buildSyntacticContents(GamlSyntacticConverter.java:152)
	at msi.gama.lang.gaml.resource.GamlResourceServices.buildSyntacticContents(GamlResourceServices.java:244)
	at msi.gama.lang.gaml.resource.GamlResource.getSyntacticContents(GamlResource.java:88)
	at msi.gama.lang.gaml.resource.GamlResource.lambda$0(GamlResource.java:94)
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029)
	at com.google.common.collect.Maps$8.apply(Maps.java:2040)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.MultitransformedIterator.next(MultitransformedIterator.java:66)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:437)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:803)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:274)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:229)
	at msi.gaml.factories.ModelAssembler.assemble(ModelAssembler.java:69)
	at msi.gaml.factories.ModelFactory.createModelDescription(ModelFactory.java:50)
	at msi.gama.lang.gaml.resource.GamlResource.buildModelDescription(GamlResource.java:118)
	at msi.gama.lang.gaml.resource.GamlResource.buildCompleteDescription(GamlResource.java:153)
	at msi.gama.lang.gaml.resource.GamlResource.validate(GamlResource.java:176)
	at msi.gama.lang.gaml.validation.GamlResourceValidator.validate(GamlResourceValidator.java:66)
	at msi.gama.lang.gaml.ui.editor.GamlEditor$2.lambda$0(GamlEditor.java:401)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at msi.gama.lang.gaml.ui.editor.GamlEditor$2.createIssues(GamlEditor.java:398)
	at msi.gama.lang.gaml.ui.editor.GamlEditor$2.run(GamlEditor.java:392)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by AlexisDrogoul** [comment]
Absolute paths is an enhancement, and http: or https: protocols are not implemented, so its normal its not working. It shouldn't however raise an exception. I'll look into it.
