### ISSUE TITLE
World inspection broken

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2332]
### Steps to reproduce
1. Run  Features/3D Visualisation/3D Camera and trajectories.gaml or Buil-In Shapes

2. Right click on the wolrd

3.

### Expected behavior
Normal behavior (select world and inspect it)

### Actual behavior
Visualization is frozen in term of selection in my case with the error message:

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

```
### System and version 
Last version in Mars

**Comment by agrignard** [comment]
Here is a minimal model to reproduce it

```
model LLL

/* Insert your model definition here */

global{
	geometry shape<-rectangle(10#km,5#km);
	init{
		loop i from:0 to:3{
			loop j from:0 to:1{
				create area{
					level<-1;
					size<-2.5#km;
					location<-{size/2 + i * size,size/2 + j * size};	
				}
			}
		}
	}	
}


species area{
	int level;
	float size;
	aspect base{
		draw square(size) color:#black empty:true;
	}
}



experiment main type: gui {
	output {
		display map type:opengl{
			species area aspect:base;
		}
		 
	}
}
```

It seems to come from the fact that area is empty. If you put empty to false then it's ok.

**Comment by agrignard** [comment]
dont' know if it can help in any case I get some time that kind of error:

```
java.lang.NullPointerException
	at gaml.additions.GamlAdditions$89.run(GamlAdditions.java:213)
	at gaml.additions.GamlAdditions$89.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:78)
	at msi.gaml.expressions.NAryOperator.value(NAryOperator.java:81)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:82)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:302)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:380)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:85)
	at msi.gama.outputs.layers.SpeciesLayer.privateDrawDisplay(SpeciesLayer.java:59)
	at msi.gama.outputs.layers.AbstractLayer.drawDisplay(AbstractLayer.java:91)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:180)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:170)
	at msi.gama.outputs.LayeredDisplayOutput.setPaused(LayeredDisplayOutput.java:539)
	at ummisco.gama.ui.views.displays.LayeredDisplayDecorator$1.perspectiveActivated(LayeredDisplayDecorator.java:187)
	at org.eclipse.ui.internal.PerspectiveListenerList$1.run(PerspectiveListenerList.java:75)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.PerspectiveListenerList.fireEvent(PerspectiveListenerList.java:58)
	at org.eclipse.ui.internal.PerspectiveListenerList.firePerspectiveActivated(PerspectiveListenerList.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.firePerspectiveActivated(WorkbenchWindow.java:1719)
	at org.eclipse.ui.internal.WorkbenchPage$4.handleEvent(WorkbenchPage.java:3000)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4781)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.advanced.impl.PerspectiveStackImpl.setSelectedElement(PerspectiveStackImpl.java:135)
	at org.eclipse.e4.ui.model.application.ui.advanced.impl.PerspectiveStackImpl.setSelectedElement(PerspectiveStackImpl.java:1)
	at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:4034)
	at msi.gama.application.workbench.PerspectiveHelper.lambda$0(PerspectiveHelper.java:113)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4781)
	at msi.gama.application.workbench.PerspectiveHelper.openPerspective(PerspectiveHelper.java:128)
	at ummisco.gama.ui.utils.SwtGui.openSimulationPerspective(SwtGui.java:257)
	at ummisco.gama.ui.utils.SwtGui.openSimulationPerspective(SwtGui.java:248)
	at ummisco.gama.ui.utils.SwtGui.confirmClose(SwtGui.java:104)
	at msi.gama.runtime.GAMA.runGuiExperiment(GAMA.java:80)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runModel(ModelRunner.java:176)
	at msi.gama.lang.gaml.ui.editor.toolbar.OpenExperimentSelectionListener.widgetSelected(OpenExperimentSelectionListener.java:64)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at ummisco.gama.ui.controls.FlatButton.doButtonUp(FlatButton.java:144)
	at ummisco.gama.ui.controls.FlatButton.handleEvent(FlatButton.java:105)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)


```
