### ISSUE TITLE
Problem installing Gama 1.7

### ISSUE THREAD

**Issue by bigaro** [gama-platform/gama#2336]
Hi there. I am new with Eclipse and gama. I am trying to install gama 1.7 in my Mac (iOS High Sierra) to explore how this program works for ABM and I followed all the steps to get the right java version (JDK 1.8) installed etc. But I am not able to open the program. I click on the gama app and I choose a workspace to store my models, settings, etc. but then, it gets stuck loading the program and I always have to force quit.
I tried to install GIT and open from Eclipse but I was not successful either, the Error log displaying is attached below.
Any tip/suggestion?
Many thanks in advance.

The Error log says this:
Java Model Exception: Java Model Status [simtools.graphlayout.feature does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:1850)
	at org.eclipse.pde.launching.PDESourcePathProvider.addBinaryPackageFragmentRoots(PDESourcePathProvider.java:133)
	at org.eclipse.pde.launching.PDESourcePathProvider.resolveClasspath(PDESourcePathProvider.java:109)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:65)
	at org.eclipse.jdt.launching.JavaRuntime.resolveSourceLookupPath(JavaRuntime.java:838)
	at org.eclipse.jdt.launching.sourcelookup.containers.JavaSourcePathComputer.computeSourceContainers(JavaSourcePathComputer.java:58)
	at org.eclipse.debug.internal.core.sourcelookup.SourcePathComputer.computeSourceContainers(SourcePathComputer.java:71)
	at org.eclipse.debug.core.sourcelookup.containers.DefaultSourceContainer.createSourceContainers(DefaultSourceContainer.java:117)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.getSourceContainers(CompositeSourceContainer.java:133)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.findSourceElements(CompositeSourceContainer.java:48)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupParticipant.findSourceElements(AbstractSourceLookupParticipant.java:70)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:142)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:505)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:785)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupDirector.getSourceElement(PDESourceLookupDirector.java:75)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.doSourceLookup(JavaDebugUtils.java:390)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveSourceElement(JavaDebugUtils.java:384)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveSourceElement(JavaDebugUtils.java:351)
	at org.eclipse.jdt.internal.debug.ui.console.JavaStackTraceHyperlink$1.run(JavaStackTraceHyperlink.java:110)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by benoitgaudou** [comment]
Hi,
The release version of GAMA has some troubles on Mac, due to some unexpected modification on Java. We are currently working on it to deal with this issue.
It is not the ideal solution, but you can try the following version that we are currently testing (a kind of alpha version) and that should be fix this issue: https://github.com/gama-platform/gama/releases/tag/oxygenCI 

For you issue with the Eclipse version of GAMA, please check that you have the project: simtools.graphlayout.feature in your workspace (it seems to be missing).

Benoit

**Comment by bigaro** [comment]
Many thanks Benoit for the prompt response!!!
This version worked just great!!
Looking forward to further explore this very nice program!!!
Best Regards,
Beatriz


Dr. Beatriz Martínez López, DVM, MPVM, PhD.
Associate Professor
Director of the Center for Animal Disease Modeling and Surveillance (CADMS)
Department of Medicine and Epidemiology
School of Veterinary Medicine
University of California
One Shields Avenue, 95616 Davis, CA

Office: Tupper Hall 2415A
Phone: +1 530 752 7675
Fax: +1 530 752 1618
Email: beamartinezlopez@ucdavis.edu<mailto:beamartinezlopez@ucdavis.edu>
Website: http://www.vetmed.ucdavis.edu/cadms
Want to support our work? Donate Now!: https://give.ucdavis.edu/VETM/V435UGF
