### ISSUE TITLE
Exception in the console in the model MODAVI.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2357]
### Steps to reproduce
1. Run the model Toy models / Multi-level Analysis.gaml

2. Step by step, nothing happens in the eclipse console

3. When the model is run, an exception appears in the eclipse console (without any visible effect on the simulation)

### Expected behavior
no exception.

### Actual behavior
The following exception appears:
```
java.lang.Boolean cannot be cast to java.awt.geom.Rectangle2D
Cannot evaluate posVector as the target agent is nil
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:72)
	at msi.gaml.operators.System.opGetValue(System.java:182)
	at gaml.additions.GamlAdditions$797.run(GamlAdditions.java:860)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:77)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:75)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:105)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:76)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:75)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:82)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:302)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:356)
	at msi.gaml.statements.LoopStatement$Bounded.runIn(LoopStatement.java:411)
	at msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:348)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:385)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:85)
	at msi.gama.outputs.layers.SpeciesLayer.privateDrawDisplay(SpeciesLayer.java:59)
	at msi.gama.outputs.layers.AbstractLayer.drawDisplay(AbstractLayer.java:91)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:180)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:170)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:285)
	at java.lang.Thread.run(Thread.java:748)
Cannot evaluate posVector as the target agent is nil
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:72)
	at msi.gaml.operators.System.opGetValue(System.java:182)
	at gaml.additions.GamlAdditions$797.run(GamlAdditions.java:860)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:77)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:75)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:105)
	at msi.gaml.expressions.ListExpression.value(ListExpression.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:76)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:75)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:82)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:302)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:356)
	at msi.gaml.statements.LoopStatement$Bounded.runIn(LoopStatement.java:411)
	at msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:348)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:385)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:85)
	at msi.gama.outputs.layers.SpeciesLayer.privateDrawDisplay(SpeciesLayer.java:59)
	at msi.gama.outputs.layers.AbstractLayer.drawDisplay(AbstractLayer.java:91)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:180)
	at ummisco.gama.opengl.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:170)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:285)
	at java.lang.Thread.run(Thread.java:748)
```

### System and version 
MOCOSX GAMA Git (Mars & Oxygen)

**Comment by hqnghi88** [comment]
Dear Benoit,
Such kind of issue i have no idea how to fix. It mainly relate with the mechanism of drawing things. If you  check in preference, show errors thrown in displays and outputs , its will display exception in gama, not in eclipse console. Even in display block with a validation of nil/dead it still occurs. UNLESS, we synchronize the computation underneath with the things shown. 
@AlexisDrogoul Do you have any idea?
