### ISSUE TITLE
UDP connection error: send message get a Socket close message

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2365]
### Steps to reproduce
1. run on two GAMA (run from the same eclipse), the 2 models UDP Client Example.gaml and UDP Server Example.gaml.

### Expected behavior
The client agent is supposed to send a message and the server to receive it.

### Actual behavior
When the client agent try to send a message, I get in Eclipse console the following exception:
```
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.send(DatagramSocket.java:658)
	at ummisco.gama.network.udp.UDPConnector.sendToServer(UDPConnector.java:203)
	at ummisco.gama.network.udp.UDPConnector.send(UDPConnector.java:216)
	at ummisco.gama.network.skills.NetworkSkill.effectiveSend(NetworkSkill.java:220)
	at msi.gama.extensions.messaging.MessagingSkill.primSendMessage(MessagingSkill.java:66)
	at gaml.additions.GamlAdditions$1117.run(GamlAdditions.java:1182)
	at gaml.additions.GamlAdditions$1117.run(GamlAdditions.java:1)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:249)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:100)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:91)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:380)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:278)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:249)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:426)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:459)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:450)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:426)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:179)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:154)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:176)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:171)
	at msi.gama.runtime.ExecutionScope.lambda$2(ExecutionScope.java:427)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:459)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:427)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:94)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:278)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:225)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:249)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### System and version 
MACOSX, GAMA Git MArs

**Comment by benoitgaudou** [comment]
I still have the same issue on closed socket.
I was wondering wether it is an issue of port or network access right allowance...
Benoit

**Comment by hqnghi88** [comment]
Did you give access to gama/java/eclipse in Firewall?

**Comment by AlexisDrogoul** [comment]
Moved to meta-issue #2449
