### ISSUE TITLE
Plugin Rjava : kills GAMA when something wrong happens

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2369]
### Steps to reproduce
1. Install the RJava plugin in the 1.8 preRelease.

2. run the model associated to the RJava library.
(without having properly set the path to R in the preferences)

### Expected behavior
It works, or display an Exception that R cannot be found ... 

### Actual behavior
GAMA is killed ! 
And the following message appears:
```
java.lang.UnsatisfiedLinkError: no jri in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.rosuda.JRI.Rengine.<clinit>(Rengine.java:19)
	at ummisco.gaml.extensions.rjava.skill.RSkill.Reval(RSkill.java:318)
	at ummisco.gaml.extensions.rjava.skill.RSkill.primREval(RSkill.java:138)
	at gaml.additions.GamlAdditions$2.run(GamlAdditions.java:81)
	at msi.gaml.statements.PrimitiveStatement.privateExecuteIn(PrimitiveStatement.java:91)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:385)
	at msi.gaml.expressions.PrimitiveOperator.value(PrimitiveOperator.java:75)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:71)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:112)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:238)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:293)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:443)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:469)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:459)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:443)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:357)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:270)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:286)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:241)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:443)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:469)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:459)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:443)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:161)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:306)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:476)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:90)
	at java.lang.Thread.run(Thread.java:748)
dhcp-5-0-30:MacOS ben$ 
```

### System and version 
MACOSX, GAMA 1.8 preRelease, with RJava plugin

**Comment by hqnghi88** [comment]
Hi, it should be fixed in experimental. Please uninstall and re install it from oxygen updatesite
