### ISSUE TITLE
Absolute path detected in external folder are duplicated and cannot be commented

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2470]
### Steps to reproduce
1. I  tried to change a file declaration to use absolute path.

2.  It link is created in external folder, but it is duplicated (or triple...)

3. And even i cannot comment that declaration . When i use Ctrl+/ to comment that line, Gama hang, and no exception in eclipse

### Expected behavior
welll...

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
![image](https://user-images.githubusercontent.com/6105384/43046931-53f66b8c-8dfa-11e8-872c-0a77e64a0be4.png)

### System and version 
Gama git, win OS

**Comment by AlexisDrogoul** [comment]
Works fine for me now with the latest commit. Can you test it ?

**Comment by hqnghi88** [comment]
I still have duplicates, I can commented an external file. 


But now, sometime i has this when i copy 
`` "New Model2 ``  and paste when selecting the quote
![image](https://user-images.githubusercontent.com/6105384/43073763-ee32cba0-8ea4-11e8-83b6-f0476f02e758.png)


java.nio.file.InvalidPathException: Illegal char <"> at index 4: D:\\"New Model2.gaml
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.fetchFileInfo(DosHandler.java:39)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.fetchFileInfo(LocalFileNativesManager.java:62)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:159)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:257)
	at ummisco.gama.ui.commands.FileOpener.getURI(FileOpener.java:61)
	at msi.gama.lang.gaml.ui.editor.GamlHyperlinkDetector.getURI(GamlHyperlinkDetector.java:94)
	at msi.gama.lang.gaml.ui.editor.GamlHyperlinkDetector.lambda$0(GamlHyperlinkDetector.java:102)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at msi.gama.lang.gaml.ui.editor.GamlHyperlinkDetector.importHyperlinks(GamlHyperlinkDetector.java:98)
	at msi.gama.lang.gaml.ui.editor.GamlHyperlinkDetector.detectHyperlinks(GamlHyperlinkDetector.java:82)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:286)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:259)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:213)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by hqnghi88** [comment]
Yes, it was a fresh wp. When i typed, it does not occur an ext. I must close the project and reopen.

**Comment by AlexisDrogoul** [comment]
Again, it works for me without any problem. In the image below, I created the two files by hand.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/579256/43074163-85c8c22a-8ea6-11e8-80e2-e2d3631c8b99.png">

**Comment by hqnghi88** [comment]
Yes, it works. 
Thank you.
