### ISSUE TITLE
brewer_colors("Pastel1", 10) break validator

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2473]
**Describe the bug**

**To Reproduce**
1. type in any model

	list<rgb> var0 <- brewer_colors("Pastel1", 10);
2. An internal exception occurs:

GAMA Caught a workbench message : org.eclipse.xtext.ui.editor.validation.ValidationJob  - Error running validator

Pastel1 has less than 10 colors
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:67)
	at msi.gaml.operators.Colors.brewerPaletteColors(Colors.java:271)
	at gaml.additions.GamlAdditions.lambda$649(GamlAdditions.java:707)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:125)
	at msi.gaml.types.Types.isEmpty(Types.java:336)
	at msi.gaml.types.Types.isEmptyContainerCase(Types.java:316)
	at msi.gaml.compilation.IDescriptionValidator$Assert.typesAreCompatibleForAssignment(IDescriptionValidator.java:79)
	at msi.gaml.variables.Variable$VarValidator.assertAssignmentFacetsTypes(Variable.java:248)
	at msi.gaml.variables.Variable$VarValidator.validate(Variable.java:222)
	at msi.gaml.variables.ContainerVariable$ContainerVarValidator.validate(ContainerVariable.java:168)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:608)
	at msi.gaml.descriptions.IDescription.lambda$2(IDescription.java:93)
	at msi.gaml.descriptions.IDescription$DescriptionVisitor.execute(IDescription.java:61)
	at msi.gaml.descriptions.IDescription$DescriptionVisitor.execute(IDescription.java:1)
	at msi.gama.util.TOrderedHashMap.forEachValue(TOrderedHashMap.java:169)
	at msi.gaml.descriptions.TypeDescription.visitOwnAttributes(TypeDescription.java:697)
	at msi.gaml.descriptions.TypeDescription.visitOwnChildren(TypeDescription.java:678)
	at msi.gaml.descriptions.SpeciesDescription.visitOwnChildren(SpeciesDescription.java:847)
	at msi.gaml.descriptions.ModelDescription.visitOwnChildren(ModelDescription.java:365)
	at msi.gaml.descriptions.SymbolDescription.validateChildren(SymbolDescription.java:709)
	at msi.gaml.descriptions.SpeciesDescription.validateChildren(SpeciesDescription.java:768)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:601)
	at msi.gaml.descriptions.TypeDescription.validate(TypeDescription.java:723)
	at msi.gaml.descriptions.ModelDescription.validate(ModelDescription.java:410)
	at msi.gama.lang.gaml.resource.GamlResource.validate(GamlResource.java:187)
	at msi.gama.lang.gaml.validation.GamlResourceValidator.validate(GamlResourceValidator.java:66)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
 

**Expected behavior**
Model validated
**Screenshots**

**Desktop (please complete the following information):**
 - OS: should on any
 - GAMA version: git
 - Java version [e.g. 1.8]

**Additional context**

**Comment by sriramab** [comment]
Also note, manual has wrong values.
Secondly there is no information what is Pastel1 and what could be the other choice.

**Comment by AlexisDrogoul** [comment]
Well. Strange bug. There are two problems here: one is the different brewer_colors methods, which I more or less discover and which emit lots of exceptions. In a way, it is a good thing, but on the other hand, they shouldn't be declared as `can_be_const` since emitting exceptions is precisely a case where they do not return a const value... Which leads to the second problem: the compiler tries to infer whether or not they return an empty list with these values (for obscure reasons that I will not detail). So there are two things to fix here: the brewer_colors declarations, and also this compiler behaviour, which should obviously consider this case (i.e. that something declared as `can_be_const` is actually throwing an exception). 

On the other hand, the test made by the compiler does not really make sense in this context, and I wonder why it's here. I have deactivated it and recompiled all the examples, incl. MAELIA, and it does not catch anything new in terms of warnings or informations. So I assume it can be safely removed. At worst, it would produce more casting (from one type of list to another), but I'm not convinced it is still useful. 

And yes, the example is false. AFAIK (but there are no docs, even in the Java classes coming from GeoTools) the names come from the site http://colorbrewer2.org/.

**Comment by sriramab** [comment]
Yes, the website is correct but there is not direct list of names. But the same brewer is used by R and there is documentation or list of names and palettes.

What do you mean deactivated?  :open_mouth:  I cannot use the brewer :? please dont do it :(
