### ISSUE TITLE
Last release broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2477]
I try ti install the last release
GAMA1.8_Mac_64_07.26.18_6699c18

I get a very very minimal interface ;-)

this is what I have when I try to open GAMA with a new workspace:
<img width="1025" alt="screen shot 2018-07-26 at 05 35 33" src="https://user-images.githubusercontent.com/3928502/43254873-5156fc86-9096-11e8-8bfd-907bf029dc98.png">

mac os 10.11.6

Am I missing something somewhere?

**Comment by sriramab** [comment]
Same issue with me

**Comment by AlexisDrogoul** [comment]
Please launch from the Terminal and report the log !

**Comment by sriramab** [comment]
[gama_jdk_error.txt](https://github.com/gama-platform/gama/files/2231430/gama_jdk_error.txt)

**Comment by AlexisDrogoul** [comment]
```
Caused by: java.lang.ClassNotFoundException: org.jgrapht.WeightedGraph cannot be found by msi.gama.core_1.7.0.201807260353
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 72 more
```

Did someone change something in JGraphT ? @gama-platform/committers

**Comment by sriramab** [comment]
my gama on mac sierra looks same as that of Arnaud and a few times like this

![monosnap 2018-07-26 12-02-04](https://user-images.githubusercontent.com/12668606/43256121-142e90c2-90cc-11e8-80e2-59bea1dbffa5.png)

**Comment by hqnghi88** [comment]
It is the same on win release. No idea what is JGraphT .

**Comment by hqnghi88** [comment]
proprably fixed. Please retry.

**Comment by AlexisDrogoul** [comment]
My fault, by the way. I accidentally deleted JGraphT from the build files... 👎

**Comment by sriramab** [comment]
So, it this now resolved?

**Comment by hqnghi88** [comment]
Yes, I tested win release.
