### ISSUE TITLE
Drag and drop file in GAMA (model files)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2522]
**Describe the bug**
When I try to drag and drop model files from Finder (MacOsX) to a GAML project, in the models folder, it does not work (i.e. the files are not droped and I get an Exception in the Eclipse console, cf. screenshot section).

**To Reproduce**
1. Create a new Gama Project
2. Drag a .gaml file located in my Download folder (especially outside of the GAMA workspace) and attempt to drop it to the models folder of this Gama Project.

**Expected behavior**
I was expecting that the files are paste in the models folder.

**Screenshots**
```
java.lang.IllegalArgumentException: Path must include project and resource name: /.cache
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2068)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:202)
	at msi.gama.util.file.CacheLocationProvider.getValue(CacheLocationProvider.java:19)
	at org.eclipse.core.internal.resources.ProjectVariableProviderManager$Descriptor.getValue(ProjectVariableProviderManager.java:62)
	at org.eclipse.core.internal.resources.ProjectPathVariableManager.internalGetValue(ProjectPathVariableManager.java:152)
	at org.eclipse.core.internal.resources.ProjectPathVariableManager.getURIValue(ProjectPathVariableManager.java:111)
	at org.eclipse.ui.internal.ide.dialogs.RelativePathVariableGroup.getPreferredVariable(RelativePathVariableGroup.java:275)
	at org.eclipse.ui.internal.ide.dialogs.RelativePathVariableGroup.getPreferredVariable(RelativePathVariableGroup.java:347)
	at org.eclipse.ui.ide.dialogs.ImportTypeDialog.<init>(ImportTypeDialog.java:129)
	at org.eclipse.ui.actions.CopyFilesAndFoldersOperation.copyOrLinkFiles(CopyFilesAndFoldersOperation.java:761)
	at ummisco.gama.ui.navigator.NavigatorResourceDropAssistant.lambda$3(NavigatorResourceDropAssistant.java:479)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4034)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3701)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:121)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - GAMA version: git
 - Java version:  1.8

**Comment by AlexisDrogoul** [comment]
I cant reproduce this. Do you get the dialog asking you whether to copy or link the file ?

**Comment by AlexisDrogoul** [comment]
Hmm... I've tried all possible configurations and I can't reproduce it. I will try to make a small modification to see if it changes something on your side.

**Comment by benoitgaudou** [comment]
Previously I did not get the dialog asking to copy or link the file.
I just tried with your last commit and seems to work perfectly.
Thanks.
