### ISSUE TITLE
Model with 2 display and one fullscreen  wrong initialization

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2533]
I open this one as I notice something that I can easily reproduce

(it might be linked to this issue https://github.com/gama-platform/gama/issues/2527 as I think it appears just after this enhancement) 

With this model 

`````
model multiscreen

global {
 init{
 	create people number:100;
 }
}

species people{
	aspect base{
		draw circle(1);
	}
}
experiment multiscreen type: gui{
	output {		
		
        display CityScope type:opengl{
        	species people aspect: base;
        }
		display CityScopeTable   type:opengl fullscreen:1 {
			species people aspect: base;
		}
	}
}

`````

The first time you open GAMA and the first time you run it you get this 
![img_3157](https://user-images.githubusercontent.com/3928502/44673167-b6e14400-a9f8-11e8-8930-4939d933874d.jpg)

If you relaunch or rerun the model then it's fine 

---------------
Mac OS X - Latest Build

**Comment by agrignard** [comment]
Maybe this can help:
```
java.lang.NullPointerException
	at ummisco.gama.ui.views.displays.LayeredDisplayDecorator.adaptToolbar(LayeredDisplayDecorator.java:142)
	at ummisco.gama.ui.views.displays.LayeredDisplayDecorator.toggleFullScreen(LayeredDisplayDecorator.java:113)
	at ummisco.gama.ui.views.displays.LayeredDisplayDecorator.lambda$11(LayeredDisplayDecorator.java:205)
	at ummisco.gama.ui.utils.WorkbenchHelper$2.runInUIThread(WorkbenchHelper.java:350)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4034)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3701)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:121)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
java.lang.NullPointerException
```
