### ISSUE TITLE
Exception when closing an Experiment with OpenGL displays

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2539]
**Describe the bug**
When i click on clos button, with a running simulation Procedural City.gaml

**To Reproduce**
1. Go to Features/3D Visualization/models/Procedural City.gaml
2. Click on experiment button
3. Click Play then click close button of Gama window

Agents stack is empty
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:73)
	at msi.gama.runtime.ExecutionScope.pop(ExecutionScope.java:294)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:396)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:207)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:302)
	at java.lang.Thread.run(Thread.java:748)
Agents stack is empty
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:73)
	at msi.gama.runtime.ExecutionScope.pop(ExecutionScope.java:294)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:396)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:207)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:302)
	at java.lang.Thread.run(Thread.java:748)

**Expected behavior**
No exception

**Screenshots**
 
![image](https://user-images.githubusercontent.com/6105384/44921453-ce0f9100-ad6c-11e8-829e-5aa031f71a88.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - PC Model: asus RoG
 - GAMA version: git
 - Java version: 1.8
 - Graphics cards / Display system: Nvidia gtx 1050ti

**Comment by AlexisDrogoul** [comment]
Hmmm.. Cant reproduce it. Does it happen all the time ?

**Comment by hqnghi88** [comment]
I tried after your opngl optimization commit , it disappears. So i close now.
