### ISSUE TITLE
Various glitches in an opengl scene

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2541]
**Describe the bug**
When displaying "heavy" model in opengl and resizing the GUI , there is a visual glitch happening as shown in the video. It does not appear with every model I think it apperas as much window open you have and as "heavy" is the rendering.

Something also weird is that the mouse is also displaying something in the rendering (as a paper eraser effect). It might be due to a synchronization between ST windows, don't know if it's hard to fix.

**To Reproduce**
1. Open a model displaying a heavy opengl scene (e.g Agent Movement/Moving3D.gaml)
2. Resize one of the window in the UI

**Expected behavior**
No glitch

**Screenshots**
![bugart mov](https://user-images.githubusercontent.com/3928502/44996376-a2abc280-af75-11e8-838b-b29034ebd684.gif)

**Desktop (please complete the following information):**
 - OS: mac os
 - GAMA version: git

**Comment by agrignard** [comment]
It might be useful I just got this errorit maked crashed the display (not the simulation)
````
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.ui.internal.Activator).
log4j:WARN Please initialize the log4j system properly.
Sep 08, 2018 7:33:17 PM org.geotools.image.ImageWorker <clinit>
INFO: Warp/affine reduction enabled: true
SWTAccessor.<init>: GTK Version: 0.0.0
java.lang.RuntimeException: Waited 5000ms for: <4c438f66, 13087c75>[count 1, qsz 0, owner <Animator thread>] - <main>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:168)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.displayIfNoAnimatorNoCheck(GLCanvas.java:646)
	at com.jogamp.opengl.swt.GLCanvas.access$1100(GLCanvas.java:95)
	at com.jogamp.opengl.swt.GLCanvas$7.handleEvent(GLCanvas.java:389)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1275)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:172)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:766)
	at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:166)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5777)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5149)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5531)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3693)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:121)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Info: GLReadBufferUtil.readPixels: pre-exisiting GL error 0x506
Info: GLReadBufferUtil.readPixels: pre-exisiting GL error 0x506
null image data
Info: GLReadBufferUtil.readPixels: pre-exisiting GL error 0x506
Info: GLReadBufferUtil.readPixels: pre-exisiting GL error 0x506
null image data
null image data
null image data
````

**Comment by agrignard** [comment]
Also this one (mostly appears when going to fullscreen and trying to run the experiment) 
```
java.lang.NullPointerException
	at ummisco.gama.ui.experiment.parameters.AgentAttributesEditorsList.getItemDisplayName(AgentAttributesEditorsList.java:40)
	at ummisco.gama.ui.experiment.parameters.AgentAttributesEditorsList.getItemDisplayName(AgentAttributesEditorsList.java:1)
	at ummisco.gama.ui.views.inspectors.AttributesEditorsView.getItemDisplayName(AttributesEditorsView.java:61)
	at ummisco.gama.ui.controls.ParameterExpandBar.updateItemNames(ParameterExpandBar.java:406)
	at ummisco.gama.ui.views.ExpandableItemsView$1.runInUIThread(ExpandableItemsView.java:186)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4034)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3701)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:121)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by AlexisDrogoul** [comment]
Difficult to do anything without the files/models concerned, as I cannot reproduce any of these errors  with the Moving3D.gaml file.

**Comment by agrignard** [comment]
This is one is also once again difficult to reproduce this morning.

let's put that either on a workspace that was corrupted or maybe on the fact that my computer was almost full (less than 50Gb disponible on a 1Tb drive) that could have an impact on the graphics card...

Anyway I close it for now and I'll reopen it if I can reproduce it.
