### ISSUE TITLE
FileUtils constructAbsoluteFilePath make exception in Headless mode

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2554]
**Describe the bug**
FileUtils constructAbsoluteFilePath have exception in Headless mode

**To Reproduce**
1. Using a release (if you dont know how to run gama headless from eclipse), edit the sample model in headless folder predatorPrey.gaml
2. Add this line
		save "something" to: "somewhere.txt" type: text rewrite: true;
3. Launch headless for the predatorPrey.xml
java.lang.ArrayIndexOutOfBoundsException: 0
	at msi.gama.common.util.FileUtils.lambda$1(FileUtils.java:131)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:131)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:308)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:384)
	at msi.gama.runtime.IScope.execute(IScope.java:505)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:384)
	at msi.gama.runtime.IScope.execute(IScope.java:505)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:245)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:297)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:209)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:438)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:438)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:361)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:274)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:126)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:95)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:286)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:157)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:81)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:75)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:223)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:201)
Exception in thread "Thread-3" Java error: index out of bounds
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:64)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:468)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:438)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:361)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:274)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:126)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:95)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:286)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:157)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:81)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:75)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:223)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:201)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at msi.gama.common.util.FileUtils.lambda$1(FileUtils.java:131)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at msi.gama.common.util.FileUtils.constructAbsoluteFilePath(FileUtils.java:131)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:308)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:384)
	at msi.gama.runtime.IScope.execute(IScope.java:505)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:384)
	at msi.gama.runtime.IScope.execute(IScope.java:505)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:245)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:297)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:209)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:438)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	... 12 more 

**Expected behavior**
No exception

**Desktop (please complete the following information):**
 - OS: Win 10 
 - GAMA version: git, release
 - Java version: 1.8 

**Additional context**
note that if i specify an absolute path in save , it works.
		save "something" to: "D:/somewhere.txt" type: text rewrite: true;
Seem an error from 
ROOT.findContainersForLocation(new Path(s))[0] 
in that case the modern fileutil have found nothing.

**Comment by AlexisDrogoul** [comment]
Filed under #2453
