### ISSUE TITLE
Issue in OpenGL display when the shape of agents (from shapefile) is increasing

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2718]
**Describe the bug**
In a model, where agents are created from a shapefile, when the shape of an agent is increased (buffer of 1), after few steps, the OpenGL display showing the agents becomes white/empty and we get the following exception in Eclipse console: 

```
java.lang.ArrayIndexOutOfBoundsException: 20000
	at msi.gama.common.geometry.UnboundedCoordinateSequence.setToYNegated(UnboundedCoordinateSequence.java:369)
	at ummisco.gama.opengl.scene.GeometryDrawer.drawPolygon(GeometryDrawer.java:198)
	at ummisco.gama.opengl.scene.GeometryDrawer.drawGeometry(GeometryDrawer.java:147)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:85)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:29)
	at ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:118)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawObjects(LayerObject.java:259)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawAllObjects(LayerObject.java:247)
	at ummisco.gama.opengl.scene.layers.LayerObject.lambda$2(LayerObject.java:195)
	at ummisco.gama.opengl.OpenGL.compileAsList(OpenGL.java:938)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawWithoutShader(LayerObject.java:195)
	at ummisco.gama.opengl.scene.layers.LayerObject.draw(LayerObject.java:152)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:100)
	at ummisco.gama.opengl.renderer.helpers.SceneHelper.draw(SceneHelper.java:219)
	at ummisco.gama.opengl.renderer.JOGLRenderer.display(JOGLRenderer.java:190)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:960)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:659)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:199)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:180)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 20000
	at msi.gama.common.geometry.UnboundedCoordinateSequence.setToYNegated(UnboundedCoordinateSequence.java:369)
	at ummisco.gama.opengl.scene.GeometryDrawer.drawPolygon(GeometryDrawer.java:198)
	at ummisco.gama.opengl.scene.GeometryDrawer.drawGeometry(GeometryDrawer.java:147)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:85)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:29)
	at ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:118)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawObjects(LayerObject.java:259)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawAllObjects(LayerObject.java:247)
	at ummisco.gama.opengl.scene.layers.LayerObject.lambda$2(LayerObject.java:195)
	at ummisco.gama.opengl.OpenGL.compileAsList(OpenGL.java:938)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawWithoutShader(LayerObject.java:195)
	at ummisco.gama.opengl.scene.layers.LayerObject.draw(LayerObject.java:152)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:100)
	at ummisco.gama.opengl.renderer.helpers.SceneHelper.draw(SceneHelper.java:219)
	at ummisco.gama.opengl.renderer.JOGLRenderer.display(JOGLRenderer.java:190)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:960)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:659)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:199)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:180)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
```

**To Reproduce**
1. Open the first model of the Road Traffic tutorial
2. In the building species, add a reflex increasing the building shape.
3. Run the model and observe the Opengl dysplay of the agents that becomes empty.
```
global {
	file buildings_shapefile <- file("../includes/building.shp");
	file roads_shapefile <- file("../includes/road.shp");
	geometry shape <- envelope(envelope(buildings_shapefile) + envelope(roads_shapefile));
	float step <- 10 #mn;
	
	init {
		create building from: buildings_shapefile ;
		create road from: roads_shapefile ;
	}
}

species building {
	string type; 
	rgb color <- #gray  ;
	
	reflex r {
		shape <- shape + 1;
	}
	
	aspect base {
		draw shape color: color ;
	}
}

species road  {
	rgb color <- #red ;
	aspect base {
		draw shape color: color ;
	}
}

experiment road_traffic type: gui {
		
	output {
		display city_display type:opengl {
			species building aspect: base ;
			species road aspect: base ;
		}
	}
}
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git and 1.8 prerelease

**Additional context**

**Comment by AlexisDrogoul** [comment]
Well. By increasing the shape, it seems you increase the number of points, up to the limit of 20000 points imposed by this class... It would be easy to rewrite it so that it changes its size dynamically, but the original goal was to prevent too much garbage to be produced during OpenGL operations... I'll see what I can do !
