### ISSUE TITLE
NPE in execution of model Soccer Experiments.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2730]
**Describe the bug**
When running any of the 2 experiments of the model Soccer Experiments.gaml of the model library, an NPE appears (Java error: nil value detected) at cycle 0.

<img width="992" alt="Capture d’écran 2019-05-20 à 18 43 19" src="https://user-images.githubusercontent.com/1555274/58019193-2a028b80-7b2f-11e9-8a3c-6322690f3bd4.png">

In eclipse console, the exceptions are:
```
java.lang.NullPointerException
	at msi.gama.metamodel.shape.GamaShape.euclidianDistanceTo(GamaShape.java:555)
	at msi.gama.metamodel.agent.AbstractAgent.euclidianDistanceTo(AbstractAgent.java:135)
	at msi.gama.metamodel.topology.continuous.ContinuousTopology.distanceBetween(ContinuousTopology.java:121)
	at msi.gaml.operators.Spatial$Relations.distance_to(Spatial.java:3672)
	at gaml.additions.GamlAdditions.lambda$380(GamlAdditions.java:437)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:78)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:76)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.operators.Containers.lambda$2(Containers.java:135)
	at com.google.common.base.Predicate.test(Predicate.java:80)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.AbstractStreamEx.toCollection(AbstractStreamEx.java:1279)
	at msi.gaml.operators.Containers.where(Containers.java:1441)
	at gaml.additions.GamlAdditions.lambda$668(GamlAdditions.java:725)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:78)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:80)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.variables.Variable.getUpdatedValue(Variable.java:568)
	at msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:227)
	at msi.gama.runtime.ExecutionScope.update(ExecutionScope.java:645)
	at msi.gama.metamodel.agent.AbstractAgent.preStep(AbstractAgent.java:270)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:430)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:430)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:234)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:203)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:197)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:192)
	at msi.gama.runtime.ExecutionScope.lambda$2(ExecutionScope.java:431)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:431)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:97)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:228)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:430)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:430)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:64)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:83)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:76)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.operators.Containers.lambda$2(Containers.java:135)
	at com.google.common.base.Predicate.test(Predicate.java:80)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
	at one.util.streamex.AbstractStreamEx.toCollection(AbstractStreamEx.java:1279)
	at msi.gaml.operators.Containers.where(Containers.java:1441)
	at gaml.additions.GamlAdditions.lambda$668(GamlAdditions.java:725)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:78)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:80)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.variables.Variable.getUpdatedValue(Variable.java:568)
	at msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:227)
	at msi.gama.runtime.ExecutionScope.update(ExecutionScope.java:645)
	at msi.gama.metamodel.agent.AbstractAgent.preStep(AbstractAgent.java:270)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:430)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:430)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:234)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:203)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:197)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:192)
	at msi.gama.runtime.ExecutionScope.lambda$2(ExecutionScope.java:431)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:431)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:97)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:228)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:430)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:462)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:430)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at msi.gama.metamodel.shape.GamaShape.euclidianDistanceTo(GamaShape.java:555)
	at msi.gama.metamodel.agent.AbstractAgent.euclidianDistanceTo(AbstractAgent.java:135)
	at msi.gama.metamodel.topology.continuous.ContinuousTopology.distanceBetween(ContinuousTopology.java:121)
	at msi.gaml.operators.Spatial$Relations.distance_to(Spatial.java:3672)
	at gaml.additions.GamlAdditions.lambda$380(GamlAdditions.java:437)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:78)
	... 50 more
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Probably due to the fact that GAMA is now less tolerant to `nil` values passed to some operators.
