### ISSUE TITLE
Strange use of the ask statement allowed at the compilation.

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2770]
**Describe the bug**
A student has tried the following use of the `ask` statement: `		ask one_of(people).kingsAction(); `.

```
global {
	init {
		create people number: 10;
	}
	
	reflex t {
		ask one_of(people).kingsAction();
	}
}

species people {
	int i <- 12;
	action kingsAction {
		write "hello";
	}
}

experiment name type: gui { }
```

When the model is run, we get the following exception:
```
Java error: wrong casting
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:65)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:468)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:452)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:430)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException
```

**Expected behavior**
In fact, I think it is expected to get an exception here.
Nevertheless, I do not understand this syntax is accepted at the compilation step.
Could GAMA identify that this syntax is wrong from a compilation point of view ? 
`ask one_of(people).kingsAction(); `.

**Desktop (please complete the following information):**
 - GAMA version:git

**Comment by AlexisDrogoul** [comment]
Well, actually, there would be a warning if the action was returning something. But here we fall in a strange situation. I've made a few adjustments to consider this case !
