### ISSUE TITLE
Exception linked with UI

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#2784]
**Describe the bug**
Exception linked with UI could happen due to multi-threading

**To Reproduce**
Load "ant foraging.gaml" model and start a simulation with an huge amount of agent. reload the simulation without stopping the previous one, an exception may happen blocking the simulation. 

java.lang.NullPointerException
	at ummisco.gama.ui.views.displays.LayeredDisplayView.update(LayeredDisplayView.java:329)
	at msi.gama.outputs.AbstractDisplayOutput.update(AbstractDisplayOutput.java:82)
	at msi.gama.outputs.LayeredDisplayOutput.update(LayeredDisplayOutput.java:453)
	at msi.gama.outputs.AbstractOutputManager.step(AbstractOutputManager.java:230)
	at msi.gama.kernel.simulation.SimulationAgent.postStep(SimulationAgent.java:305)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:255)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:433)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:433)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:57)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:470)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:433)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at ummisco.gama.ui.views.displays.LayeredDisplayView.update(LayeredDisplayView.java:329)
	at msi.gama.outputs.AbstractDisplayOutput.update(AbstractDisplayOutput.java:82)
	at msi.gama.outputs.LayeredDisplayOutput.update(LayeredDisplayOutput.java:453)
	at msi.gama.outputs.AbstractOutputManager.step(AbstractOutputManager.java:230)
	at msi.gama.kernel.simulation.SimulationAgent.postStep(SimulationAgent.java:305)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:255)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:433)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	... 8 more

**Comment by gnoubi** [comment]
Note that the exception happens when there is an image displayed

**Comment by AlexisDrogoul** [comment]
Yep. That happens all the time and very often, also in other models, and it is normal as far as I can tell regarding the number of threads accessing the same information . That's why the preferences provide the possibility to not display the errors happening in displays. Did you check it ?

**Comment by AlexisDrogoul** [comment]
Otherwise: you talk about multi-threading, but which experiment did you run, how many simulations and threads ?  What is a "huge amount" of agents ? "an exception may happen": is it reproducible ? does it happen all the time or only some time ? Thank you to be a bit more precise.

**Comment by gnoubi** [comment]
Hi

The « Show errors thrown in displays and outputs » is selected to false value. The exception is shown in the display of the new simulation.

Nicolas

**Comment by gnoubi** [comment]
Yes I talk about multi-threading because I think that some simulation thread are not closed (especially display thread) before simulation reload

I test the simple ant model with a 2000 or 4000  sized population of ants.

It happens some time for a simple model but all the time when the model becomes more complicated, with many GUI elements (e.g. LittoSIM-Gen model).

Thanks
Nicolas
Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906
