### ISSUE TITLE
GAMA stop working from setting a buffer to world shape

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2787]
**Describe the bug**
Launch the following simple model , gama throw an exception and then seems hang (clicking on stop button does not close experiment , no "Not responding" message but no thing more we can do until restart gama). If we remove + 0.1 after envelope, it will work.
model NewModel

global {
	geometry shape <- envelope(square(100)) + 0.1;
}
grid ground width:5 height:5 neighbors:4{
	
}
experiment NewModel type: gui { 
	output {
		display "ss" {
			grid ground lines:#black;
		}
	}
}

See error in eclipse

java.lang.NullPointerException
	at msi.gama.metamodel.topology.grid.GridNeighborhood.getNeighborsIn(GridNeighborhood.java:115)
	at msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation$GamlGridAgent.getNeighbors(GamaSpatialMatrix.java:1845)
	at msi.gaml.skills.GridSkill.getNeighbors(GridSkill.java:146)
	at gaml.additions.GamlAdditions.lambda$96(GamlAdditions.java:211)
	at msi.gaml.compilation.GamaHelper.run(GamaHelper.java:43)
	at msi.gaml.compilation.IGamaHelper.run(IGamaHelper.java:35)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:486)
	at msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation.createAgents(GamaSpatialMatrix.java:1583)
	at msi.gama.metamodel.topology.AbstractTopology.initialize(AbstractTopology.java:173)
	at msi.gama.metamodel.topology.grid.GridTopology.initialize(GridTopology.java:55)
	at msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation.initializeFor(GamaSpatialMatrix.java:1641)
	at msi.gama.metamodel.agent.GamlAgent.initializeMicroPopulation(GamlAgent.java:218)
	at msi.gaml.descriptions.SpeciesDescription.lambda$4(SpeciesDescription.java:673)
	at msi.gaml.compilation.IGamaHelper.run(IGamaHelper.java:35)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:486)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:414)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:394)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:121)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:292)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:246)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:260)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:440)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:440)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:312)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/6105384/61167355-e002b880-a567-11e9-907e-b1d5a2219abf.png)

**Expected behavior**
no exception and no hang

**Desktop (please complete the following information):**
win 10, gama git, jdk 8

**Comment by AlexisDrogoul** [comment]
Two things happen in sequence here:

1. The grid does not seem to be initialised correctly if the shape of the world is not a rectangle or square (some cells are not considered as "covering" the shape of the wolrd). And adding a buffer to an envelope creates a rounded rectangle. To obtain what you want, `envelope(square(100+0.1))` or `envelope(envelope(square(100)) + 0.1)`work, just not your expression. 
2. This creates a state where part of the grid is not correctly instantiated, and this part cannot be correctly disposed of, preventing the experiment to be correctly closed, etc.

I've pushed a fix for both.
