### ISSUE TITLE
Exception when displaying gif image (izard.gif from the model library)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2790]
**Describe the bug**
When I run the model Data / Data importation / Raster Image Import.gaml, the Izards are not displayed. Their aspect draws a gif image.

The Exception that appears in the Eclipse console is the following one:
```
Error when drawing in a display : java.lang.IllegalArgumentException: Non-positive period.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Non-positive period.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at msi.gama.common.util.ImageUtils.getImageFromFile(ImageUtils.java:164)
	at msi.gama.common.util.ImageUtils.getImageFromFile(ImageUtils.java:97)
	at msi.gama.util.file.GamaImageFile.loadImage(GamaImageFile.java:275)
	at msi.gama.util.file.GamaImageFile.getImage(GamaImageFile.java:290)
	at msi.gama.outputs.display.AWTDisplayGraphics.drawFile(AWTDisplayGraphics.java:168)
	at msi.gaml.statements.draw.FileExecuter.executeOn(FileExecuter.java:62)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:325)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:210)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:419)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Non-positive period.
	at java.util.Timer.scheduleAtFixedRate(Timer.java:327)
	at msi.gama.common.util.GifDecoder.readContents(GifDecoder.java:571)
	at msi.gama.common.util.GifDecoder.read(GifDecoder.java:290)
	at msi.gama.common.util.ImageUtils.privateReadGifFromFile(ImageUtils.java:150)
	at msi.gama.common.util.ImageUtils.lambda$3(ImageUtils.java:164)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 57 more
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by benoitgaudou** [comment]
I also notice, that even when the Preference "show Error message in the display" is set to true, the exception is not displayed in GAMA (only in Eclipse).

**Comment by AlexisDrogoul** [comment]
Probably because GIF files are supposed to be animated **by default**.
