### ISSUE TITLE
Saving to GeoTiff produces a not compatible Tiff file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2793]
**Describe the bug**
Run the model `Save to Geotiff.gaml` from the Model Library / Data / Data Exportation.

When the folder `results` (in which the file should be created) does not exist, 
it throws in the Eclipse console (only) the following exception.

When the folder `results` exists, then the exception is not thrown, but the generated file 
Notice that a generated tif file is not recognized as a tif file by GAMA and cannot be displayed in GAMA.
(when I double click on the file, to open it the second Exception below occurs).

```
java.io.FileNotFoundException: /Users/ben/Dev/GitRepository/gama/msi.gama.models/models/Data/Data Exportation/results/grid.prj (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at msi.gaml.statements.SaveStatement.saveRasterImage(SaveStatement.java:497)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:380)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:311)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:440)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:362)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:288)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:293)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:247)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:261)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:440)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:440)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:313)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException: Some input parameters are null
	at org.geotools.gce.geotiff.GeoTiffWriter.writeImage(GeoTiffWriter.java:402)
	at org.geotools.gce.geotiff.GeoTiffWriter.write(GeoTiffWriter.java:271)
	at msi.gaml.statements.SaveStatement.saveRasterImage(SaveStatement.java:551)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:380)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:311)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:440)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:362)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:288)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:293)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:247)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:261)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:440)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:440)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:313)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
-- Surface bounds set to 0  0 | 1167 789
-- Surface bounds set to 0  0 | 1167 800
-- Surface bounds set to 0  0 | 1167 831
-- Surface bounds set to 0  0 | 1167 831
```

Exception when trying to open the generated file: 

```
-- Surface bounds set to 0  0 | 1167 831
org.eclipse.swt.SWTException: Invalid image (java.lang.ArithmeticException: / by zero)
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:64)
	at org.eclipse.swt.internal.image.FileFormat.load(FileFormat.java:90)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:155)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:25)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:335)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:65)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createImageFileMetaData(FileMetaDataProvider.java:460)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:337)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:375)
	at ummisco.gama.ui.navigator.contents.ResourceManager.processAddition(ResourceManager.java:277)
	at ummisco.gama.ui.navigator.contents.ResourceManager.visit(ResourceManager.java:438)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at ummisco.gama.ui.navigator.contents.ResourceManager.resourceChanged(ResourceManager.java:232)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ArithmeticException: / by zero
	at org.eclipse.swt.internal.image.TIFFDirectory.getGrayPalette(TIFFDirectory.java:220)
	at org.eclipse.swt.internal.image.TIFFDirectory.read(TIFFDirectory.java:458)
	at org.eclipse.swt.internal.image.TIFFFileFormat.loadFromByteStream(TIFFFileFormat.java:65)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:59)
	... 25 more
null image data
org.eclipse.swt.SWTException: Invalid image (java.lang.ArithmeticException: / by zero)
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:64)
	at org.eclipse.swt.internal.image.FileFormat.load(FileFormat.java:90)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:155)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:25)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:335)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:65)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createImageFileMetaData(FileMetaDataProvider.java:460)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:337)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:375)
	at ummisco.gama.ui.navigator.contents.WrappedFile.getSuffix(WrappedFile.java:132)
	at ummisco.gama.ui.navigator.NavigatorBaseLighweightDecorator.decorate(NavigatorBaseLighweightDecorator.java:32)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:261)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:107)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:380)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:362)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:350)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:313)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ArithmeticException: / by zero
	at org.eclipse.swt.internal.image.TIFFDirectory.getGrayPalette(TIFFDirectory.java:220)
	at org.eclipse.swt.internal.image.TIFFDirectory.read(TIFFDirectory.java:458)
	at org.eclipse.swt.internal.image.TIFFFileFormat.loadFromByteStream(TIFFFileFormat.java:65)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:59)
	... 18 more
null image data
Deleting simulation perspective and opening immediately the modeling perspective = false
org.eclipse.swt.SWTException: Invalid image (java.lang.ArithmeticException: / by zero)
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:64)
	at org.eclipse.swt.internal.image.FileFormat.load(FileFormat.java:90)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:155)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:25)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:335)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:65)
	at ummisco.gama.ui.viewers.image.ImageViewer.loadImageData(ImageViewer.java:349)
	at ummisco.gama.ui.viewers.image.ImageViewer$2.run(ImageViewer.java:315)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ArithmeticException: / by zero
	at org.eclipse.swt.internal.image.TIFFDirectory.getGrayPalette(TIFFDirectory.java:220)
	at org.eclipse.swt.internal.image.TIFFDirectory.read(TIFFDirectory.java:458)
	at org.eclipse.swt.internal.image.TIFFFileFormat.loadFromByteStream(TIFFFileFormat.java:65)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:59)
	... 8 more
null image data
java.lang.NullPointerException
	at ummisco.gama.ui.viewers.image.ImageViewer.lambda$0(ImageViewer.java:176)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at ummisco.gama.ui.controls.FlatButton.doButtonUp(FlatButton.java:137)
	at ummisco.gama.ui.controls.FlatButton.handleEvent(FlatButton.java:102)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4150)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:126)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
I won't work on this, bit of fed up with GeoTiff format. If no one wants to fix it, then we remove GeoTiff from the list of save formats.
