### ISSUE TITLE
Save may return an error in batch mode (and not in GUI mode) when rewritting the file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2796]
**Describe the bug**
Let consider the model below, that is a simplification of the model `model13.gaml` located in  `Tutorials / Predator Prey / `.
The important part is the `save` statement: 
 * when I run the GUI experiment, I get no error, and the model writes in the file at each step a value
 * when I run the batch experiment, the exception below appears.

```
global {
	float energy_init <- 1.0;

	init {
		create generic_species number: 100;
	}
	
	reflex save_result when: (length(generic_species) > 0){
		save ("cycle: "+ cycle + "; nbPreys: " + length(generic_species)) to: "results.txt" type: "text" ;
	}
	
	reflex stop_simulation when: (length(generic_species) = 0) {
		do pause ;
	} 
}

species generic_species {
	float energy <- (rnd(1000) / 1000) * energy_init  update: energy - 1 max: 10.0 ;
	reflex death when: energy < 0 { do die; }
}

experiment prey_predator type: gui { }

experiment Optimization type: batch repeat: 2 keep_seed: true until: ( time > 200 ) {
	parameter "Energy init:" var: energy_init min: 0.1 max: 1.0 step: 0.1;
	method tabu maximize: length(generic_species) iter_max: 10 tabu_list_size: 3;
}
```

**Notice that, I correct the `model13.gaml`, in order to keep the value for each cycle, by adding the `rewrite` facet such as:** 
 ```
  		save ("cycle: "+ cycle + "; nbPreys: " + length(generic_species)) to: "results.txt" type: "text" rewrite: (cycle = 0) ? true : false;

 ```
 
And this solves the "bug" explained above.
So I do not know if this is really an issue to fix? Or an issue easy to close :-)

Here is the exception:

```
Java error: I/O error
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:55)
	at msi.gaml.statements.SaveStatement.saveText(SaveStatement.java:764)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:365)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:106)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:99)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.lambda$1(ExecutionScope.java:433)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:464)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:454)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:433)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Invalid argument
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
	at msi.gaml.statements.SaveStatement.saveText(SaveStatement.java:761)
	... 27 more
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version:  git

**Comment by AlexisDrogoul** [comment]
It's because of the concurrency between simulations: they all try to access (esp. open and close) the same file, which is a bad idea. If you remove the possibility for experiments to run simulations in parallel, then the error disappears. Of if you name the file after the simulation name... The same would happen in Java with multiple threads, so it's clearly a bad design of the model, not a bug in GAMA.
