### ISSUE TITLE
NPE in a chart (in LWR Traffic model)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2804]
**Describe the bug**
Run the model `LWR Traffic Flow Model.gaml` in `Toy Models / Traffic`.
Let the simulation run until a cycle between 2000 and 2500 (basically after that the red serie in the Concentration display becomes lower than the other ones).

A NPE Exception appears in GAMA and in the Eclipse Console.

Notice: I tired to identify from which display this Exception has been thrown by commenting on the 2 displays with a chart, but the Exception was not thrown anymore in these cases...
 
```
java.lang.NullPointerException
reportAndThrowIfNeeded : Java error: nil value detected
	at org.jfree.data.xy.XYIntervalSeries.getX(XYIntervalSeries.java:122)
	at org.jfree.data.xy.XYIntervalSeriesCollection.getX(XYIntervalSeriesCollection.java:161)
	at org.jfree.data.xy.AbstractXYDataset.getXValue(AbstractXYDataset.java:77)
	at org.jfree.chart.renderer.xy.XYLineAndShapeRenderer.drawPrimaryLine(XYLineAndShapeRenderer.java:824)
	at org.jfree.chart.renderer.xy.XYLineAndShapeRenderer.drawItem(XYLineAndShapeRenderer.java:750)
	at org.jfree.chart.renderer.xy.XYErrorRenderer.drawItem(XYErrorRenderer.java:394)
	at org.jfree.chart.plot.XYPlot.render(XYPlot.java:3739)
	at org.jfree.chart.plot.XYPlot.draw(XYPlot.java:3272)
	at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1286)
	at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1172)
	at msi.gama.outputs.layers.charts.ChartJFreeChartOutput.getImage(ChartJFreeChartOutput.java:137)
	at msi.gama.outputs.display.AWTDisplayGraphics.drawChart(AWTDisplayGraphics.java:450)
	at msi.gama.outputs.layers.charts.ChartLayer.privateDraw(ChartLayer.java:52)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:419)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
report error : Java error: nil value detected
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Cant reproduce it (i've tried different combinations of parameters, but w/o luck).

**Comment by AlexisDrogoul** [comment]
Same issue (I suspect) than #1605. And same unsatisfactory conclusion and fix.
