### ISSUE TITLE
review needed for model SIR Comodel.gaml (NPE,  empty JAVA2D displays and strange OpenGL displays)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2805]
**Describe the bug**
Run the model `SIR Comodel.gaml` from `Toy Model / Comodels / SIR Switch`.

2 issues appear to me in the simulation:
- The display HostDisp#SIR_2#Adapter#0 is empty.
- After having launched the simulation, after a number of steps (that is different for each simulation), a NPE is thrown from an aspect (of a dead agent). See the Exception below and the screenshot.

```
report error : Java error: nil value detected
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:57)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:81)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.draw.DrawingData.lambda$4(DrawingData.java:108)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionEvaluator.value(AttributeHolder.java:104)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionEvaluator.refresh(AttributeHolder.java:109)
	at msi.gaml.statements.draw.AttributeHolder.lambda$0(AttributeHolder.java:120)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at msi.gaml.statements.draw.AttributeHolder.refresh(AttributeHolder.java:120)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:324)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:210)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:44)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:190)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:388)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:419)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at gaml.additions.GamlAdditions.lambda$932(GamlAdditions.java:989)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	... 56 more
```

**Screenshots**
<img width="471" alt="Screenshot 2019-07-20 at 02 11 08" src="https://user-images.githubusercontent.com/1555274/61559375-bd0a6400-aa93-11e9-9eaf-a4bba2d0ff6e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by hqnghi88** [comment]
I change the model for the second part.
The first part indeed is strange , as i recognize some "force layouting" and it should be a bug of comodeling with the new layout feature.

**Comment by AlexisDrogoul** [comment]
Several things (on mac): 

- With the recent bug fix (for #2813), the displays appear twice for each submodel. 
- Only Java2D displays appear blank. When set to OpenGL, they show up. However, they behave very strangely (as if only one surface was shared between two displays : ie you can move one and the second will move too).
- It is a bit difficult to understand the meanings of the displays: 2 charts are labeled the same way, we have "SIR_1.Adapter" and "SIR_2.Adapter" (or something like this) for the titles, which make it hard to understand what they are supposed to represent. Wouldn't it be possible to label the displays/experiments a little bit more clearly (i.e. Agents_SIR, Equation_SIR, something like this...) ?

In the meantime, the question of displays in comodels experiments is absolutely not clear. Are the submodels displays supposed to show up at all ? Or is it a bug ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Corresponding with the current code in the models, the displays of sub model are not supposed to show up, as in each "adapter" (xxx adapter.gaml), there is a blank output, which mean replacing/overriding the output of its micro-model. If we dont place a blank output in adapter, or import directly micromodel in comodel , the micro-displays should show up.
I found the strange naming behavior and commented it in other close issue too. I will take alook soon tomorrow.

**Comment by AlexisDrogoul** [comment]
OK. So the fact that the displays show up is clearly a bug ? We should probably narrow this issue to this, then (i.e. `submodels displays show up although an empty output is defined in the adapter...` or something like this).

**Comment by benoitgaudou** [comment]
I run it today and get the following exception now.
Any idea?
```
java.lang.NullPointerException
	at msi.gama.kernel.experiment.ExperimentAgent.getDefinedSeed(ExperimentAgent.java:215)
	at msi.gama.kernel.experiment.ExperimentAgent.initialize(ExperimentAgent.java:183)
	at msi.gama.kernel.experiment.ExperimentAgent.<init>(ExperimentAgent.java:175)
	at gaml.additions.GamlAdditions.lambda$1125(GamlAdditions.java:1200)
	at msi.gama.common.interfaces.IExperimentAgentCreator$ExperimentAgentDescription.create(IExperimentAgentCreator.java:39)
	at msi.gaml.compilation.kernel.GamaMetaModel.createExperimentAgent(GamaMetaModel.java:72)
	at msi.gama.kernel.experiment.ExperimentPlan$ExperimentPopulation.createAgents(ExperimentPlan.java:246)
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:498)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:449)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:314)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:474)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:362)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:291)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:309)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:263)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:277)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:431)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:329)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hqnghi88** [comment]
I close this issue with a workaround that remove the error, but the root cause is a problem with the display of inheritant experiment of micro-model. I will find time to view it before the release (im currently stuck in another mission for warm team).
