### ISSUE TITLE
Draw statement exception in border: + boolean and rotate: + integer

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2821]
**Describe the bug**

In the draw statement, 2 new Exceptions appear:
- `border:` :  this facet can accept boolean or a color. But when it is a boolean, the following exception appears:
```
Error when drawing in a display : java.lang.Boolean cannot be cast to msi.gama.util.GamaColor
```
- `rotate:`: this facet can accept integer or a pair. But when it is an integer, the following exception appears:
```
Error when drawing in a display : java.lang.Integer cannot be cast to msi.gama.util.GamaPair
```

Here is a model example to illustrate this:

```
global {
	init {
		create aspBorder ;
		create aspRotate;
	}
}

species aspBorder {
	aspect default {
		draw circle(1.0) border: true;
	}
}

species aspRotate {
	aspect default {
		draw square(1.0) rotate: 45;
	}
}

experiment name type: gui {
	
	output {
		display d {
			species aspBorder ;
			species aspRotate;
		}
	}
}
```

Here is the Exceptions:

```
Error when drawing in a display : java.lang.Boolean cannot be cast to msi.gama.util.GamaColor
java.lang.ClassCastException: java.lang.Boolean cannot be cast to msi.gama.util.GamaColor
	at msi.gaml.statements.draw.ShapeExecuter.computeAttributes(ShapeExecuter.java:148)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:88)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:324)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:191)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:419)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Error when drawing in a display : java.lang.Integer cannot be cast to msi.gama.util.GamaPair
java.lang.ClassCastException: java.lang.Integer cannot be cast to msi.gama.util.GamaPair
	at msi.gaml.statements.draw.ShapeExecuter.computeAttributes(ShapeExecuter.java:147)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:88)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:324)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:191)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:419)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by benoitgaudou** [comment]
I can add, I also get in another model (to big to be shared sorry), the following error:
- `Error when drawing in a display : java.lang.Double cannot be cast to msi.gama.metamodel.shape.ILocation`

It seems to come from the `at:` but I am not sure  ...

**Comment by AlexisDrogoul** [comment]
OK. I got it ! Expect a fix in a few minutes.
