### ISSUE TITLE
Some PNG images cannot be viewed in the included image viewer

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2825]
**Describe the bug**
In a project, we use some PNG pictures that:
- work perfectly when used in a model (i.e. when they are used in a `draw` statement, they appear in the display and do not throw any exception),
- throw an exception when I try to display them in GAMA. In addition (and this is linked), their metadata are not displayed.

I attached at the end the image and the GAMA project.

The exception is:
```
org.eclipse.swt.SWTException: Invalid image
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.internal.image.PngChunk.validate(PngChunk.java:351)
	at org.eclipse.swt.internal.image.PngChunkReader.readNextChunk(PngChunkReader.java:59)
	at org.eclipse.swt.internal.image.PNGFileFormat.readNextChunk(PNGFileFormat.java:94)
	at org.eclipse.swt.internal.image.PNGFileFormat.loadFromByteStream(PNGFileFormat.java:80)
	at org.eclipse.swt.internal.image.FileFormat.loadFromStream(FileFormat.java:59)
	at org.eclipse.swt.internal.image.FileFormat.load(FileFormat.java:90)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:155)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:25)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:335)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:92)
	at ummisco.gama.ui.viewers.image.ImageViewer.loadImageData(ImageViewer.java:349)
	at ummisco.gama.ui.viewers.image.ImageViewer$2.run(ImageViewer.java:315)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Screenshots**
Here is a picture of my GAMA project:
<img width="286" alt="Screenshot 2019-07-29 at 11 22 52" src="https://user-images.githubusercontent.com/1555274/62021791-3c660900-b1f3-11e9-8db1-bb890c4220c1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

![0](https://user-images.githubusercontent.com/1555274/62021701-bea1fd80-b1f2-11e9-9178-112b082d394e.png)

[Test_pictures.zip](https://github.com/gama-platform/gama/files/3440183/Test_pictures.zip)

**Comment by benoitgaudou** [comment]
I can add that I noticed that all the pictures that throw this Exception in GAMA share the same characteristics:
- in the (Mac) Finder, their Colour profile is "GIMP built-in sRGB"
(whereas the other image, that do not throw an Exception, can have no profile, sRGB IEC61966-2.1 or Adobe ImageReady... )

**Comment by AlexisDrogoul** [comment]
Well, in that case, just open and re-export them using "Preview.app" or any graphic application, as Gimp probably introduces some exotic metadata that SWT can't read. But we won't (can't) fix it in GAMA.

**Comment by AlexisDrogoul** [comment]
OK. Found a workaround via ImageIO.
