### ISSUE TITLE
Exception in event management

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2826]
When I run the following model (this is a simplification of an existing model), a grey rectangle appears (in a JAva2D display). 
When I click on it, the associated agent is supposed to die, but instead, I get an Exception (see below).

```
	action move_down_event {
		ask elements {
		//	do move_down_event();
			if(move_down_event()){return;}
		}
	}
```

Note that the exception is "due" to the following line: `if(move_down_event(){return;}`. When it replaced by `do move_down_event();`, the model works fine.

I admit that I do not know whether this is due to a GAMA issue, a modeler bad practice or both?

```
model NewModel

global {
	float ui_width <- 100.0;
	float ui_height <- 20.0;
		
	init {
		 create Basket {
			do add_action_to_basket;		
		 }	
	}
	
	action move_down_event_basket{	
		ask Basket {
			do move_down_event;
		}
	}
}

species Displayed_List_Element {

	geometry rec2 <- polyline([{0,0}, {ui_width,0}]);
	geometry rec <- polygon([{0,0}, {0,ui_height}, {ui_width,ui_height},{ui_width,0},{0,0}]);
	geometry shape <-  rectangle(ui_width, ui_height);

	bool move_down_event{
		if self overlaps #user_location  {
			do die;
			return true;
		}
		return false;
	}	
	
 	aspect default {
		draw rec   at: {location.x, location.y} color: rgb(233,233,233);
		draw rec2  at: {location.x, location.y + ui_height / 2} color: #black;
	}
}

species Basket {
	list<Displayed_List_Element> elements <- [];

	action move_down_event {
		ask elements {
		//	do move_down_event();
			if(move_down_event()){return;}
		}
	}
		
	action add_item (Displayed_List_Element list_elem){
		elements 	<- elements + list_elem;
	}

	action add_action_to_basket {
	  	create Displayed_List_Element returns: elem ;
		do add_item(first(elem));
	}
}

experiment e {
	
	output {
		display "Basket" background:#black {
			species Displayed_List_Element ;
			
			event mouse_down action: move_down_event_basket;
		}
	}	
}
```

Here is the Exception:
```
java.lang.NullPointerException
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:212)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.RemoteSequence.privateExecuteIn(RemoteSequence.java:45)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:260)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:275)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:209)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:58)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:510)
	at msi.gaml.statements.DoStatement.privateExecuteIn(DoStatement.java:271)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.RemoteSequence.privateExecuteIn(RemoteSequence.java:45)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:260)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:275)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:209)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:58)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:368)
	at msi.gama.outputs.layers.EventLayer$EventListener.lambda$0(EventLayer.java:184)
	at msi.gama.runtime.GAMA.runAndUpdateAll(GAMA.java:392)
	at msi.gama.outputs.layers.EventLayer$EventListener.executeEvent(EventLayer.java:184)
	at msi.gama.outputs.layers.EventLayer$EventListener.mouseDown(EventLayer.java:140)
	at ummisco.gama.java2d.Java2DDisplaySurface.dispatchMouseEvent(Java2DDisplaySurface.java:212)
	at ummisco.gama.ui.views.displays.LayeredDisplayMultiListener.mouseDown(LayeredDisplayMultiListener.java:162)
	at ummisco.gama.ui.views.displays.SWTLayeredDisplayMultiListener.mouseDown(SWTLayeredDisplayMultiListener.java:132)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4150)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:126)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
```

**Comment by AlexisDrogoul** [comment]
The code is **weird**, to say the least. What is GAMA supposed to do, for instance, with : 

 ```
		if self overlaps #user_location  {
			do die;
			return true;
		}
```

Return something ? But the execution scope is interrupted by the death of the agent. Not return anything ? In that case it is dead code and the result cant be trusted in the calling actions. 
No wonder, anyway, that you have a NPE somewhere ! 

So the code, here, is clearly at fault. However, your exception revealed a problem in the reporting of exceptions: when an agent died, the errors "belonging" to it were not displayed. So I made some changes to allow them to be displayed.
