### ISSUE TITLE
Th CSV view is empty

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2832]
**Describe the bug**
In GAMA, double-click on a CSV file.
It should open a CSV viewer in GAMA and fill in it with the value of the csv file
Right now, this new view is open, but the table is empty. In the text pane there is the text of the csv file.

The following exception is thrown in the Eclipse console
```
java.lang.NoClassDefFoundError: msi/gama/util/file/csv/CsvReader
	at ummisco.gama.ui.viewers.csv.model.CSVModel.initializeReader(CSVModel.java:129)
	at ummisco.gama.ui.viewers.csv.model.CSVModel.readLines(CSVModel.java:160)
	at ummisco.gama.ui.viewers.csv.model.CSVModel.readLines(CSVModel.java:148)
	at ummisco.gama.ui.viewers.csv.model.CSVModel.setInput(CSVModel.java:121)
	at ummisco.gama.ui.viewers.csv.MultiPageCSVEditor.updateTableFromTextEditor(MultiPageCSVEditor.java:212)
	at ummisco.gama.ui.viewers.csv.MultiPageCSVEditor.lambda$1(MultiPageCSVEditor.java:188)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4102)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:126)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
Caused by: java.lang.ClassNotFoundException: msi.gama.util.file.csv.CsvReader cannot be found by ummisco.gama.ui.viewers_1.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git

**Comment by benoitgaudou** [comment]
I try a fix by exporting the `msi.gama.util.file.csv` in the `msi.gama.core` plugin.

Please reopen the issue if this fix is not the genuine one and could introduce unexpected side effects.

**Comment by AlexisDrogoul** [comment]
Would be a good thing to regenerate the binaries (and replace them used in the 1.8 version...)
