### ISSUE TITLE
Setup SonarCloud on GAMA Repo

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#2843]
**Is your request related to a problem? Please describe.**
It could be a great idea to use a code covering service on the GAMA repo. It will help to see what files are forgotten in the repo, clean dead code, etc 

**Describe the solution you'd like**
I know [SonarQube software](https://www.sonarqube.org/) which works very well for Java projects. And it can easily be used (for free) on the [SonarCloud platform](https://sonarcloud.io/) (for the dashboard) with Travis CI (to fetch code at each commit)! :smile: 

**Additional context**
I've already linked the organization and the project [here](https://sonarcloud.io/organizations/gama-platform/projects), I just need the help of @hqnghi88 to [setup Travis](https://docs.travis-ci.com/user/sonarcloud/#inspecting-code-with-the-sonarqube-scanner) properly (I've started by setting the `SONAR_TOKEN` :wink: )

**Comment by RoiArthurB** [comment]
Hi all,

I've tried to add SonarCloud in the Travis runtime, but it couldn't compile... 

Here's the error : 
```
mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gama-platform_gama

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/travis/build/gama-platform/gama). Please verify you invoked Maven from the correct directory. -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

The command "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gama-platform_gama" exited with 1.
```
(see here : https://travis-ci.org/gama-platform/gama/builds/569696845#L500 line 500)

So, from what I understand, the problem is that i can't find a POM file for the GAMA project.. Anyone have any idea about how to solve it? :thinking:

**Comment by RoiArthurB** [comment]
Hey @hqnghi88, I saw your commit (537461e4eb4111531185090d5f8cc0c67d93c2e4) which works ! :smile: 
But it just do the job for `msi.gama.parent` package... Is that normal? :thinking:

**Comment by hqnghi88** [comment]
No, it do the job for annotation, processor, and parent (parent will spread to all the rest)

**Comment by RoiArthurB** [comment]
I'm afraid that the command work, but is over-write each time... Maybe I should create 2 other projects for these packages? :thinking: 

But I'm sure that, for example, the package `ummsi.gama.annotation` is not covered and the name of the project (msi.gama.parent) really makes me think about over-writing...

**Comment by RoiArthurB** [comment]
:up: @hqnghi88 

As I told you previously, your implementation of SonarQube (software of code coverage used by SonarCloud) in Travis isn't perfect... 

If you look at SonarCloud when Travis is running, you'll see the project changing for the last package compiled and over-writing the previous project. 
So it's firstly `ummisco.gama.annotations`, after it's overwritten by `msi.gama.processor`, and it's finally overwritten by `msi.gama.parent`...

This problem comes from your `./travis/compile.sh` script which compile and install SonarQube in each directory. 
I think the command [`mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gama-platform_gama;`](https://github.com/gama-platform/gama/blob/b3fc47457393cb0da8fb583466e3622e4dbfd91c/travis/compile.sh#L6) should be run only one time at the root of the project and compile project after that normally

**Comment by hqnghi88** [comment]
Much easier by using different projectKey , fixed in e07b5d10a638d92623ca02c3c8720d36bccba93c

**Comment by RoiArthurB** [comment]
Well... It's maybe not clean, but at least it works ^^
Well done ^^

**Comment by hqnghi88** [comment]
What do you mean "be clean"?

**Comment by RoiArthurB** [comment]
It's better if everything could be in a single SonarCloud project. That way we would have statistics for the whole repo at one.

Also, we're missing some extra repo (like _travis/_ folder and scripts inside...)

**Comment by hqnghi88** [comment]
They are linked by a maven build so no ways a travis folder can be check by sonarcloud. And no, as it is linked with maven build, it must be 3 projects as we wont (unless it changes in future) combine annotation and processor in msi.parent.

**Comment by RoiArthurB** [comment]
> it must be 3 projects
Ok, I didn't know it, so it's perfect ^^

> no ways a Travis folder can be check by sonarcloud
Actually, SonarCloud can check shell scripts and stuff like that, so I could work on a script to run during Travis build and just check the content of this _travis/_ folder... But I don't know yet how to do if we have some other folder to scan... 
Maybe the simplest solution would be to move all these folders in a subfolder and run a sonarcloud analysis just for the content of this one... 🤔🤔🤔

**Comment by hqnghi88** [comment]
you mean validation of shell scripts syntax? or even execution? No idea and no interest in such direction, most of travis errors come from travis 's policy (it changes days by days). 
The important thing if you have any info, we will change soon to jdk 11, does sonarcloud in maven works well?

**Comment by RoiArthurB** [comment]
The idea is to cover 100% of the code in the repo, it's maybe not totally useless...

And yes, SonarCloud (and SonarQube software) supports JDK 11 (the openJDK and the oracleJDK, I don't know if you want to switch to the open one which could be a good idea from my point of view... Like the openJDK 8 is still free to update/download and everything) : https://github.com/SonarSource/sonar-scanner-maven/pull/47

**Comment by RoiArthurB** [comment]
I reopen this issue because there still exist a bug related to SonarCloud.

During the compilation process, Travis return the error ( https://travis-ci.org/gama-platform/gama around line 648 on every built) bellow :

```
[debug] execute contextualize
[ERROR] Unable to run check class org.sonar.java.se.SymbolicExecutionVisitor -  on file 'ummisco.gama.java2d/src/ummisco/gama/java2d/Java2DDisplaySurface.java', To help improve SonarJava, please report this problem to SonarSource : see https://www.sonarqube.org/community/
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at java.lang.Double.compareTo(Double.java:49)
	at org.sonar.java.se.checks.MinMaxRangeCheck.checkRangeInconsistencies(MinMaxRangeCheck.java:207)
	at org.sonar.java.se.checks.MinMaxRangeCheck.handleMinMaxInvocation(MinMaxRangeCheck.java:191)
	at org.sonar.java.se.checks.MinMaxRangeCheck.checkPostStatement(MinMaxRangeCheck.java:154)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:106)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:118)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.checks.NullDereferenceCheck.checkPostStatement(NullDereferenceCheck.java:210)
	at org.sonar.java.se.CheckerDispatcher.executePost(CheckerDispatcher.java:106)
	at org.sonar.java.se.CheckerDispatcher.addTransition(CheckerDispatcher.java:97)
	at org.sonar.java.se.ExplodedGraphWalker.enqueueHappyPath(ExplodedGraphWalker.java:734)
	at org.sonar.java.se.ExplodedGraphWalker.lambda$executeMethodInvocation$11(ExplodedGraphWalker.java:719)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.sonar.java.se.ExplodedGraphWalker.lambda$executeMethodInvocation$12(ExplodedGraphWalker.java:719)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.sonar.java.se.ExplodedGraphWalker.executeMethodInvocation(ExplodedGraphWalker.java:716)
	at org.sonar.java.se.ExplodedGraphWalker.visit(ExplodedGraphWalker.java:561)
	at org.sonar.java.se.ExplodedGraphWalker.execute(ExplodedGraphWalker.java:258)
	at org.sonar.java.se.ExplodedGraphWalker.visitMethod(ExplodedGraphWalker.java:218)
	at org.sonar.java.se.ExplodedGraphWalker.visitMethod(ExplodedGraphWalker.java:210)
	at org.sonar.java.se.SymbolicExecutionVisitor.execute(SymbolicExecutionVisitor.java:78)
	at org.sonar.java.se.SymbolicExecutionVisitor.visitNode(SymbolicExecutionVisitor.java:64)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:103)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:128)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:105)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:128)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:105)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:86)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.scanFile(SubscriptionVisitor.java:72)
	at org.sonar.java.se.SymbolicExecutionVisitor.scanFile(SymbolicExecutionVisitor.java:54)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:149)
	at org.sonar.java.model.VisitorsBridge.visitFile(VisitorsBridge.java:137)
	at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:90)
	at org.sonar.java.ast.JavaAstScanner.scan(JavaAstScanner.java:67)
	at org.sonar.java.JavaSquid.scanSources(JavaSquid.java:115)
	at org.sonar.java.JavaSquid.scan(JavaSquid.java:109)
	at org.sonar.plugins.java.JavaSquidSensor.execute(JavaSquidSensor.java:88)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:397)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:393)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:390)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:356)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy160.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:104)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
ok
return code 0
/home/travis/build/gama-platform/gama
The command "bash ./travis/compile.sh" exited with 0.
```

It looks like a bug from SonarQube compiler, but I haven't find anything revelant on internet about it and the error looks too simple to still exist... And if it's really a SonarQube bug, I need to have the simpliest bug reproduction to open an issue at SonarSources forum.

Can you help me to investigate the error please?

**Comment by AlexisDrogoul** [comment]
Is it ok now ? Can we close this issue ? And by the way, what does SonarCloud provide ?

**Comment by hqnghi88** [comment]
Dear Alexis, i think there is no change, it have always a stuck error exception like Arthur commented, and it seems to be a bug of sonarcloud,  the only possible solution i think is to debug the sonarcloud sourcecode, but... It seem to be a hard mission.

**Comment by RoiArthurB** [comment]
SonarCloud is the web free hosted of the software named [SonarQube](https://www.sonarqube.org/) which is an open-source platform for continuous inspection of code quality and performing automatic reviews with static analysis of code to detect bugs, code smells, and security vulnerabilities.

The bug main comes from the version error. Actually Travis is running the version 3.0.3, but the latest version of SonarScanner (the piece of software analyzing the code and returning this error) is the 4.2 (see [here](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/) )

---

A solution (if we want to keep that stuff) would be to go for another similar service provider. There's plenty and most of them are free to use for Open-Source projects (and some are not related to Travis and may display short report like the Travis' green mark next to the commit hash -see below-)
![image](https://user-images.githubusercontent.com/16764085/74582971-4c153580-4ffd-11ea-95f1-35d91f489ce9.png)
![image](https://user-images.githubusercontent.com/16764085/74582987-7ebf2e00-4ffd-11ea-997e-36a3bb722057.png)
