### ISSUE TITLE
CSV Editor

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2860]
**Describe the bug**
A csv file created from GAMA and edited in the CSV Editor cannot be read by GAMA.
Note that when it is open and save by a SublimeText, the file works fine.

**To Reproduce**
1. Create a csv file from GAMA (New > General ...) in the includes folder
2. Open it in GAMA with de CSV Editor, open the Text pane
3. Paste the following dataset inside the file:
```
0,0,0,0,0,0,0,0,0,0,0
0,0,0,1,1,1,1,1,0,0,0
0,0,1,1,0,0,0,1,1,0,0
0,1,1,0,0,0,0,0,0,0,0
0,1,1,0,0,1,1,1,1,0,0
0,0,1,1,0,0,1,1,1,0,0
0,0,0,1,1,1,1,0,1,0,0
0,0,0,0,0,0,0,0,0,0,0
``` 
4. Save the file. 
5. Look at the metadat associated to this file: `(11x1 | no header |delimiter ',' | unknown)`.
So the dimension is not well recognized and also the datatype.
6. Try to open this file from a GAMA model:
```
global {
	csv_file testFromGAMA0_csv_file <- csv_file("../includes/toto.csv");

	init {
		matrix data2 <- matrix(testFromGAMA0_csv_file);		
	}
}
```
7. Launch the model: I get the followgin Exception in Eclipse (and an error in GAMA):
```
Creation of main0
report error : The file toto.csv seems to contain data that have not been processed
java.lang.ArrayIndexOutOfBoundsException: 11
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
	at msi.gama.util.file.GamaCSVFile.createMatrixFrom(GamaCSVFile.java:438)
	at msi.gama.util.file.GamaCSVFile.fillBuffer(GamaCSVFile.java:350)
	at msi.gama.util.file.GamaFile.getContents(GamaFile.java:346)
	at msi.gama.util.file.GamaFile._matrixValue(GamaFile.java:422)
	at msi.gama.util.file.GamaFile.matrixValue(GamaFile.java:417)
	at msi.gama.util.file.GamaFile.matrixValue(GamaFile.java:411)
	at msi.gaml.types.GamaMatrixType.staticCast(GamaMatrixType.java:53)
	at msi.gaml.types.GamaMatrixType.cast(GamaMatrixType.java:67)
	at msi.gaml.types.GamaMatrixType.cast(GamaMatrixType.java:1)
	at msi.gaml.types.GamaContainerType.cast(GamaContainerType.java:42)
	at msi.gaml.types.GamaContainerType.cast(GamaContainerType.java:1)
	at msi.gaml.operators.Cast.as(Cast.java:170)
	at gaml.additions.GamlAdditions.lambda$946(GamlAdditions.java:1003)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:113)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:314)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:475)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:362)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:291)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:309)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:263)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:277)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:329)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
```
8. Now open the file with a Text editor (e.g. Sublime Text). 
9. Without modifying anything just resave it. When you run the model, no more exception.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8.0

**Comment by AlexisDrogoul** [comment]
The part that seems a bit strange in your manipulation comes from the
'pasting' of the data. It seems that the end of line is not correctly
recognized, or that you introduce strange characters when pasting. Have you
tried by normally creating the data?

Le mar. 20 août 2019 à 21:42, benoitgaudou <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
When I replace the previous step 3., by simply typing (with a normal ENTER key for the end of line),
I get the same trouble.
As an example I typed the following matrix:
```
1,4,1,6
3,2,5,6
1,1,1,1
```

I get wrong metadata (4x1  | .... | unknown) and Exception when opened from the GAML model.

**Comment by AlexisDrogoul** [comment]
The metadata is not properly updated, presumably. Does it work if, after all your step, you refresh the file ?

**Comment by benoitgaudou** [comment]
In fact, it seems that the refresh "solves" the issue.

When I write the file, and import it in a GAML model, I get the Exception.
But when I refresh the model, the metadata are correct, and no more exception....

**Comment by AlexisDrogoul** [comment]
I have added a fix, which should eliminate the problem (there might be some visual glitches regarding the file in the navigator, but they will be harmless). However, I think the best move to do would be to only provide a viewer (and not an editor) for CSV files.
