### ISSUE TITLE
Cannot start GAMA 1.9 (cant pick workspace)

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2862]
I tried to start develope gama 1.9 from git branch GAMA_1.9
Using jdk 11 and eclipse 1906, there is no critcal compilation errors, but when i launch product.runtime, i got this exception eclipse console and gama force closed.

> GAMA: Initializing preferences                       [Start Level: Equinox Container: f66d1bc6-32ee-4cad-80de-6fe41bfef9c0]in: 0ms
!SESSION 2019-08-21 15:46:04.594 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product msi.gama.application.runtime --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.runtime -data C:\Users\hqngh\eclipse-workspace1906/../runtime-gama.runtime.product -dev file:C:/Users/hqngh/eclipse-workspace1906/.metadata/.plugins/org.eclipse.pde.core/gama.runtime.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY org.eclipse.osgi 4 0 2019-08-21 15:46:05.890
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Display.error(Display.java:1186)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:738)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1405)
	at ummisco.gama.ui.PickWorkspaceDialog.<init>(PickWorkspaceDialog.java:82)
	at ummisco.gama.ui.utils.SwtGui.openPickWorkspaceDialog(SwtGui.java:742)
	at msi.gama.application.workspace.WorkspaceManager.checkWorkspace(WorkspaceManager.java:321)
	at msi.gama.application.Application.start(Application.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

gama git branch GAMA_1.9

**Comment by AlexisDrogoul** [comment]
Yep. For the moment, it's better to have a workspace ready... I will try to provide a fix soon.

**Comment by hqnghi88** [comment]
Dear Alexis,
Sorry, i saw your commit and test it but it gives an other message (still not launch)
> GAMA: Initializing preferences                       [Start Level: Equinox Container: c94acea1-ad66-4966-b550-28d103f7c64e]in: 0ms
!SESSION 2019-08-21 22:23:04.246 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product msi.gama.application.runtime --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.runtime -data C:\Users\hqngh\eclipse-workspace1906/../runtime-gama.runtime.product -dev file:C:/Users/hqngh/eclipse-workspace1906/.metadata/.plugins/org.eclipse.pde.core/gama.runtime.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY org.eclipse.osgi 4 0 2019-08-21 22:23:12.179
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:95)
	at ummisco.gama.ui.utils.WorkbenchHelper.getWorkbench(WorkbenchHelper.java:171)
	at ummisco.gama.ui.utils.WorkbenchHelper.getDisplay(WorkbenchHelper.java:126)
	at ummisco.gama.ui.utils.WorkbenchHelper.getShell(WorkbenchHelper.java:138)
	at ummisco.gama.ui.dialogs.Messages.confirm(Messages.java:31)
	at ummisco.gama.ui.utils.SwtGui.confirm(SwtGui.java:130)
	at msi.gama.application.workspace.WorkspaceManager.checkWorkspace(WorkspaceManager.java:309)
	at msi.gama.application.Application.start(Application.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by AlexisDrogoul** [comment]
Yep. Working on it...

**Comment by hqnghi88** [comment]
I just tried with newest commit and it works. Thanks.
