### ISSUE TITLE
Exception in display with multi-scale modeling of a dead agent 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2871]
**Describe the bug**
In the Incremental Model 6.gaml (on the GAMA Git version, branch master), when I run the model with a Proba infection set around 0.5, time to time I get the following exception in an aspect: GAMA seems to try to display a dead agents.

As agents do not really die, my guess is that this exception appears when GAMA tries to display an agent that has been captured by a building. 

GAML code:
```
species people {
	aspect sphere3D {
		draw sphere(3) at: {location.x, location.y, location.z + 3} color: is_infected ? #red : #green;
	}
}
```

```
java.lang.NullPointerException
	at gaml.additions.GamlAdditions.lambda$300(GamlAdditions.java:356)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:83)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.operators.Points.toPoint(Points.java:85)
	at gaml.additions.GamlAdditions.lambda$732(GamlAdditions.java:789)
	at msi.gaml.expressions.AbstractNAryOperator._value(AbstractNAryOperator.java:316)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.value(AttributeHolder.java:78)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.refresh(AttributeHolder.java:83)
	at msi.gaml.statements.draw.AttributeHolder.lambda$0(AttributeHolder.java:121)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at msi.gaml.statements.draw.AttributeHolder.refresh(AttributeHolder.java:121)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:323)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:191)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:254)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:308)
	at java.lang.Thread.run(Thread.java:748)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:58)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:90)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.operators.Points.toPoint(Points.java:85)
	at gaml.additions.GamlAdditions.lambda$732(GamlAdditions.java:789)
	at msi.gaml.expressions.AbstractNAryOperator._value(AbstractNAryOperator.java:316)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.value(AttributeHolder.java:78)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.refresh(AttributeHolder.java:83)
	at msi.gaml.statements.draw.AttributeHolder.lambda$0(AttributeHolder.java:121)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at msi.gaml.statements.draw.AttributeHolder.refresh(AttributeHolder.java:121)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:323)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:211)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:191)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:93)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:71)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:65)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:182)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:254)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at gaml.additions.GamlAdditions.lambda$300(GamlAdditions.java:356)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:83)
	... 31 more
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git, branch master

**Comment by AlexisDrogoul** [comment]
There are two options in GAMA to get rid of this:
1. **Synchronise the display** (this can be explained in the tutorial, btw) so that the birth and death of agents are synchronised with the drawing (i.e. an agent does not die while it is being drawn). This is the (best) solution to this problem. No other one can be provided.
2. **Set the preferences to not show the errors in displays** (this preference exists when you don't want to synchronise, for instance for performance reasons).
