### ISSUE TITLE
at operator on a color

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2873]
**Describe the bug**
The `at` operator on color seems to be perfectly accepted at the compilation step.
```
int r <-rgb(34,34,34) at 0;
```
but at the execution, I get an ClassCastException 
```
java.lang.ClassCastException: msi.gama.util.GamaColor cannot be cast to msi.gama.util.IContainer$Addressable
	at gaml.additions.GamlAdditions.lambda$958(GamlAdditions.java:1015)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:75)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:76)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:150)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.RemoteSequence.privateExecuteIn(RemoteSequence.java:45)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:260)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:275)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:209)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:314)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:475)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:362)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:291)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
```

**Desktop (please complete the following information):**
 - OS: mcOS
 - GAMA version: git - master

**Comment by AlexisDrogoul** [comment]
It's been a loooong time since colors could be manipulated like containers. The error is then normal. But I was surprised to see the compiler accepting this sentence. After a bit of digging, it appears that this error has revealed a gap in the validation of the `at` and `[..]` operators, which basically could be used for any type... The reason was simple: both were declared on the `IContainer.Addressable` java interface, which, despite its location, is not a sub interface of `Container`. So, with type erasing at compile time, the two methods were considered by GAMA as operating on `Object`s, not on `Container`s. 
I've fixed the error and added some basic validation regarding the type of indices used.
