### ISSUE TITLE
GAMA 1.8RC2 : trouble in running this GAMA version

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2876]
**Describe the bug**

I had hug trouble to run GAMA 1.8RC2: when I run it, the splash screen appears, then disappears and appears again ... and that continues like that infinitely.
When I run it from the console, the message loop over:
```
Bad value: "${target.nl}" for NL. Using system default.
```

I "fix" it (i.e. I was able to run GAMA1.8RC2) by launching GAMA, each time, with `./gama -clean`. (note that, even if I run it 1 time with -clean and another time without after, I still have the issue).

**To Reproduce**
I admit that I do not know how to reproduce it.
From the last successful run, I tried to launch GAMA 1.9, so I installed JDK 11. 
(but I still use the 1.8 version by default).

In addition, I have to problem to run the GAMA 1.8.0...

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8RC2
 - Java version: installed : JDK 1.8.0_181 and JDK 11 ; used by default : JDK 1.8.

**Comment by hqnghi88** [comment]
Hi Benoit,
Try one thing, place -vm to tell exactly the path to correct jdk version for each release. Even jdk1. 8 is used by default, some ghost variable still chose newest version or vice versa....

**Comment by benoitgaudou** [comment]
Hi,

I tried many ways to launch GAMA...
```
./Gama -vm /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/
```
(with and without the `-vm` option in the `Gama.ini` file)...

The only run that works is still using `./Gama -clean`...
Below an example of the error log.

```
!SESSION 2019-08-27 11:34:37.553 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=1.8.0_161
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault

!ENTRY org.eclipse.equinox.common 4 0 2019-08-27 11:34:38.328
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.common [2]
  Another singleton bundle selected: osgi.identity; type="osgi.bundle"; version:Version="3.10.300.v20190218-2100"; osgi.identity="org.eclipse.equinox.common"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:264)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:188)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:326)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2019-08-27 11:34:38.329
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.simpleconfigurator [3]
  Another singleton bundle selected: osgi.identity; type="osgi.bundle"; version:Version="1.3.200.v20181101-1115"; osgi.identity="org.eclipse.equinox.simpleconfigurator"; singleton:="true"
```

**Comment by AlexisDrogoul** [comment]
On macOS, the vm can also be indicated in the Info.plist companion file. What is strange is that you seem to specify java1.8 181, but it's java1.8 161 the appears in the log...

**Comment by AlexisDrogoul** [comment]
I close this issue as RC2 is a version we no longer support, right ?
