### ISSUE TITLE
Exception in BDI tutorial models

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2879]
**Describe the bug**
Run the fifth model of the BDI Tutorial. After some steps, an exception appears: `Can not execute ask on a  nil agent`.

It seems to come for the perceive / sanction blocks of the policeman species: 
```
	perceive target: miner in: view_dist {
		enforcement law:"working" sanction:"sanction_to_law";
		enforcement obligation:has_gold /*when:has_belief(has_gold)*/ sanction: "sanction_to_obligation" reward:"reward_to_obligation";
	}
	
	sanction sanction_to_law{
		ask agent_perceived{
			threshold_law <- 0.0;
			gold_sold <- gold_sold-5;
		}
		fine <- fine +5;
	}
```

The eclipse console exception is:
```
Can not execute ask on a nil agent
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:62)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:217)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.architecture.simplebdi.SanctionStatement.privateExecuteIn(SanctionStatement.java:35)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.architecture.simplebdi.EnforcementStatement.privateExecuteIn(EnforcementStatement.java:258)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.RemoteSequence.privateExecuteIn(RemoteSequence.java:45)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:260)
	at msi.gama.runtime.concurrent.GamaExecutorService.execute(GamaExecutorService.java:275)
	at msi.gaml.architecture.simplebdi.PerceiveStatement.privateExecuteIn(PerceiveStatement.java:195)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gaml.architecture.simplebdi.SimpleBdiArchitecture.executeOn(SimpleBdiArchitecture.java:364)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:236)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:204)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:208)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:203)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:415)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:98)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git master

**Comment by mathieuBourgais** [comment]
I do not have time right now to investigate this but ill be able to do it in 10 days.
