### ISSUE TITLE
replication of edges for spatial_graph from nodes

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2945]
In the current version of GAMA (git), when using operators such as "as_distance_graph", when two nodes (nodeA and nodeB) are closer than the given distance (operand), two edges are created nodeA -> nodeB and nodeB -> nodeA, and the graph returned is undirected.

Should we change that?

A simple model to see that:
```

model test_graph_operator

global {
	graph g;
	init {
		create dummy number:2;
		g <- as_distance_graph(dummy, 500);
		write g.edges; 
		
	}
}

species dummy skills: [moving]{
	aspect default {
		draw circle(1) color: #red;
	}
}
experiment testLink type: gui {
	output {
		display view {
			species dummy;
			graphics "view" {
				loop e over: g.edges {
					draw geometry(e) color: #black;
				}
				
			}
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
Sure. I didn't pay attention to this issue, but it is clearly a bug to make it the default. At least we should let the modeler specify it.

**Comment by AlexisDrogoul** [comment]
I've issued an implementation that does not create double edges anymore, with the idea that, if the modeller wants to create double edges, he/she can do it by hand after having created the graph. Please test !

**Comment by AlexisDrogoul** [comment]
My "fix" seems to have broken all the tests on graphs... Quite strange. Have you been able to test it yourself ?

**Comment by hqnghi88** [comment]
I have many errors in eclipse console when launching all test case from gama gui 👍 
java.lang.NullPointerException: Cannot invoke "msi.gama.kernel.simulation.SimulationAgent.getTopology()" because the return value of "msi.gama.runtime.IScope.getSimulation()" is null
reportAndThrowIfNeeded : Java error: nil value detected
	at msi.gama.metamodel.topology.AbstractTopology.setRoot(AbstractTopology.java:74)
	at msi.gama.metamodel.topology.AbstractTopology.<init>(AbstractTopology.java:67)
	at msi.gama.metamodel.topology.continuous.ContinuousTopology.<init>(ContinuousTopology.java:39)
	at msi.gama.metamodel.population.GamaPopulation.computeTopology(GamaPopulation.java:635)
	at msi.gama.metamodel.population.GamaPopulation.initializeFor(GamaPopulation.java:561)
	at msi.gama.kernel.simulation.SimulationAgent.getPopulationFor(SimulationAgent.java:485)
	at msi.gama.kernel.experiment.ExperimentAgent.getPopulationFor(ExperimentAgent.java:724)
	at msi.gaml.species.AbstractSpecies.getPopulation(AbstractSpecies.java:113)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:495)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:1)
	at msi.gaml.operators.Containers.internal_at(Containers.java:555)
	at gaml.additions.core.GamlAdditions.lambda$508(GamlAdditions.java:570)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:81)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:65)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:88)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.test.TestStatement.privateExecuteIn(TestStatement.java:141)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:442)
	at msi.gama.runtime.IScope.execute(IScope.java:567)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:106)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:99)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:442)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:234)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:259)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:451)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:196)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:94)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:111)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:208)
	at msi.gama.kernel.experiment.TestAgent.step(TestAgent.java:80)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:478)
	at msi.gama.kernel.experiment.ExperimentScheduler.lambda$0(ExperimentScheduler.java:135)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:135)
	at msi.gama.kernel.experiment.ExperimentScheduler.startThread(ExperimentScheduler.java:106)
	at msi.gama.kernel.experiment.ExperimentScheduler.start(ExperimentScheduler.java:200)
	at msi.gama.kernel.experiment.ExperimentController.processUserCommand(ExperimentController.java:132)
	at msi.gama.kernel.experiment.ExperimentController.offer(ExperimentController.java:99)
	at msi.gama.kernel.experiment.ExperimentController.userStart(ExperimentController.java:212)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:565)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:149)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runHeadlessTests(ModelRunner.java:108)
	at ummisco.gama.ui.utils.SwtGui.runHeadlessTests(SwtGui.java:389)
	at ummisco.gama.ui.commands.TestsRunner.lambda$0(TestsRunner.java:53)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at msi.gama.util.IList.get(IList.java:188)
	at msi.gama.util.GamaList.getFromIndicesList(GamaList.java:99)
	at msi.gama.metamodel.population.GamaPopulation.getFromIndicesList(GamaPopulation.java:938)
	at msi.gama.metamodel.population.GamaPopulation.getFromIndicesList(GamaPopulation.java:1)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:496)
	at msi.gaml.species.AbstractSpecies.getFromIndicesList(AbstractSpecies.java:1)
	at msi.gaml.operators.Containers.internal_at(Containers.java:555)
	at gaml.additions.core.GamlAdditions.lambda$508(GamlAdditions.java:570)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:81)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:65)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:80)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:65)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:88)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.test.TestStatement.privateExecuteIn(TestStatement.java:141)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:442)
	at msi.gama.runtime.IScope.execute(IScope.java:567)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:106)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:99)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:442)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:234)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:259)
	at msi.gama.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:451)
	at msi.gama.kernel.batch.ExhaustiveSearch.testSolutions(ExhaustiveSearch.java:196)
	at msi.gama.kernel.batch.ExhaustiveSearch.findBestSolution(ExhaustiveSearch.java:94)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.run(ParamSpaceExploAlgorithm.java:111)
	at msi.gama.kernel.experiment.BatchAgent.step(BatchAgent.java:208)
	at msi.gama.kernel.experiment.TestAgent.step(TestAgent.java:80)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:478)
	at msi.gama.kernel.experiment.ExperimentScheduler.lambda$0(ExperimentScheduler.java:135)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at msi.gama.kernel.experiment.ExperimentScheduler.step(ExperimentScheduler.java:135)
	at msi.gama.kernel.experiment.ExperimentScheduler.startThread(ExperimentScheduler.java:106)
	at msi.gama.kernel.experiment.ExperimentScheduler.start(ExperimentScheduler.java:200)
	at msi.gama.kernel.experiment.ExperimentController.processUserCommand(ExperimentController.java:132)
	at msi.gama.kernel.experiment.ExperimentController.offer(ExperimentController.java:99)
	at msi.gama.kernel.experiment.ExperimentController.userStart(ExperimentController.java:212)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:565)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:149)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runHeadlessTests(ModelRunner.java:108)
	at ummisco.gama.ui.utils.SwtGui.runHeadlessTests(SwtGui.java:389)
	at ummisco.gama.ui.commands.TestsRunner.lambda$0(TestsRunner.java:53)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
