### ISSUE TITLE
clean_network operator does not work with 3D shapfile

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2954]
**Describe the bug**
When I want to use the `clean_network` operator on a 3D shapefile I get an Exception.

See as an example in the attached model:
```
list<geometry> pathway_clean <- clean_network(bldg_pathways.contents,3.0,true,true);
```
where data from `bldg_pathways` are in 3D.
I get the following exception:

```
[GE 300 (2).zip](https://github.com/gama-platform/gama/files/4327789/GE.300.2.zip)

java.lang.IllegalArgumentException: Cannot compute the quadrant for two identical points location[44.148299999535084;43.82180000023246;7.0]
	at com.vividsolutions.jts.geomgraph.Quadrant.quadrant(Quadrant.java:92)
	at com.vividsolutions.jts.geomgraph.index.MonotoneChainIndexer.findChainEnd(MonotoneChainIndexer.java:104)
	at com.vividsolutions.jts.geomgraph.index.MonotoneChainIndexer.getChainStartIndices(MonotoneChainIndexer.java:89)
	at com.vividsolutions.jts.geomgraph.index.MonotoneChainEdge.<init>(MonotoneChainEdge.java:77)
	at com.vividsolutions.jts.geomgraph.Edge.getMonotoneChainEdge(Edge.java:127)
	at com.vividsolutions.jts.geomgraph.index.SimpleMCSweepLineIntersector.add(SimpleMCSweepLineIntersector.java:103)
	at com.vividsolutions.jts.geomgraph.index.SimpleMCSweepLineIntersector.add(SimpleMCSweepLineIntersector.java:97)
	at com.vividsolutions.jts.geomgraph.index.SimpleMCSweepLineIntersector.computeIntersections(SimpleMCSweepLineIntersector.java:72)
	at com.vividsolutions.jts.geomgraph.GeometryGraph.computeSelfNodes(GeometryGraph.java:354)
	at com.vividsolutions.jts.operation.relate.RelateComputer.computeIM(RelateComputer.java:93)
	at com.vividsolutions.jts.operation.relate.RelateOp.getIntersectionMatrix(RelateOp.java:138)
	at com.vividsolutions.jts.operation.relate.RelateOp.relate(RelateOp.java:83)
	at com.vividsolutions.jts.geom.Geometry.relate(Geometry.java:1030)
	at com.vividsolutions.jts.geom.Geometry.intersects(Geometry.java:781)
	at msi.gama.metamodel.shape.GamaShape.intersects(GamaShape.java:613)
	at msi.gaml.operators.Spatial$Transformations.connectLine(Spatial.java:3286)
	at msi.gaml.operators.Spatial$Transformations.clean(Spatial.java:3243)
	at gaml.additions.GamlAdditions.lambda$470(GamlAdditions.java:527)
	at msi.gaml.expressions.AbstractNAryOperator._value(AbstractNAryOperator.java:316)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:113)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:81)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:117)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:242)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:252)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:314)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:475)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:366)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:291)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:128)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:522)
	at msi.gama.kernel.experiment.ExperimentController.lambda$0(ExperimentController.java:94)
	at java.lang.Thread.run(Thread.java:748)
java.io.FileNotFoundException: /Users/ben/Dev/wsGAMA_git/.metadata/.plugins/org.eclipse.core.resources/.projects/Test/.markers.snap (No such file or directory)
```

**To Reproduce**
1. Run the attached model

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git
 - Java version: 1.8

**Comment by ptaillandier** [comment]
It will be very difficult to fix this one: the clean_network operators deeply relies on the JTS operators (i.e. intersects) that do not work in 3D...
