### ISSUE TITLE
Problem with agent menu and selection

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2967]
**Describe the bug**
When I run the attached model, the agent menu is blank. I cannot select a cell with the right click on the map either.
[nicolas.zip](https://github.com/gama-platform/gama/files/4452161/nicolas.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - GAMA version: git and official 1.8

**Comment by AlexisDrogoul** [comment]
Unfortunately, works for me on macOS... Maybe a Windows only problem (can someone confirm it?).


![image](https://user-images.githubusercontent.com/579256/78848434-ffb60700-7a3b-11ea-9608-619e0d3f4cf6.png)

![image](https://user-images.githubusercontent.com/579256/78848467-10ff1380-7a3c-11ea-9174-0cda8f0b121a.png)

**Comment by hqnghi88** [comment]
On my win
![image](https://user-images.githubusercontent.com/6105384/78849041-9a631580-7a3d-11ea-8b88-a8a6409c2704.png)
and no right click either

**Comment by hqnghi88** [comment]
Avec nouvel workspace, Jai ca quand import le projet:

Apr 09, 2020 8:46:37 AM org.geotools.util.logging.LoggingImagingListener errorOccurred
INFO: Problem occurs when computing a tile by the owner.
java.lang.IllegalArgumentException: Sourc and Destination image must have the same Bands
	at it.geosolutions.jaiext.piecewise.GenericPiecewiseOpImage.computeRect(GenericPiecewiseOpImage.java:249)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:969)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.RenderedOp.getTile(RenderedOp.java:2257)
	at sun.java2d.SunGraphics2D.drawTranslatedRenderedImage(SunGraphics2D.java:2820)
	at sun.java2d.SunGraphics2D.drawRenderedImage(SunGraphics2D.java:2707)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.paintImage(GridCoverageRenderer.java:1199)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.paint(GridCoverageRenderer.java:1132)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.paint(GridCoverageRenderer.java:1093)
	at org.geotools.renderer.lite.StreamingRenderer$RenderRasterRequest.execute(StreamingRenderer.java:3338)
	at org.geotools.renderer.lite.StreamingRenderer$PainterThread.run(StreamingRenderer.java:3511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


when i launch simu

org.eclipse.swt.SWTError: Item not added
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Menu.createItem(Menu.java:385)
	at org.eclipse.swt.widgets.MenuItem.<init>(MenuItem.java:88)
	at ummisco.gama.ui.menus.AgentsMenu.fillPopulationSubMenu(AgentsMenu.java:335)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingPopulationMenuItem(AgentsMenu.java:120)
	at ummisco.gama.ui.menus.AgentsMenu.createMenuForAgent(AgentsMenu.java:293)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingAgentMenuItem(AgentsMenu.java:62)
	at ummisco.gama.ui.menus.AgentsMenu.fillPopulationSubMenu(AgentsMenu.java:325)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingPopulationMenuItem(AgentsMenu.java:108)
	at ummisco.gama.ui.menus.AgentsMenu.createMenuForAgent(AgentsMenu.java:293)
	at ummisco.gama.ui.menus.AgentsMenu.fill(AgentsMenu.java:370)
	at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:150)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:731)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:813)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:475)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:468)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:500)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5148)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4797)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1502)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2152)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4867)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1502)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2152)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4867)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1502)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2152)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:126)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

**Comment by AlexisDrogoul** [comment]
@hqnghi88 could you try to find and copy here the corresponding lines (or put a breakpoint and understand what happens)  in Menu and Widget on SWT ? These classes are actually different on macOS and Windows...

**Comment by hqnghi88** [comment]
probably problem of number of item in menu, on win,
[log.txt](https://github.com/gama-platform/gama/files/4453608/log.txt)

**Comment by hqnghi88** [comment]
in Menu:
void createItem (MenuItem item, int index) {
	int count = OS.GetMenuItemCount (handle);
	if (!(0 <= index && index <= count)) error (SWT.ERROR_INVALID_RANGE);
	display.addMenuItem (item);
	/*
	* Bug in Windows.  For some reason, when InsertMenuItem()
	* is used to insert an item without text, it is not possible
	* to use SetMenuItemInfo() to set the text at a later time.
	* The fix is to insert the item with some text.
	*
	* Feature in Windows.  When an empty string is used instead
	* of a space and InsertMenuItem() is used to set a submenu
	* before setting text to a non-empty string, the menu item
	* becomes unexpectedly disabled.  The fix is to insert a
	* space.
	*/
	long /*int*/ hHeap = OS.GetProcessHeap ();
	long /*int*/ pszText = OS.HeapAlloc (hHeap, OS.HEAP_ZERO_MEMORY, 4);
	OS.MoveMemory (pszText, new char [] {' ', '\0'}, 4);
	MENUITEMINFO info = new MENUITEMINFO ();
	info.cbSize = MENUITEMINFO.sizeof;
	info.fMask = OS.MIIM_ID | OS.MIIM_TYPE | OS.MIIM_DATA;
	info.wID = item.id;
	info.dwItemData = item.id;
	info.fType = item.widgetStyle ();
	info.dwTypeData = pszText;
	boolean success = OS.InsertMenuItem (handle, index, true, info);
	if (pszText != 0) OS.HeapFree (hHeap, 0, pszText);
	if (!success) {
		display.removeMenuItem (item);
		error (SWT.ERROR_ITEM_NOT_ADDED);
	}
	redraw ();
}





in SWT (ERROR UNSPECIFIED)
/* SWT Errors (fatal, may occur only on some platforms) */
		case ERROR_FAILED_LOAD_LIBRARY:
		case ERROR_NO_MORE_CALLBACKS:
		case ERROR_NOT_IMPLEMENTED:
		case ERROR_UNSPECIFIED: {
			SWTError error = new SWTError (code, message);
			error.throwable = throwable;
			throw error;
		}

in Widget is just the line to throw SWT error

**Comment by hqnghi88** [comment]
Change Breakdown agents number would help
![image](https://user-images.githubusercontent.com/6105384/78851491-18c2b600-7a44-11ea-9319-849b24c5aee2.png)




![image](https://user-images.githubusercontent.com/6105384/78851449-05174f80-7a44-11ea-8425-5367e3abc5ed.png)

**Comment by AlexisDrogoul** [comment]
OK. Maybe we should think, then, on initialising it with a different number on Windows ?

**Comment by hqnghi88** [comment]
I dont know if this issue was on the old version, but it is really depend on the number of agents pop.
model test. This tiny model can reproduce this phenonmenon on win. So both
		int subMenuSize = GamaPreferences.Interface.CORE_MENU_SIZE.getValue();
and
			final int nb = size / subMenuSize + 1;
shoule be optimized for win.

global   {
	init {
		create A number:250000; 
	}
}
species A use_individual_shapes:false use_regular_agents:false use_neighbors_cache:false { }
experiment "test" type:gui { }

**Comment by tcquang** [comment]
Dear Nghi,
I can confirm this issue on Windows. It depends on the size of raster data
and memory of the PC.
Regards,
Quang

[image: image.png]

**Comment by AlexisDrogoul** [comment]
So, coming back to this bug and trying to understand, because I didn't find any reference to such a bug on the Eclipse Bugzilla site. 

Is it because GAMA create menus with too many submenus ? Or a problem with the items themselves ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Many submenus is easy to see as changing the breakdown threshold would help. Not really see "problem with the items", you means, some attributes of agent are wrong or...

**Comment by hqnghi88** [comment]
As in Quang ' comment, i see one point : the memory of pc, I did not test but can you @ptaillandier , if we increase the memory for gama, does it help without changing the breakdown number?

**Comment by ptaillandier** [comment]
Not a memory problem, I tested with "-Xmx30024m" and I still have the same issue.

**Comment by tcquang** [comment]
Dear Nghi,
I tested on my Mac with 6MB. It works well.
Regards,
Quang

**Comment by ptaillandier** [comment]
I tested with GAMA 1.8.2 and I still have the issue. 
it can be reproduced with this simple model:
```
model bugAgentMenu
grid cell width: 300 height: 300;
experiment bugAgMenu;
```

I get this error in the Eclipse console:
org.eclipse.swt.SWTError: Item not added
	at org.eclipse.swt.SWT.error(SWT.java:4901)
	at org.eclipse.swt.SWT.error(SWT.java:4790)
	at org.eclipse.swt.SWT.error(SWT.java:4761)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:432)
	at org.eclipse.swt.widgets.Menu.createItem(Menu.java:370)
	at org.eclipse.swt.widgets.MenuItem.<init>(MenuItem.java:88)
	at ummisco.gama.ui.menus.AgentsMenu.fillPopulationSubMenu(AgentsMenu.java:343)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingPopulationMenuItem(AgentsMenu.java:122)
	at ummisco.gama.ui.menus.AgentsMenu.createMenuForAgent(AgentsMenu.java:295)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingAgentMenuItem(AgentsMenu.java:64)
	at ummisco.gama.ui.menus.AgentsMenu.fillPopulationSubMenu(AgentsMenu.java:328)
	at ummisco.gama.ui.menus.AgentsMenu.cascadingPopulationMenuItem(AgentsMenu.java:110)
	at ummisco.gama.ui.menus.AgentsMenu.createMenuForAgent(AgentsMenu.java:295)
	at ummisco.gama.ui.menus.AgentsMenu.fill(AgentsMenu.java:374)

I tested with a value of 100 for the preference "Break down agents in menus every" and I still have the issue. With a value of 1000, I do not have it anymore... but of course it is a not very easy to navigate with a list of 1000 agents.

**Comment by ptaillandier** [comment]
It seems to work on my computer. Thanks!
