### ISSUE TITLE
[batch][headless] NPE once first simulation is over

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#297]
**Describe the bug**
When running a batch experiment through headless server I have a NullPointerException at the end of the first simulation of the batch:
```
java.lang.NullPointerException: Cannot invoke "gama.core.util.IList.get(int)" because "c" is null
	at gama.core.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:501)
	at gama.core.kernel.experiment.BatchAgent.createSimulation(BatchAgent.java:274)
	at gama.core.kernel.experiment.BatchAgent.launchSimulationsWithSolution(BatchAgent.java:327)
	at gama.core.kernel.batch.exploration.Exploration.explore(Exploration.java:198)
	at gama.core.kernel.batch.exploration.AExplorationAlgorithm.run(AExplorationAlgorithm.java:125)
	at gama.core.kernel.experiment.BatchAgent.step(BatchAgent.java:233)
	at gama.headless.core.Experiment.step(Experiment.java:144)
	at gama.headless.server.GamaServerExperimentJob.doStep(GamaServerExperimentJob.java:95)
	at gama.headless.server.GamaServerExperimentController.step(GamaServerExperimentController.java:260)
	at gama.headless.server.GamaServerExperimentController$MyRunnable.run(GamaServerExperimentController.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
And the whole experiment stops. The same experiment has no problem running in GUI mode.

**To Reproduce**
1. Start gama headless server
2. run this model:
```
model batchtest


global {
	bool end <- false;
	
	reflex e when:cycle=100{
		end <-true;
	}
}

experiment simulationBase type: batch until:end keep_simulations:true repeat:100 parallel:1  {
}
```
3. See error

**Expected behavior**
The experiment doesn't crash after the end of the first simulation

**Comment by lesquoyb** [comment]
I've found what generates the NPE: the flowstatus of the scope passed to `createAgent` at line 500 in `createSimulation` of `ExperimentAgent` (see [here](https://github.com/gama-platform/gama/blob/2024-06/gama.core/src/gama/core/kernel/experiment/ExperimentAgent.java#L493) is `DISPOSE`, so in the implementation (see [here](https://github.com/gama-platform/gama/blob/2024-06/gama.core/src/gama/core/kernel/simulation/SimulationPopulation.java#L130)) there's a test and if the scope is interrupted (which is the case if the flowStatus is `DISPOSE`) the whole method returns null, which creates our NPE later.

@chapuisk you recently reworked a bit the Exploration class that is involved (see the error stack) maybe you can have a look ?

**Comment by lesquoyb** [comment]
well maybe the problem is in the fetching of the parameters then because I have the default ones for parallelism:
![image](https://github.com/user-attachments/assets/02caa1f9-45be-4db9-9c9e-abf46d9d3261)
`pref_parallel_simulations_all `is false but `pref_parallel_simulations`is true, maybe there's a confusion here

**Comment by chapuisk** [comment]
Ok ! can you print the pref within your experiment? are we sure that server workspace is the exact same as the GUI one? do you have the same error when `parallel` facet is more than 1?

**Comment by chapuisk** [comment]
@lesquoyb can you explain further how you practically launch the experiment with the use of Gama server? so I can reproduce the issue and see what I can do !!!

**Comment by chapuisk** [comment]
Ok ! I spotted the bug, however I don't know how we should handle it.
To state it simply: server ask experiment to step > step of the experiment is to launch batch plan (100 simulations) > returns to server testing if end condition (the one specified in batch facet `until`) is met > it is not (to be clear it makes no sens in batch experiment) > step again experiment (has already done 100 simulations) > error
The part of the code responsible for this is [here](https://github.com/gama-platform/gama/blob/8d526b320ea9db78f1cf5a076a4d861f7cb51ebe/gama.headless/src/gama/headless/server/GamaServerExperimentController.java#L83). A workaround could be to test `if (exp.isBatch())` and do not step in that case... however it would break the repeat way to go (experiment batch step() means going to the next set of repeat). I don't know why but headless server workspace seems to have the `pref_parallel_simulation_all` to true, putting it to false is another workaround (but the issue will appear if pref is changed)

**Comment by lesquoyb** [comment]
@hqnghi88 I tried to refactor the use of executionThread in GamaServerExperiment as we talked together but the bug is still happening and unfortunately I don't really understand this part of the code, could you have a look please ?
The preference thing is another issue and it is actually "normal" it just needs to be documented

**Comment by hqnghi88** [comment]
If that block of runnable is not useful for batch agent, @lesquoyb  try to prevent it to launch in LoadCommand, line 130, by filter a condition on exp.isBatch(), of course we need then to call a step command from client to begin the job of batchagent, instead of "start" command (there is no background thread to loop the steps for batchAgent in gamaserver then)

**Comment by lesquoyb** [comment]
moving this for the next release as we can still run them with the headless -batch mode and it seems fairly complicated to fix properly in server rn
