### ISSUE TITLE
LocalSimulationRuntime does not seem to manage cores / threads efficiently

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2984]
**Describe the bug**
LocalSimulationRuntime is a class called by the headless part of GAMA to launch simulations. Sometimes, for instance with 16 cores available (and visible by GAMA and the runtime) and 16 simulations to run, only 4 cores are used... 

**Expected behavior**
That all cores are used, or at least the best combination of threads and cores. 

**Desktop (please complete the following information):**
 - OS: macOS, Windows, Ubuntu
 - GAMA version: git
 - Java version: 1.8

**Additional context**
LocalSimulationRuntime simply starts threads, without really managing them (for example like what is done in GamaExecutorService). It should be interesting to replace it with a more advanced version.

**Comment by AlexisDrogoul** [comment]
Please test with the new `ExecutorBasedSimulationRuntime` implementation.

**Comment by gnoubi** [comment]
Does it the LocalSimulationRuntime of headless?
If it is, the simulation is running with only one thread

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
@gnoubi What do you mean ?

**Comment by AlexisDrogoul** [comment]
@hqnghi88 are you using as part of your recent development on Gama Server ? Does it work well ?

**Comment by hqnghi88** [comment]
No for the current git. I used to push the experiment in this executor queue, but then i need to have different api of launch, play, pause, step, stop, So i manually create one thread per experiment. That what i need your review and possible refactoring.

**Comment by hqnghi88** [comment]
However, if a grid is in parallel, it seems to consume all cores
<img width="738" alt="image" src="https://user-images.githubusercontent.com/6105384/162249425-96b45529-0527-4d31-8f8a-e99f0e222c94.png">

**Comment by RoiArthurB** [comment]
I reopen this issue as I have the exact same issue when I set cores for GAMA Headless in Batch mode : 

```
$ bash gama-headless.sh -hpc 1 -batch Optimization ./samples/predatorPrey/predatorPrey.gaml
******************************************************************
* GAMA version 1.8.2                                             *
* http://gama-platform.org                                       *
* (c) 2007-2022 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
An error has occurred. See the log file
/home/roiarthurb/Documents/GAMA/gama/ummisco.gama.product/target/products/ummisco.gama.application.product/linux/gtk/x86_64/configuration/1651814755696.log.
Error in you command, here's the log :

!SESSION 2022-05-06 07:25:55.568 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=17.0.3
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application msi.gama.headless.id4 -hpc 1 -batch Optimization ./samples/predatorPrey/predatorPrey.gaml
Command-line arguments:  -application msi.gama.headless.id4 -data .workspace0 -hpc 1 -batch Optimization ./samples/predatorPrey/predatorPrey.gaml

!ENTRY org.eclipse.osgi 4 0 2022-05-06 07:25:56.812
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.setMaximumPoolSize(ThreadPoolExecutor.java:1670)
	at msi.gama.headless.runtime.ExecutorBasedSimulationRuntime.setNumberOfThreads(ExecutorBasedSimulationRuntime.java:79)
	at msi.gama.headless.runtime.Application.checkParameters(Application.java:245)
	at msi.gama.headless.runtime.Application.start(Application.java:316)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
	at org.eclipse.core.launcher.Main.main(Main.java:44)
```

**Desktop (please complete the following information):**
- OS: Linux
- GAMA version: git
- Java version: OpenJDK 17 LTS

**Comment by RoiArthurB** [comment]
I did not pulled the commit fixing this, sorry 🙈🙈🙈
