### ISSUE TITLE
Two runs in a row of a batch experiment makes GAMA unable to run any other experiment

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3091]
**Describe the bug**
After the launch of GAMA,  when I launch first a batch experiment and launch it again when the first experiment is finished.  The second experiment is not launched, an exception occurs in the Eclipse console. No other experiment can be launched.

**To Reproduce**
1. Launch GAMA
2. Launch the `explore_model` experiment in the model6.gaml in the  Luneray flu Tutorial.
3. When it is finished,  launch it a second time.
4. The second experiment is not  executed and  the following exception appears in the Eclipse console:
```
Adding object pool: Envelope 3D
Creation of explore_model0
java.lang.NullPointerException
	at msi.gama.runtime.ExecutionScope.copy(ExecutionScope.java:948)
	at msi.gama.runtime.GAMA.copyRuntimeScope(GAMA.java:349)
	at msi.gama.runtime.GAMA.run(GAMA.java:388)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.initParams(ParamSpaceExploAlgorithm.java:82)
	at msi.gama.kernel.batch.GeneticAlgorithm.<init>(GeneticAlgorithm.java:144)
	at gaml.additions.core.GamlAdditions.lambda$9(GamlAdditions.java:114)
	at msi.gaml.descriptions.SymbolProto.create(SymbolProto.java:241)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:751)
	at msi.gaml.descriptions.SymbolDescription.lambda$4(SymbolDescription.java:772)
	at msi.gaml.descriptions.SpeciesDescription.visitChildren(SpeciesDescription.java:885)
	at msi.gaml.descriptions.ExperimentDescription.visitChildren(ExperimentDescription.java:166)
	at msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:771)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:757)
	at msi.gaml.descriptions.SymbolDescription.lambda$4(SymbolDescription.java:772)
	at msi.gama.util.IMap.forEachValue(IMap.java:450)
	at msi.gaml.descriptions.ModelDescription.visitChildren(ModelDescription.java:361)
	at msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:771)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:757)
	at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:76)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.lambda$2(ModelRunner.java:156)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.findModel(ModelRunner.java:156)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runModel(ModelRunner.java:169)
	at msi.gama.lang.gaml.ui.editor.toolbar.OpenExperimentSelectionListener.widgetSelected(OpenExperimentSelectionListener.java:66)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at ummisco.gama.ui.controls.FlatButton.doButtonUp(FlatButton.java:141)
	at ummisco.gama.ui.controls.FlatButton.handleEvent(FlatButton.java:104)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at msi.gama.application.Application.start(Application.java:143)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

```
5. No other experiment can  be launched anymore.

Note  that if a gui experiment is launched before the first  batch or the second batch experiment, the issue does not appear.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git,  branch 1_8_2
 - Java version: JKDD Oracle 11

**Comment by AlexisDrogoul** [comment]
Hi,

Strange, I cant reproduce this bug. I've followed the exact same instructions but no exceptions are thrown. Can you show me your current preferences in case it might explain this discrepancy ? Esp. these ones : 

<img width="885" alt="Monosnap 2021-04-20 14-43-46" src="https://user-images.githubusercontent.com/579256/115357453-d8fde500-a1e6-11eb-90e9-e9c292e5f173.png">

**Comment by hqnghi88** [comment]
I can reproduce it:
- open model6
- click explore_model button
- play button, wait until finish
- stop button, it return to modeling perspective (or not, as the editor did not appear and the status bar still display)
![image](https://user-images.githubusercontent.com/6105384/115361830-29774180-a1eb-11eb-9dd6-f49b6538b449.png)
-open model6 from navigator
-click expore_model
And then Exception

Creation of explore_model0
java.lang.NullPointerException: Cannot invoke "msi.gama.runtime.AgentExecutionContext.createCopy()" because "this.agentContext" is null
	at msi.gama.runtime.ExecutionScope.copy(ExecutionScope.java:906)
	at msi.gama.runtime.GAMA.copyRuntimeScope(GAMA.java:349)
	at msi.gama.runtime.GAMA.run(GAMA.java:388)
	at msi.gama.kernel.batch.ParamSpaceExploAlgorithm.initParams(ParamSpaceExploAlgorithm.java:82)
	at msi.gama.kernel.batch.GeneticAlgorithm.<init>(GeneticAlgorithm.java:144)
	at gaml.additions.core.GamlAdditions.lambda$9(GamlAdditions.java:114)
	at msi.gaml.descriptions.SymbolProto.create(SymbolProto.java:241)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:751)
	at msi.gaml.descriptions.SymbolDescription.lambda$4(SymbolDescription.java:772)
	at msi.gaml.descriptions.SpeciesDescription.visitChildren(SpeciesDescription.java:885)
	at msi.gaml.descriptions.ExperimentDescription.visitChildren(ExperimentDescription.java:166)
	at msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:771)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:757)
	at msi.gaml.descriptions.SymbolDescription.lambda$4(SymbolDescription.java:772)
	at msi.gama.util.IMap.forEachValue(IMap.java:450)
	at msi.gaml.descriptions.ModelDescription.visitChildren(ModelDescription.java:361)
	at msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:771)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:757)
	at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:76)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.lambda$2(ModelRunner.java:156)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.findModel(ModelRunner.java:156)
	at msi.gama.lang.gaml.ui.utils.ModelRunner.runModel(ModelRunner.java:169)
	at msi.gama.lang.gaml.ui.editor.toolbar.OpenExperimentSelectionListener.widgetSelected(OpenExperimentSelectionListener.java:66)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:766)
	at ummisco.gama.ui.controls.FlatButton.doButtonUp(FlatButton.java:141)
	at ummisco.gama.ui.controls.FlatButton.handleEvent(FlatButton.java:104)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at msi.gama.application.Application.start(Application.java:143)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

**Comment by AlexisDrogoul** [comment]
OK. I can reproduce this last one (but not the first). Two fishy things (probably linked): 

1. closing the experiment does not bring back the editors (very strange)
2. launching the experiment again creates an error

**Comment by AlexisDrogoul** [comment]
The cause was a wrong thread access when disposing the interactive console view. Very strange. It should now be fixed.

**Comment by benoitgaudou** [comment]
Tested, and  it works!
