### ISSUE TITLE
UI lib is loaded during headless execution, causing crash/hang of GAMA 1.8.1

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#3096]
**Describe the bug**

Headless try to load an ui lib that need SWT during headless execution. 

```
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4924r25 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk-4924r25.so
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

```

My sh : 
```
exec java -cp ./GAMA/plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx2048m -Djava.awt.headless=true org.eclipse.core.launcher.Main -application msi.gama.headless.id4 -hpc 1 ./GAMA/doe.xml ./GAMA/result
```

Full stacktrace below : 

```!SESSION 2021-05-03 11:06:25.498 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=1.8.0_222
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application msi.gama.headless.id4 -hpc 1 ./GAMA/doe.xml ./GAMA/result
Command-line arguments:  -application msi.gama.headless.id4 -hpc 1 ./GAMA/doe.xml ./GAMA/result

!ENTRY org.eclipse.osgi 4 0 2021-05-03 11:08:04.762
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (158).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:836)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:765)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:39)
	at org.eclipse.osgi.internal.loader.sources.MultiSourcePackage.loadClass(MultiSourcePackage.java:35)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.createInjector(ModelingActivator.java:68)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.getInjector(ModelingActivator.java:56)
	at msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:53)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.emf.ecore.plugin.RegistryReader$PluginClassDescriptor.createInstance(RegistryReader.java:178)
	at org.eclipse.emf.ecore.plugin.RegistryReader$ResourceFactoryDescriptor.createFactory(RegistryReader.java:200)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.convert(ResourceFactoryRegistryImpl.java:92)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$2.delegatedGetFactory(ResourceSetImpl.java:458)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:144)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:85)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:431)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:423)
	at msi.gama.lang.gaml.resource.GamlResourceServices.getTemporaryResource(GamlResourceServices.java:262)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.getEObjectOf(GamlExpressionCompiler.java:1202)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:183)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:162)
	at msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:128)
	at msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:81)
	at msi.gaml.descriptions.BasicExpressionDescription.getDenotedType(BasicExpressionDescription.java:146)
	at msi.gaml.descriptions.StringBasedExpressionDescription.getDenotedType(StringBasedExpressionDescription.java:99)
	at msi.gaml.statements.Facets.getTypeDenotedBy(Facets.java:296)
	at msi.gaml.descriptions.SymbolDescription.getTypeDenotedByFacet(SymbolDescription.java:173)
	at msi.gaml.descriptions.SymbolDescription.getTypeDenotedByFacet(SymbolDescription.java:162)
	at msi.gaml.descriptions.SymbolDescription.computeType(SymbolDescription.java:476)
	at msi.gaml.descriptions.SymbolDescription.getGamlType(SymbolDescription.java:467)
	at msi.gaml.descriptions.ActionDescription.getShortDescription(ActionDescription.java:218)
	at msi.gaml.descriptions.ActionDescription.getTitle(ActionDescription.java:214)
	at msi.gama.lang.gaml.documentation.DocumentationNode.<init>(DocumentationNode.java:51)
	at msi.gama.lang.gaml.documentation.DocumentationTask.process(DocumentationTask.java:43)
	at msi.gama.lang.gaml.documentation.GamlResourceDocumenter$1.run(GamlResourceDocumenter.java:55)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4924r25 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk-4924r25.so
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:329)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:241)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:88)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:159)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:386)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:343)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808)
	... 68 more
Root exception:
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4924r25 in java.library.path
	no swt-pi4-gtk in java.library.path
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk-4924r25.so
	Can't load library: /home/2017016/sreyco01/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:329)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:241)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:88)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:159)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:386)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:343)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:815)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:808)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:765)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:39)
	at org.eclipse.osgi.internal.loader.sources.MultiSourcePackage.loadClass(MultiSourcePackage.java:35)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.createInjector(ModelingActivator.java:68)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.getInjector(ModelingActivator.java:56)
	at msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:53)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.emf.ecore.plugin.RegistryReader$PluginClassDescriptor.createInstance(RegistryReader.java:178)
	at org.eclipse.emf.ecore.plugin.RegistryReader$ResourceFactoryDescriptor.createFactory(RegistryReader.java:200)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.convert(ResourceFactoryRegistryImpl.java:92)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$2.delegatedGetFactory(ResourceSetImpl.java:458)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:144)
	at org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:85)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:431)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:423)
	at msi.gama.lang.gaml.resource.GamlResourceServices.getTemporaryResource(GamlResourceServices.java:262)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.getEObjectOf(GamlExpressionCompiler.java:1202)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:183)
	at msi.gama.lang.gaml.expression.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:162)
	at msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:128)
	at msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:81)
	at msi.gaml.descriptions.BasicExpressionDescription.getDenotedType(BasicExpressionDescription.java:146)
	at msi.gaml.descriptions.StringBasedExpressionDescription.getDenotedType(StringBasedExpressionDescription.java:99)
	at msi.gaml.statements.Facets.getTypeDenotedBy(Facets.java:296)
	at msi.gaml.descriptions.SymbolDescription.getTypeDenotedByFacet(SymbolDescription.java:173)
	at msi.gaml.descriptions.SymbolDescription.getTypeDenotedByFacet(SymbolDescription.java:162)
	at msi.gaml.descriptions.SymbolDescription.computeType(SymbolDescription.java:476)
	at msi.gaml.descriptions.SymbolDescription.getGamlType(SymbolDescription.java:467)
	at msi.gaml.descriptions.ActionDescription.getShortDescription(ActionDescription.java:218)
	at msi.gaml.descriptions.ActionDescription.getTitle(ActionDescription.java:214)
	at msi.gama.lang.gaml.documentation.DocumentationNode.<init>(DocumentationNode.java:51)
	at msi.gama.lang.gaml.documentation.DocumentationTask.process(DocumentationTask.java:43)
	at msi.gama.lang.gaml.documentation.GamlResourceDocumenter$1.run(GamlResourceDocumenter.java:55)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**To Reproduce**

Error don't appear in local (i have the needed swt library on my local computer) and only occur on cluster.
Not all execution crash, so it's hard to reproduce.

**Desktop (please complete the following information):**
 - GAMA version 1.8.1
 - Java version: openjdk version "1.8.0_222"

**Comment by AlexisDrogoul** [comment]
Would be interesting to understand which symbol GAMA wants to compile when it tries to load the ui module. Apparently, it's done through the Guice module, and due to these definitions in the (generated) plugin.xml of the language plugin:

```
	<!-- adding resource factories -->
	<extension
		point="org.eclipse.emf.ecore.extension_parser">
		<parser
			class="msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory:org.eclipse.xtext.resource.IResourceFactory"
			type="gaml">
		</parser>
	</extension>
	<extension
		point="org.eclipse.emf.ecore.extension_parser">
		<parser
			class="msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory:org.eclipse.xtext.resource.IResourceFactory"
			type="experiment">
		</parser>
	</extension>
```

The implementation of `ExecutableExtensionFactory`, necessary to inject the correct instances is in fact located in the ui module. And of course it shouldn't be there (but in the runtime module). 

Problem is: it is generated by XText. I will try to figure out if it can be moved without problems.

**Comment by AlexisDrogoul** [comment]
https://www.eclipse.org/forums/index.php/t/508681/
https://www.eclipse.org/forums/index.php/t/818736/

Seems that this bug is quite widespread. An important information in those discussions is that the use of a `.ui` XText plugin does not necessarily mean that a UI environment should be loaded.

**Comment by AlexisDrogoul** [comment]
@reyman Is it the stock 1.8.1 version that you are loading ? No additional plugin ?

**Comment by AlexisDrogoul** [comment]
Continuing to dig... I realize that the injector should not be created in that way in a headless environment, but through `msi.gama.headless.core.HeadlessSimulationLoader.preloadGAMA()`. So there is probably something to verify in how `GamlExecutableExtensionFactory` gets the Injector, especially in the following method:

```
	@Override
	protected Injector getInjector() {
		ModelingActivator activator = ModelingActivator.getInstance();
		return activator != null ? activator.getInjector(ModelingActivator.MSI_GAMA_LANG_GAML_GAML) : null;
	}
```

Maybe a test about being headless that would then delegate to `preloadGAMA()` ? I will try and commit some trial fixes.

**Comment by reyman** [comment]
> @reyman Is it the stock 1.8.1 version that you are loading ? No additional plugin ?

Yes this is the stock version without plugin.
