### ISSUE TITLE
Black screen when drawing a string in Keystone mode on OpenGL

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3125]
Tested with this simple model :

model NewModel

global {
}

experiment exp {
	output {
		display map type: opengl keystone: [{0.0, 0.0, 0.0}, {-0.0026638499113079417, 1.005268058792359, 0.0}, {1.0026638499113079, 1.021072235169437, 0.0}, {1.0, 0.0, 0.0}] {
			graphics ssss {
				draw string("dd-MM-yyyy") at: {50, 50} color: (#black) font: font("Helvetica", 18, #bold);
				draw circle(30) at: {50, 50} color: #red;
			}
		}
	}
}
We got this exception in eclipse console:

Runtime error array vertex_buffer_object must be unbound to call this method in OpenGL loop
com.jogamp.opengl.GLException: array vertex_buffer_object must be unbound to call this method
	at jogamp.opengl.gl4.GL4bcImpl.checkBufferObject(GL4bcImpl.java:40603)
	at jogamp.opengl.gl4.GL4bcImpl.checkArrayVBOUnbound(GL4bcImpl.java:40619)
	at jogamp.opengl.gl4.GL4bcImpl.glVertexPointer(GL4bcImpl.java:6344)
	at ummisco.gama.opengl.scene.StringDrawerHelper$FaceBuffer.drawOn(StringDrawerHelper.java:307)
	at ummisco.gama.opengl.scene.StringDrawerHelper.drawOn(StringDrawerHelper.java:135)
	at ummisco.gama.opengl.scene.StringDrawer.draw(StringDrawer.java:108)
	at ummisco.gama.opengl.scene.StringDrawer._draw(StringDrawer.java:75)
	at ummisco.gama.opengl.scene.StringDrawer._draw(StringDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:29)
	at ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:106)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawObjects(LayerObject.java:241)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawAllObjects(LayerObject.java:229)
	at ummisco.gama.opengl.scene.layers.LayerObject.lambda$2(LayerObject.java:183)
	at ummisco.gama.opengl.OpenGL.compileAsList(OpenGL.java:882)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawWithoutShader(LayerObject.java:183)
	at ummisco.gama.opengl.scene.layers.LayerObject.draw(LayerObject.java:142)
	at ummisco.gama.opengl.scene.ModelScene.lambda$1(ModelScene.java:87)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:84)
	at ummisco.gama.opengl.renderer.helpers.SceneHelper.draw(SceneHelper.java:209)
	at ummisco.gama.opengl.renderer.JOGLRenderer.display(JOGLRenderer.java:187)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:161)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:173)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:975)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:674)
	at ummisco.gama.opengl.view.SWTGLAnimator.displayGL(SWTGLAnimator.java:201)
	at ummisco.gama.opengl.view.SWTGLAnimator.run(SWTGLAnimator.java:182)
	at java.base/java.lang.Thread.run(Thread.java:832)

If we comment the draw string statement, it works normally with transformed display by keystone.

GAMA git 1.8.2
windows 10 64 bit.
nvidia 1660 gpu

**Comment by AlexisDrogoul** [comment]
Same happens (logically) with the new MeshDrawer. Run any of the models with fields/mesh (and grid display also) and enter keystone. Trying to refresh the screen with keystone on creates the error.

**Comment by AlexisDrogoul** [comment]
I have programmed a fix (not very pretty, but it does the job) that allows to have text+mesh in keystone. I will commit it a bit later as I need more testing on other linked components.

**Comment by AlexisDrogoul** [comment]
This has been fixed in the latest commit.
