### ISSUE TITLE
GAMA crashes when starting a GUI experiment

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3164]
**Describe the bug**
Sometimes GAMA would crash when I start a GUI experiment (only 1 openGL display). Here's the error message when it crashes:
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:725: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
Occasionally this exception would also pop up, but does not cause GAMA to crash:
```
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
	at java.base/java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.acquireViewLock(LayeredDisplayView.java:366)
	at ummisco.gama.ui.views.displays.LayeredDisplayView.lambda$0(LayeredDisplayView.java:341)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
~This doesn't happen when setting `LayeredDisplayView.OLD_SYNC_STRATEGY = true`, as suggested in 7954606ed3a2d67845f2100805efd1040e55193e.~

**To Reproduce**
I don't know how to reproduce this reliably yet.

**Desktop (please complete the following information):**
 - OS: Linux 5.13.7-arch1-1 x86_64 GNU/Linux
 - PC Model: Acer Aspire A5
 - GAMA version: git
 - Java version: AdoptOpenJDK 15.0.2
 - Graphics cards / Display system: Intel UHD Graphics 620 / XWayland

**Comment by AlexisDrogoul** [comment]
What is this `XInitThreads` thing ? There seems to be some longstanding bugs and issues with this command and JOGL, but it is supposed to be now unnecessary to call since almost 10 years ... (last post was in 2012 !). 
There are also other suspects here: https://stackoverflow.com/questions/60187422/lwjglxcb-crashes-randomly 
And one I found for Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568859

The "old" sync strategy used `synchronized` methods to synchronise the different threads (simulation thread, update thread and rendering thread), effectively blocking some of them, while the new one opens the possibility to have unrelated threads (like simulation and rendering)  run in parallel, provided they only share "concurrency enabled" structures (a view is NOT one of them). Does your display use an image (jpg / png) ? That could be one of the examples of these non concurrent structures.

**Comment by minhduc0711** [comment]
> What is this XInitThreads thing ?

Sorry, I don't know what it is. I'm using XWayland, so I will rerun GAMA on actual Xorg to see if it still happens.
> Does your display use an image (jpg / png) ?
No, I just used pure GAMA shapes.

**Comment by AlexisDrogoul** [comment]
It is probably a coincidence, as this latest commit has nothing to do with displays. Or it is simply the fact that the balance between threads is perturbed by this removal of synchronised here... I would bet that the error only manifests from time to time, right? Probably due to a bad random combination of threads. Have you observed it before ? Does it happen with Java2D displays too ? 

In the meantime, I will check what has been modified in https://github.com/gama-platform/gama/commit/7954606ed3a2d67845f2100805efd1040e55193e that could explain the appearance of this error (where could 2 threads update the same display, for instance ?)

**Comment by RoiArthurB** [comment]
I don't have any issue with the latest build of GAMA 1.8.2 🤷🤷🤷
Here's the full of me launch it and running `MondrianGenerator` in `opengl` mode (I removed Gtk Warning)
![image](https://user-images.githubusercontent.com/16764085/129145022-0109dbcd-9660-46aa-93cd-28c5b8ea2643.png)
```
./Gama     
> GAMA: version 1.8.2                         loading on____ linux 5.13.8-1-MANJARO, x86_64, JDK 15.0.2
> JAI : ImageIO extensions                    loaded for____ jpg||tiff|bmp|gif|arx|tf8|TF8|png|ppm|jp2|asc|tif|TIF|TIFF|btf|BTF|pgm|wbmp|jpeg|pbm
> GAMA: msi.gama.core                         loaded in_____ 1848ms
> GAMA: irit.gaml.extensions.database         loaded in_____ 17ms
> GAMA: msi.gama.headless                     loaded in_____ 5ms
> GAMA: ummisco.gama.serialize                loaded in_____ 6ms
> GAMA: simtools.gaml.extensions.traffic      loaded in_____ 52ms
> GAMA: msi.gaml.architecture.simplebdi       loaded in_____ 128ms
> GAMA: msi.gaml.extensions.fipa              loaded in_____ 17ms
> GAMA: native Bullet library                 loaded in_____ 14ms
> GAMA: simtools.gaml.extensions.physics      loaded in_____ 30ms
> GAMA: ummisco.gaml.extensions.maths         loaded in_____ 17ms
> GAMA: msi.gama.lang.gaml                    loaded in_____ 3ms
> GAMA: ummisco.gama.opengl                   loaded in_____ 9ms
> GAMA: ummisco.gama.network                  loaded in_____ 6ms
> GAMA: ummisco.gaml.extensions.stats         loaded in_____ 22ms
> GAMA: ummisco.gama.java2d                   loaded in_____ 2ms
> GAMA: espacedev.gaml.extensions.genstar     loaded in_____ 5ms
> GAMA: miat.gaml.extension.pedestrian        loaded in_____ 26ms
> GAMA: all plugins                           loaded in_____ 2257ms

(Gama Platform:771473): GLib-GObject-WARNING **: 12:41:09.679: ../glib/gobject/gsignal.c:3598: signal name 'attributes-changed' is invalid for instance '0x7fba10c68560' of type 'GtkContainerAccessible'

(Gama Platform:771473): GLib-GObject-WARNING **: 12:41:09.679: ../glib/gobject/gsignal.c:3598: signal name 'text_changed::delete' is invalid for instance '0x7fba10c68560' of type 'GtkContainerAccessible'

(Gama Platform:771473): GLib-GObject-WARNING **: 12:41:09.679: ../glib/gobject/gsignal.c:3598: signal name 'text_changed::insert' is invalid for instance '0x7fba10c68560' of type 'GtkContainerAccessible'

Follow OS Theme: true
Follow OS Theme: true

 GAMA: GAML artefacts                        built in______ 737ms

 GAMA: preferences                           loaded in_____ 4258ms

Tree root = 0 weight null
Anisotropic level: 16.0
--------------------------------------------------------------------------------
---------- RESHAPING TO 1339X885 -----------------------------------------------
--------------------------------------------------------------------------------
Camera zoom level                  1.0
Size of env in units               100.0 | 100.0
Ratio width/height in units        1.0
Initial Size of env in pixels      1035.3504638671875 | 808.350341796875
Size of env in pixels              731.700927734375 | 731.70068359375
Ratio width/height in pixels       1.000000333661879
Window pixels/env pixels           1.8299826462514601 | 1.2095109651303317
Current XRatio pixels/env in units 7.31700927734375 | 7.3170068359375
Device Zoom =  100
AutoScale down =  1339 885
--------------------------------------------------------------------------------
---------- RESHAPING TO 1339X867 -----------------------------------------------
--------------------------------------------------------------------------------
Camera zoom level                  1.0
Size of env in units               100.0 | 100.0
Ratio width/height in units        1.0
Initial Size of env in pixels      1027.909423828125 | 791.9093017578125
Size of env in pixels              716.81884765625 | 716.818603515625
Ratio width/height in pixels       1.0000003405891307
Window pixels/env pixels           1.8679754367202641 | 1.2095110195910275
Current XRatio pixels/env in units 7.1681884765625 | 7.16818603515625
Device Zoom =  100
AutoScale down =  1339 867
--------------------------------------------------------------------------------
---------- RESHAPING TO 1339X885 -----------------------------------------------
--------------------------------------------------------------------------------
Camera zoom level                  1.0
Size of env in units               100.0 | 100.0
Ratio width/height in units        1.0
Initial Size of env in pixels      1035.3504638671875 | 808.350341796875
Size of env in pixels              731.700927734375 | 731.70068359375
Ratio width/height in pixels       1.000000333661879
Window pixels/env pixels           1.8299826462514601 | 1.2095109651303317
Current XRatio pixels/env in units 7.31700927734375 | 7.3170068359375
Device Zoom =  100
AutoScale down =  1339 885
```

And here's my laptop config (interesting points) : 
```
System:    Kernel: 5.13.8-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 
[...]
Graphics:  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: Dell driver: i915 v: kernel 
           bus-ID: 00:02.0 chip-ID: 8086:9b41 class-ID: 0300 
           Device-2: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo bus-ID: 1-5:2 
           chip-ID: 0c45:6723 class-ID: 0e02 
           Display: x11 server: X.Org 1.20.13 driver: loaded: intel display-ID: :0 screens: 1 
           Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2") 
           s-diag: 582mm (22.9") 
           Monitor-1: eDP1 res: 1920x1080 hz: 60 dpi: 168 size: 290x170mm (11.4x6.7") 
           diag: 336mm (13.2") 
           OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.1.6 
           direct render: Yes 
---
$ java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

**Comment by minhduc0711** [comment]
My bad, I just did some backtracking and the issue actually starts appearing since a8a15eac3a99d5066d6be1946eb2a4010325dfca, not 7954606ed3a2d67845f2100805efd1040e55193e.

Sometimes I get the old `XInitThreads` error message from earlier, and sometimes I get this new one:
```
Nativewindow X11 IOError: Display 0x7f2780bd6f40 (:0): Resource temporarily unavailable
FATAL ERROR in native method: Nativewindow X11 IOError: Display 0x7f2780bd6f40 (:0): Resource temporarily unavailable
	at org.eclipse.swt.internal.gtk.GDK.gdk_window_get_origin(Native Method)
Nativewindow X11 IOError: Display 0x7f2780bd6f40 (:0): Resource temporarily unavailable
	at org.eclipse.swt.widgets.Control.getWindowOrigin(Control.java:6844)
	at org.eclipse.swt.widgets.Display.mapInPixels(Display.java:4094)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:220)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6816)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6077)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1537)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4568)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.ui.internal.Workbench$$Lambda$2221/0x0000000800d1ac38.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at msi.gama.application.Application.start(Application.java:143)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@15.0.2/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@15.0.2/NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15.0.2/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@15.0.2/Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```

**Comment by AlexisDrogoul** [comment]
Any hints on whether or not going back to the old Animator helps ?

**Comment by minhduc0711** [comment]
Yes, the crash does not happen anymore if I use the old animator.

**Comment by AlexisDrogoul** [comment]
OK. The single-threaded animator will then be used on Linux and the multi-threaded ones in the other OSes since Linux doesn't seem to correctly handle this. I've committed the changes already.

**Comment by minhduc0711** [comment]
Thank you!
