### ISSUE TITLE
Problem with inspector

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3175]
**Describe the bug**
Sorry very limited information here but this is what I see when trying to inspect an agent (using a pedestrian skill) (the picking is working but there is a problem with the inspection).

here is the message error I hope it helps
<img width="1792" alt="Screenshot 2021-09-03 at 18 43 25" src="https://user-images.githubusercontent.com/3928502/132040302-f60cf92c-7669-42f7-a705-37438daa0800.png">

java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "msi.gama.metamodel.agent.IAgent.getAttribute(String)" is null
	at simtools.gaml.extensions.traffic.DrivingSkill.getLeadingDistance(DrivingSkill.java:940)
	at gaml.additions.traffic.GamlAdditions.lambda$81(GamlAdditions.java:113)
	at msi.gaml.compilation.GamaHelper.run(GamaHelper.java:55)
	at msi.gaml.compilation.IGamaHelper.run(IGamaHelper.java:35)
	at msi.gaml.variables.Variable.value(Variable.java:654)
	at msi.gama.metamodel.agent.AbstractAgent.getDirectVarValue(AbstractAgent.java:403)
	at msi.gama.runtime.ExecutionScope.getAgentVarValue(ExecutionScope.java:637)
	at ummisco.gama.ui.parameters.AbstractEditor.retrieveValueOfParameter(AbstractEditor.java:149)
	at ummisco.gama.ui.parameters.AbstractEditor.<init>(AbstractEditor.java:98)
	at ummisco.gama.ui.parameters.ExpressionBasedEditor.<init>(ExpressionBasedEditor.java:44)
	at ummisco.gama.ui.parameters.NumberEditor.<init>(NumberEditor.java:43)
	at ummisco.gama.ui.parameters.FloatEditor.<init>(FloatEditor.java:28)
	at ummisco.gama.ui.parameters.EditorFactory.create(EditorFactory.java:124)
	at ummisco.gama.ui.experiment.parameters.AgentAttributesEditorsList.add(AgentAttributesEditorsList.java:61)
	at ummisco.gama.ui.views.inspectors.AgentInspectView.addItem(AgentInspectView.java:156)
	at ummisco.gama.ui.views.inspectors.AgentInspectView.ownCreatePartControl(AgentInspectView.java:88)
	at ummisco.gama.ui.views.GamaViewPart.createPartControl(GamaViewPart.java:188)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

**Comment by AlexisDrogoul** [comment]
The inspector does not probably play any role here, it seems to be a problem coming from the DrivingSkill, which returns `null` for a `float` value.

**Comment by AlexisDrogoul** [comment]
I have nevertheless reinforced a bit the handling of exceptions in the parameter editors (2bed20aa955f9afa47d61375886ad61ed08a380e)

**Comment by ptaillandier** [comment]
I fixes the issue with the driving skill. Could you test it?

**Comment by agrignard** [comment]
OK it's ok now. I close this issue
