### ISSUE TITLE
"Show as wireframe" does not seem to work in OpenGL displays

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#3299]
**Describe the bug**
OpenGL displays have a control named "Show as wireframe" in their side controls. Pushing it either produces strange results or produces an error when a mesh is being drawn. 

**To Reproduce**
1. Open any model with an OpenGL display
2. Launch it and, in the display, reveal the side controls 
3. Click on "show as wireframe"
4. See result (not looking like a wireframe) or, if a mesh layer is being defined, see this error appearing in the console (in developer mode):
```
Runtime error Cannot invoke "java.nio.DoubleBuffer.put(double[])" because "this.lineColorBuffer" is null in OpenGL loop
java.lang.NullPointerException: Cannot invoke "java.nio.DoubleBuffer.put(double[])" because "this.lineColorBuffer" is null
	at ummisco.gama.opengl.scene.mesh.MeshDrawer.colorize(MeshDrawer.java:260)
	at ummisco.gama.opengl.scene.mesh.MeshDrawer.fillBuffers(MeshDrawer.java:235)
	at ummisco.gama.opengl.scene.mesh.MeshDrawer._draw(MeshDrawer.java:153)
	at ummisco.gama.opengl.scene.mesh.MeshDrawer._draw(MeshDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:51)
```

**Expected behavior**
That the shapes appear as wireframe -- and no error of course !

**Screenshots**
<img width="689" alt="Newt Window 2022-02-06 12-57-19" src="https://user-images.githubusercontent.com/579256/152669606-411c152b-0ac3-4cb1-ad45-8bb2df9ec051.png">
<img width="682" alt="Newt Window 2022-02-06 12-56-48" src="https://user-images.githubusercontent.com/579256/152669610-25e7da05-c05c-4ecf-b121-fbf09e668d4e.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - PC Model: MacBook Pro 16" (Intel)
 - GAMA version: git / 1.8.2
 - Java version: JDK 17 (Adoptium)
 - Graphics cards / Display system: AMD Radeon Pro 5500M

**Comment by AlexisDrogoul** [comment]
I committed a fix for this issue. For an unknown reason, the  `GL_LINE / GL_FILL` properties of `glPolygonMode(GL.GL_FRONT_AND_BACK,...);` seems to be altered outside of the drawings done by GAMA. Fixing it however means changing the mode quite often, which might have an impact on large drawings. For mesh layers, the cause was that the change of property at the display level was not reflected in the MeshDrawer : the buffer containing line colors was not correctly initialized.
