### ISSUE TITLE
Problem with 2 OpenGL displays in fullscreen on one monitor

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3337]
**Describe the bug**
I know it doesn't make sense to run this experiment however I am wandering if GAMA can handle this configuration by itself instead of having to force quit the application. Mayve it can be at least a warning when the experiment is launch saying that there is only one screen etc

The settings is the following:
- A model with 2 display in fullscreen 0 and 1 (for instance just add this to Tutorials/Road Traffic/Model 01.gaml
````
experiment road_traffic type: gui {
	parameter "Shapefile for the buildings:" var: shape_file_buildings category: "GIS" ;
	parameter "Shapefile for the roads:" var: shape_file_roads category: "GIS" ;
	parameter "Shapefile for the bounds:" var: shape_file_bounds category: "GIS" ;
		
	output {
		display city_display type:opengl fullscreen:0{
			species building aspect: base ;
			species road aspect: base ;
		}
		
		display city_display2 type:opengl fullscreen:0{
			species building aspect: base ;
			species road aspect: base ;
		}
	}
}
```` 

**To Reproduce**
Run this model from a laptop with only one screen and you can see that you cannot escape full screen (unless you press on the red cross if the toolbar is available (if there is no toolbar you have to use force quit)

**Expected behavior**
I'd like to be able to escape the fullscreen by pressing ```esc```

**Desktop (please complete the following information):**
- Mac OS
-  GAMA 1.8.2

**Comment by agrignard** [comment]
Might be link with #3341

**Comment by agrignard** [comment]
Doesn't seem to work.

Step to reproduce on a Desktop Computer (without an external screen) 
1. Open this model ```Tutorials/Road Traffic/Model 01.gaml```
2. Change the existing experiment ```road_traffic``` by this one and I still cannot esc this mode
`````
experiment road_traffic type: gui {
	parameter "Shapefile for the buildings:" var: shape_file_buildings category: "GIS" ;
	parameter "Shapefile for the roads:" var: shape_file_roads category: "GIS" ;
	parameter "Shapefile for the bounds:" var: shape_file_bounds category: "GIS" ;
		
	output {
		display city_display type:opengl fullscreen:0{
			species building aspect: base ;
			species road aspect: base ;
		}
		
		display city_display2 type:opengl fullscreen:1{
			species building aspect: base ;
			species road aspect: base ;
		}
	}
}

`````
3. Lanch the experiment 




On my configuration this is how looks my screen once the simulation is launch 
<img width="1440" alt="Screenshot 2022-05-06 at 10 32 14" src="https://user-images.githubusercontent.com/3928502/167062674-aea0771b-d698-4ff9-9bab-eeedf5cdb0c2.png">


And this is what I have in the eclipse console 
`````
Part Opened:city_display
Part Opened:city_display2
Show toolbar city_display true
Registered ummisco.gama.opengl.view.OpenGLDisplayView@44e4fa97 as fullscreen on Monitor 0
Show toolbar city_display2 true
Impossible to register ummisco.gama.opengl.view.OpenGLDisplayView@6e6b556d as fullscreen on Monitor 0
Tree root = stack weight null
Uncaught exception in animator & drawable:Caught ThreadDeath: null on thread Animator thread
com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread Animator thread
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at ummisco.gama.opengl.view.GamaGLAnimator.run(GamaGLAnimator.java:169)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:942)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:747)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:742)
	at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:658)
	at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:124)
	at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:76)
	at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:342)
	at com.jogamp.nativewindow.NativeWindowFactory$1$1.run(NativeWindowFactory.java:247)
	... 1 more
`````


CONFIGURATION WITH ONE MACBOOK + ONE EXTERNAL DISPLAY I get this

1. On my Macbook Screen

<img width="1439" alt="Screenshot 2022-05-06 at 10 38 44" src="https://user-images.githubusercontent.com/3928502/167063226-42cc390f-fdfb-42fa-986e-4fd706252475.png">

2. And this on the external display 
![Screenshot 2022-05-06 at 10 38 36](https://user-images.githubusercontent.com/3928502/167063248-0b9b3195-e584-4e5a-a288-4f493cacfc8b.png)

**Comment by agrignard** [comment]
Working too!
