### ISSUE TITLE
Error while generating documentation XML files from JAVA code

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3349]
**Describe the bug**
GAMA's source code fail to generate inbuild documentation XML file used to create online website documentation

**To Reproduce**
1. Compile GAMA software
2. Move to `msi.gama.documentation` folder
3. Launch following java command `java -cp ".:libs/jdom-2.0.1.jar:target/classes:../ummisco.gama.annotations/target/classes"  msi.gama.doc.MainGenerateWiki -online` (cf. [publish.sh script](https://github.com/gama-platform/gama/blob/GAMA_1.8.2/travis/publish.sh#L10))
4. See [error log from Gh Actions](https://github.com/gama-platform/gama/runs/6061377594?check_suite_focus=true#step:6:91) : 
```
GENERATION OF THE XML CATEGORY FILES FROM XML docGAMA.xml
Please notice that the docGAMA.xml files should have been previously generated..
Preparation of the folders................DONE
org.jdom2.input.JDOMParseException: Error on line 425 of document file:/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml: Character reference "&#8" is an invalid XML character.
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:228)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:277)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:264)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116)
	at msi.gama.doc.util.UnifyDoc.mergeFiles(UnifyDoc.java:109)
	at msi.gama.doc.util.UnifyDoc.unifyAllProjects(UnifyDoc.java:80)
	at msi.gama.doc.util.GenerateCategoryXML.GenerateKeywordsXML(GenerateCategoryXML.java:33)
	at msi.gama.doc.MainGenerateWiki.main(MainGenerateWiki.java:32)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml; lineNumber: 425; columnNumber: 138; Character reference "&#8" is an invalid XML character.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanCharReferenceValue(XMLScanner.java:1338)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2993)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 7 more
Merge all the docGAMA.xml filess................{ummisco.gama.java2d=/home/runner/work/gama/gama/ummisco.gama.java2d/target/docGAMA.xml, msi.gama.core=/home/runner/work/gama/gama/msi.gama.core/target/docGAMA.xml, msi.gama.lang.gaml=/home/runner/work/gama/gama/msi.gama.lang.gaml/target/docGAMA.xml, msi.gaml.extensions.fipa=/home/runner/work/gama/gama/msi.gaml.extensions.fipa/target/docGAMA.xml, ummisco.gaml.extensions.sound=/home/runner/work/gama/gama/ummisco.gaml.extensions.sound/target/docGAMA.xml, irit.gaml.extensions.database=/home/runner/work/gama/gama/irit.gaml.extensions.database/target/docGAMA.xml, simtools.gaml.extensions.physics=/home/runner/work/gama/gama/simtools.gaml.extensions.physics/target/docGAMA.xml, ummisco.gama.opengl=/home/runner/work/gama/gama/ummisco.gama.opengl/target/docGAMA.xml, ummisco.gama.ui.modeling=/home/runner/work/gama/gama/ummisco.gama.ui.modeling/target/docGAMA.xml, ummisco.gaml.extensions.maths=/home/runner/work/gama/gama/ummisco.gaml.extensions.maths/target/docGAMA.xml, ummisco.gama.ui.experiment=/home/runner/work/gama/gama/ummisco.gama.ui.experiment/target/docGAMA.xml, msi.gama.headless=/home/runner/work/gama/gama/msi.gama.headless/target/docGAMA.xml, miat.gaml.extensions.pedestrian=/home/runner/work/gama/gama/miat.gaml.extensions.pedestrian/target/docGAMA.xml, simtools.gaml.extensions.traffic=/home/runner/work/gama/gama/simtools.gaml.extensions.traffic/target/docGAMA.xml, espacedev.gaml.extensions.genstar=/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml, ummisco.gaml.extensions.stats=/home/runner/work/gama/gama/ummisco.gaml.extensions.stats/target/docGAMA.xml, ummisco.gama.ui.shared=/home/runner/work/gama/gama/ummisco.gama.ui.shared/target/docGAMA.xml, msi.gaml.architecture.simplebdi=/home/runner/work/gama/gama/msi.gaml.architecture.simplebdi/target/docGAMA.xml, ummisco.gama.ui.viewers=/home/runner/work/gama/gama/ummisco.gama.ui.viewers/target/docGAMA.xml, ummisco.gama.serialize=/home/runner/work/gama/gama/ummisco.gama.serialize/target/docGAMA.xml, msi.gama.application=/home/runner/work/gama/gama/msi.gama.application/target/docGAMA.xml, ummisco.gama.ui.navigator=/home/runner/work/gama/gama/ummisco.gama.ui.navigator/target/docGAMA.xml, ummisco.gama.network=/home/runner/work/gama/gama/ummisco.gama.network/target/docGAMA.xml}
java.lang.NullPointerException: Cannot invoke "org.jdom2.Document.hasRootElement()" because "doc" is null
	at org.jdom2.output.support.AbstractXMLOutputProcessor.printDocument(AbstractXMLOutputProcessor.java:496)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.process(AbstractXMLOutputProcessor.java:191)
	at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:822)
	at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:394)
	at msi.gama.doc.util.UnifyDoc.unifyAllProjects(UnifyDoc.java:85)
	at msi.gama.doc.util.GenerateCategoryXML.GenerateKeywordsXML(GenerateCategoryXML.java:33)
	at msi.gama.doc.MainGenerateWiki.main(MainGenerateWiki.java:32)
DONE
Transform the docGAMA.xml file into the XML category file ................Beginning of the transformation
[Fatal Error] docGAMAglobal.xml:1:1: Premature end of file.
org.xml.sax.SAXParseException; systemId: file:/home/runner/work/gama/gama/msi.gama.documentation/files/gen/java2xml/docGAMAglobal.xml; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at msi.gama.doc.transform.XmlTransform.transformXML(XmlTransform.java:48)
	at msi.gama.doc.transform.XmlToCategoryXML.createCategoryWiki(XmlToCategoryXML.java:40)
	at msi.gama.doc.util.GenerateCategoryXML.GenerateKeywordsXML(GenerateCategoryXML.java:37)
	at msi.gama.doc.MainGenerateWiki.main(MainGenerateWiki.java:32)
Creation of the wiki page for Operators.....GENERATION OF THE WIKI DOCUMENTATION FROM JAVA CODE
Please notice that the docGAMA.xml files should have been previously generated..
Preparation of the folders................DONE
org.jdom2.input.JDOMParseException: Error on line 425 of document file:/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml: Character reference "&#8" is an invalid XML character.
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:228)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:277)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:264)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116)
	at msi.gama.doc.util.UnifyDoc.mergeFiles(UnifyDoc.java:109)
	at msi.gama.doc.util.UnifyDoc.unify(UnifyDoc.java:58)
	at msi.gama.doc.MainGenerateWiki.main(MainGenerateWiki.java:42)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml; lineNumber: 425; columnNumber: 138; Character reference "&#8" is an invalid XML character.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanCharReferenceValue(XMLScanner.java:1338)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2993)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 6 more
Merge all the docGAMA.xml files................{ummisco.gama.java2d=/home/runner/work/gama/gama/ummisco.gama.java2d/target/docGAMA.xml, msi.gama.core=/home/runner/work/gama/gama/msi.gama.core/target/docGAMA.xml, msi.gama.lang.gaml=/home/runner/work/gama/gama/msi.gama.lang.gaml/target/docGAMA.xml, msi.gaml.extensions.fipa=/home/runner/work/gama/gama/msi.gaml.extensions.fipa/target/docGAMA.xml, irit.gaml.extensions.database=/home/runner/work/gama/gama/irit.gaml.extensions.database/target/docGAMA.xml, simtools.gaml.extensions.physics=/home/runner/work/gama/gama/simtools.gaml.extensions.physics/target/docGAMA.xml, ummisco.gama.opengl=/home/runner/work/gama/gama/ummisco.gama.opengl/target/docGAMA.xml, ummisco.gama.ui.modeling=/home/runner/work/gama/gama/ummisco.gama.ui.modeling/target/docGAMA.xml, ummisco.gaml.extensions.maths=/home/runner/work/gama/gama/ummisco.gaml.extensions.maths/target/docGAMA.xml, ummisco.gama.ui.experiment=/home/runner/work/gama/gama/ummisco.gama.ui.experiment/target/docGAMA.xml, msi.gama.headless=/home/runner/work/gama/gama/msi.gama.headless/target/docGAMA.xml, simtools.gaml.extensions.traffic=/home/runner/work/gama/gama/simtools.gaml.extensions.traffic/target/docGAMA.xml, espacedev.gaml.extensions.genstar=/home/runner/work/gama/gama/espacedev.gaml.extensions.genstar/target/docGAMA.xml, ummisco.gaml.extensions.stats=/home/runner/work/gama/gama/ummisco.gaml.extensions.stats/target/docGAMA.xml, ummisco.gama.ui.shared=/home/runner/work/gama/gama/ummisco.gama.ui.shared/target/docGAMA.xml, msi.gaml.architecture.simplebdi=/home/runner/work/gama/gama/msi.gaml.architecture.simplebdi/target/docGAMA.xml, ummisco.gama.ui.viewers=/home/runner/work/gama/gama/ummisco.gama.ui.viewers/target/docGAMA.xml, ummisco.gama.serialize=/home/runner/work/gama/gama/ummisco.gama.serialize/target/docGAMA.xml, msi.gama.application=/home/runner/work/gama/gama/msi.gama.application/target/docGAMA.xml, ummisco.gama.ui.navigator=/home/runner/work/gama/gama/ummisco.gama.ui.navigator/target/docGAMA.xml, ummisco.gama.network=/home/runner/work/gama/gama/ummisco.gama.network/target/docGAMA.xml}
java.lang.NullPointerException: Cannot invoke "org.jdom2.Document.hasRootElement()" because "doc" is null
	at org.jdom2.output.support.AbstractXMLOutputProcessor.printDocument(AbstractXMLOutputProcessor.java:496)
	at org.jdom2.output.support.AbstractXMLOutputProcessor.process(AbstractXMLOutputProcessor.java:191)
	at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:822)
	at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:394)
	at msi.gama.doc.util.UnifyDoc.unify(UnifyDoc.java:63)
	at msi.gama.doc.MainGenerateWiki.main(MainGenerateWiki.java:42)
DONE
Transform the docGAMA.xml file into Wiki Files (md) and create/update them in the gama.wiki folder................Beginning of the transformation
[Fatal Error] docGAMAglobal.xml:1:1: Premature end of file.
```

**Comment by hqnghi88** [comment]
fixed! the rest is git commit and git push command to gama.wiki or githubio i think you can manage well.

**Comment by RoiArthurB** [comment]
Fixed https://github.com/gama-platform/gama/runs/6071759659?check_suite_focus=true thanks Sensei @hqnghi88 🙏💪
