### ISSUE TITLE
[Serialization] Reloading simulation from file doesn't work anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#351]
**Describe the bug**
It looks like saving a simulation into a file is working (though hard to check, but at least a file is created) but when trying to restore the simulation from a file an error is raised

**To Reproduce**
1. Go to `Create Simulation From File.gaml`
2. Run the first experiment up to cycle 5
3. now try to run the second simulation
4. See error:
```
1 occurence in 2. Reload Simulation0 at cycle 0: Java error: I/O error
in Simulation 0
in agent 2. Reload Simulation0
IOException: java.lang.NullPointerException
org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:377)
org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:801)
gama.extension.serialize.binary.BinarySerialiser.restoreAgentFromBytes(BinarySerialiser.java:95)
gama.extension.serialize.binary.BinarySerialisation.restoreFromBytes(BinarySerialisation.java:179)
gama.extension.serialize.binary.BinarySerialisation.restoreFromFile(BinarySerialisation.java:131)
gama.extension.serialize.gaml.CreateAgentsFromSerialisedFileDelegate.createAgents(CreateAgentsFromSerialisedFileDelegate.java:51)
gama.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:460)
in create simulation from: input ;
```
And here is what I have in the eclipse console:
```
unable to decode:
java.io.IOException: java.lang.NullPointerException: Cannot load from object array because the return value of "org.nustaq.serialization.FSTClazzInfo$FSTFieldInfo.getPossibleClasses()" is null
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:377)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:801)
	at gama.extension.serialize.binary.BinarySerialiser.restoreAgentFromBytes(BinarySerialiser.java:95)
	at gama.extension.serialize.binary.BinarySerialisation.restoreFromBytes(BinarySerialisation.java:179)
	at gama.extension.serialize.binary.BinarySerialisation.restoreFromFile(BinarySerialisation.java:131)
	at gama.extension.serialize.gaml.CreateAgentsFromSerialisedFileDelegate.createAgents(CreateAgentsFromSerialisedFileDelegate.java:51)
	at gama.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:460)
	at gama.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at gama.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at gama.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:509)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.runtime.IScope.execute(IScope.java:414)
	at gama.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at gama.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:59)
	at gama.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at gama.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at gama.core.runtime.ExecutionScope.execute(ExecutionScope.java:509)
	at gama.core.runtime.IScope.execute(IScope.java:443)
	at gama.core.metamodel.agent.MinimalAgent.init(MinimalAgent.java:243)
	at gama.core.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:456)
	at gama.core.runtime.ExecutionScope.init(ExecutionScope.java:601)
	at gama.core.kernel.experiment.DefaultExperimentController.schedule(DefaultExperimentController.java:200)
	at gama.core.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:536)
	at gama.core.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:713)
	at gama.core.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:771)
	at gama.core.kernel.experiment.DefaultExperimentController.processUserCommand(DefaultExperimentController.java:72)
	at gama.core.kernel.experiment.AbstractExperimentController.lambda$0(AbstractExperimentController.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException: Cannot load from object array because the return value of "org.nustaq.serialization.FSTClazzInfo$FSTFieldInfo.getPossibleClasses()" is null
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:523)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:487)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:447)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:375)
	... 28 more
```

**Expected behavior**
Restoring simulations works again

**Additional context**
May be related to previous serialization issues: #244 and #246

**Comment by AlexisDrogoul** [comment]
This issue should now be completely fixed. Please test.
